# Generated by Django 5.1.15 on 2026-07-07 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("comercial", "0050_eliminar_montaje_de_lujo"),
    ]

    operations = [
        migrations.CreateModel(
            name="BadgeServicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.CharField(max_length=40)),
                ("orden", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Badge de servicio (portada)",
                "verbose_name_plural": "Badges de servicio (portada)",
                "ordering": ["orden"],
            },
        ),
        migrations.CreateModel(
            name="ConfiguracionCatalogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_empresa",
                    models.CharField(default="Quinta Ko'ox Tanil", max_length=100),
                ),
                (
                    "ubicacion",
                    models.CharField(default="Umán, Yucatán · México", max_length=150),
                ),
                (
                    "subtitulo_portada",
                    models.CharField(
                        default="Donde los momentos se vuelven recuerdos",
                        max_length=150,
                    ),
                ),
                (
                    "telefono",
                    models.CharField(default="(999) 445 71 78", max_length=20),
                ),
                ("email_contacto", models.EmailField(blank=True, max_length=254)),
                (
                    "sitio_web",
                    models.CharField(default="quintakooxtanil.com", max_length=100),
                ),
                ("url_cotizador", models.CharField(blank=True, max_length=150)),
                ("url_portal_clientes", models.CharField(blank=True, max_length=150)),
                ("direccion", models.CharField(blank=True, max_length=200)),
                ("facebook", models.CharField(blank=True, max_length=100)),
                ("instagram", models.CharField(blank=True, max_length=100)),
                (
                    "imagen_portada",
                    models.ImageField(
                        blank=True, null=True, upload_to="catalogo/portada/"
                    ),
                ),
                (
                    "imagen_footer",
                    models.ImageField(
                        blank=True, null=True, upload_to="catalogo/footer/"
                    ),
                ),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuración del Catálogo",
                "verbose_name_plural": "Configuración del Catálogo",
            },
        ),
        migrations.CreateModel(
            name="PaqueteCatalogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "imagen",
                    models.ImageField(
                        blank=True, null=True, upload_to="catalogo/paquetes/"
                    ),
                ),
                (
                    "proveedor",
                    models.CharField(
                        blank=True,
                        help_text="Ej: David Vera Banquetes — se muestra en el crédito al pie",
                        max_length=100,
                    ),
                ),
                (
                    "precio_venta_fijo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Precio de venta al cliente. Vacío = 'Precio por confirmar'.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Paquete completo",
                "verbose_name_plural": "Paquetes completos",
                "ordering": ["orden"],
            },
        ),
        migrations.CreateModel(
            name="SeccionCatalogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(help_text="Ej: 01, 02, 03", max_length=4)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Identificador interno, ej: eventos", unique=True
                    ),
                ),
                (
                    "titulo",
                    models.CharField(help_text="Ej: El espacio para", max_length=100),
                ),
                (
                    "titulo_enfasis",
                    models.CharField(
                        blank=True,
                        help_text="Parte en cursiva/verde del título, ej: tu celebración",
                        max_length=100,
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
                (
                    "imagen_hero",
                    models.ImageField(
                        blank=True, null=True, upload_to="catalogo/secciones/"
                    ),
                ),
                ("imagen_hero_caption", models.CharField(blank=True, max_length=150)),
                (
                    "nota_pie",
                    models.CharField(
                        blank=True,
                        help_text="Ej: La carpa tiene costo adicional y está sujeta a disponibilidad.",
                        max_length=300,
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0)),
                ("activa", models.BooleanField(default=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Sección del catálogo",
                "verbose_name_plural": "Secciones del catálogo",
                "ordering": ["orden"],
            },
        ),
        migrations.CreateModel(
            name="ItemPaqueteCatalogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grupo",
                    models.CharField(
                        choices=[
                            ("MOBILIARIO", "Mobiliario"),
                            ("CRISTALERIA", "Cristalería"),
                            ("CRISTALERIA_PREMIUM", "Cristalería premium"),
                        ],
                        max_length=25,
                    ),
                ),
                ("texto", models.CharField(max_length=200)),
                ("orden", models.PositiveIntegerField(default=0)),
                (
                    "paquete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="catalogo.paquetecatalogo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de paquete",
                "verbose_name_plural": "Items de paquete",
                "ordering": ["grupo", "orden"],
            },
        ),
        migrations.CreateModel(
            name="CaracteristicaSeccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.CharField(max_length=200)),
                ("orden", models.PositiveIntegerField(default=0)),
                (
                    "seccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="caracteristicas",
                        to="catalogo.seccioncatalogo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Característica",
                "verbose_name_plural": "Características",
                "ordering": ["orden"],
            },
        ),
        migrations.CreateModel(
            name="TarjetaCatalogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        blank=True,
                        help_text="Si hay producto vinculado y este campo está vacío, se usa producto.nombre",
                        max_length=100,
                    ),
                ),
                ("subtitulo", models.CharField(blank=True, max_length=150)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "imagen",
                    models.ImageField(
                        blank=True, null=True, upload_to="catalogo/tarjetas/"
                    ),
                ),
                (
                    "badge_texto",
                    models.CharField(
                        blank=True, help_text="Ej: SET PARA 10 INVITADOS", max_length=60
                    ),
                ),
                ("mostrar_precio", models.BooleanField(default=True)),
                (
                    "unidad_precio",
                    models.CharField(
                        blank=True,
                        help_text="Ej: +IVA, /noche — se muestra junto al precio",
                        max_length=30,
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0)),
                ("activa", models.BooleanField(default=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "producto",
                    models.ForeignKey(
                        blank=True,
                        help_text="Selecciona el producto real del ERP. El precio se toma de aquí, nunca se escribe a mano.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tarjetas_catalogo",
                        to="comercial.producto",
                    ),
                ),
                (
                    "seccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarjetas",
                        to="catalogo.seccioncatalogo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarjeta del catálogo",
                "verbose_name_plural": "Tarjetas del catálogo",
                "ordering": ["orden"],
            },
        ),
        migrations.CreateModel(
            name="DescuentoTarjeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "precio_regular",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "precio_descuento",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "etiqueta_badge",
                    models.CharField(
                        default="Oferta",
                        help_text="Ej: Oferta · Reserva en octubre",
                        max_length=60,
                    ),
                ),
                (
                    "nota_vigencia",
                    models.CharField(
                        help_text="Ej: Precio válido para eventos apartados durante octubre 2026. A partir de noviembre 2026: $4,400.00 +IVA.",
                        max_length=250,
                    ),
                ),
                ("vigente_desde", models.DateField(blank=True, null=True)),
                ("vigente_hasta", models.DateField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "tarjeta",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="descuento",
                        to="catalogo.tarjetacatalogo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Descuento de tarjeta",
                "verbose_name_plural": "Descuentos de tarjeta",
            },
        ),
    ]
