# Generated by Django 5.1.15 on 2026-07-07 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0001_catalogo_inicial"),
        ("comercial", "0050_eliminar_montaje_de_lujo"),
    ]

    operations = [
        migrations.AddField(
            model_name="paquetecatalogo",
            name="producto",
            field=models.ForeignKey(
                blank=True,
                help_text="Si ligas un Producto (paquete) del ERP, el precio se toma de ahí y se actualiza solo. Déjalo vacío para paquetes de proveedor externo con precio_venta_fijo manual.",
                limit_choices_to={"es_paquete": True},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="paquetes_catalogo",
                to="comercial.producto",
            ),
        ),
        migrations.AlterField(
            model_name="paquetecatalogo",
            name="precio_venta_fijo",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Solo se usa si no hay Producto ligado. Vacío = 'Precio por confirmar'.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tarjetacatalogo",
            name="unidad_precio",
            field=models.CharField(
                blank=True,
                help_text="Ej: /noche, /persona — se muestra junto al precio. El precio ya incluye IVA, no escribas '+IVA' aquí.",
                max_length=30,
            ),
        ),
    ]
