# Generated by Django 5.1.15 on 2026-07-08 18:49
"""
Carga el contenido REAL del catálogo (extraído de Catalogo_QKT_v17.pdf,
16 páginas) a los modelos dinámicos. Idempotente (update_or_create) —
segura de re-ejecutar. Se aplica sola en el deploy, sin necesitar correr
ningún comando manual.

Notas de precios (importante, revisar):
- Los productos con receta de costeo (Producto.sugerencia_precio) siguen
  la convención del proyecto: el valor guardado es SIN IVA, el catálogo
  y el cotizador le suman 16% al mostrarlo ("IVA incluido").
- El PDF original mostraba precios "+IVA" (es decir, SIN IVA) en todos
  lados. Para "Renta de Inmueble" no existe un Producto real en el ERP,
  así que se crea uno nuevo con el precio SIN IVA tal como aparecía en
  el PDF ($4,400.00), consistente con el resto del sistema.
- El descuento de octubre 2026 ($4,400 -> $2,999, ambos "+IVA" en el PDF
  original) se convierte aquí a los montos YA CON IVA incluido
  ($5,104.00 -> $3,478.84), para que se vea consistente con el resto del
  catálogo (que ahora siempre muestra "IVA incluido"). Si Elian prefiere
  otro monto exacto, se edita directo en el admin (Descuento de tarjeta).
"""
from decimal import Decimal, ROUND_HALF_UP

from django.db import migrations

CENT = Decimal('0.01')


def _con_iva(valor):
    return (valor * Decimal('1.16')).quantize(CENT, rounding=ROUND_HALF_UP)


def cargar(apps, schema_editor):
    ConfiguracionCatalogo = apps.get_model('catalogo', 'ConfiguracionCatalogo')
    BadgeServicio = apps.get_model('catalogo', 'BadgeServicio')
    SeccionCatalogo = apps.get_model('catalogo', 'SeccionCatalogo')
    CaracteristicaSeccion = apps.get_model('catalogo', 'CaracteristicaSeccion')
    TarjetaCatalogo = apps.get_model('catalogo', 'TarjetaCatalogo')
    DescuentoTarjeta = apps.get_model('catalogo', 'DescuentoTarjeta')
    PaqueteCatalogo = apps.get_model('catalogo', 'PaqueteCatalogo')
    ItemPaqueteCatalogo = apps.get_model('catalogo', 'ItemPaqueteCatalogo')
    Producto = apps.get_model('comercial', 'Producto')

    # ── Configuración general ────────────────────────────────────────────
    config, _ = ConfiguracionCatalogo.objects.get_or_create(pk=1)
    config.nombre_empresa = "Quinta Ko'ox Tanil"
    config.ubicacion = "Umán, Yucatán · México"
    config.subtitulo_portada = "Donde los momentos se vuelven recuerdos"
    config.telefono = "(999) 445 71 78"
    config.sitio_web = "quintakooxtanil.com"
    config.url_cotizador = "quintakooxtanil.com/cotizar"
    config.url_portal_clientes = "quintakooxtanil.com/mi-evento"
    config.direccion = "Carretera Tanil — Ticimul Km 1.92, Umán, Yucatán"
    config.instagram = "@quintakooxtanil"
    config.save()

    # ── Badges de portada ────────────────────────────────────────────────
    for i, texto in enumerate([
        'EVENTOS Y BODAS', 'PASADÍA', 'HOSPEDAJE AIRBNB',
        'MOBILIARIO Y MONTAJE', 'BARRA Y CATERING',
    ]):
        BadgeServicio.objects.update_or_create(texto=texto, defaults={'orden': i})

    # ── 01 · EVENTOS ─────────────────────────────────────────────────────
    eventos, _ = SeccionCatalogo.objects.update_or_create(
        slug='eventos',
        defaults=dict(
            numero='01', titulo='El espacio para', titulo_enfasis='tu celebración',
            descripcion=(
                'Jardín bajo los árboles, pista de baile y salón con arcos coloniales. '
                'Capacidad para hasta 200 invitados, con la atención personalizada de '
                'una familia que vive para que tu evento sea perfecto.'
            ),
            imagen_hero_caption='Jardín, luces colgantes y los arcos coloniales de la Quinta al atardecer',
            nota_pie=(
                'La carpa tiene costo adicional y está sujeta a disponibilidad. Es '
                'opcional: brinda protección climática y realza el montaje de tu '
                'evento — consulta disponibilidad.'
            ),
            orden=1,
        ),
    )
    for i, texto in enumerate([
        'Jardín con capacidad para hasta 200 personas',
        'Pista de baile bajo los árboles y las estrellas',
        'Salón cubierto con arcos coloniales',
        'Área de bar integrada al espacio',
        'Estacionamiento dentro de la Quinta',
        'Uso exclusivo durante tu evento',
    ]):
        CaracteristicaSeccion.objects.update_or_create(
            seccion=eventos, texto=texto, defaults={'orden': i}
        )

    # "Renta de Inmueble" no existe como Producto — se crea (precio SIN IVA,
    # el catálogo le suma 16% igual que a cualquier otro producto ligado).
    producto_evento = Producto.objects.filter(nombre__icontains='Renta').filter(
        nombre__icontains='Inmueble'
    ).first()
    if not producto_evento:
        producto_evento = Producto.objects.create(
            nombre='Renta de Inmueble',
            margen_ganancia=Decimal('0.30'),
            precio_venta_fijo=Decimal('4400.00'),
            visible_cotizador=False,  # solo para el catálogo, no altera el cotizador público
        )

    tarjeta_evento, _ = TarjetaCatalogo.objects.update_or_create(
        seccion=eventos, orden=0,
        defaults=dict(
            producto=producto_evento,
            titulo='Renta del inmueble',
            descripcion=(
                'Solo renta del inmueble · 6 horas · acceso a todas las áreas · '
                'puedes traer tus propios proveedores de confianza.'
            ),
            badge_texto='6 horas · acceso a todas las áreas',
            mostrar_precio=True,
        ),
    )
    # Oferta de octubre 2026 (montos ya con IVA incluido — ver nota arriba).
    DescuentoTarjeta.objects.update_or_create(
        tarjeta=tarjeta_evento,
        defaults=dict(
            precio_regular=_con_iva(Decimal('4400.00')),
            precio_descuento=_con_iva(Decimal('2999.00')),
            etiqueta_badge='Oferta · Reserva en octubre',
            nota_vigencia=(
                'Precio válido para eventos apartados durante octubre 2026. '
                'A partir de noviembre 2026 aplica el precio regular.'
            ),
            vigente_hasta='2026-10-31',
            activo=True,
        ),
    )

    # ── 02 · PASADÍA ─────────────────────────────────────────────────────
    pasadia, _ = SeccionCatalogo.objects.update_or_create(
        slug='pasadia',
        defaults=dict(
            numero='02', titulo='Un día para', titulo_enfasis='descansar',
            descripcion=(
                'La Quinta abre sus puertas para que tú y tu familia disfruten un '
                'día completo de descanso y naturaleza. Sin eventos paralelos: solo '
                'tu grupo y todo el espacio para ustedes.'
            ),
            imagen_hero_caption='Pasadía en la Quinta — alberca privada, jardín y naturaleza yucateca',
            nota_pie='Disponible todos los días del año · Barra y catering opcionales.',
            orden=2,
        ),
    )
    for i, texto in enumerate([
        'Alberca privada de uso exclusivo',
        'Áreas verdes y jardines con palmeras',
        'Horario 10:00 a.m. – 7:00 p.m.',
        'Capacidad máxima: 20 personas',
        'Mesas y sillas para 20 personas',
        'Brincolín y carrito de bolis (sabores surtidos)',
        'Uso de 1 habitación incluido',
        'Estacionamiento dentro de la Quinta',
        'Corredor colonial techado con vista al jardín y alberca',
        'Área de foam y juegos para los más pequeños',
        'Patio amplio para actividades al aire libre',
        'Ambiente familiar, privado y tranquilo',
    ]):
        CaracteristicaSeccion.objects.update_or_create(
            seccion=pasadia, texto=texto, defaults={'orden': i}
        )

    # Reutiliza el Producto real ya usado por el cotizador público si existe
    # (buscado igual que en views_cotizador.py: 'Pastadía' o 'Pasadia').
    producto_pasadia = (
        Producto.objects.filter(nombre__icontains='Pastad').first()
        or Producto.objects.filter(nombre__icontains='Pasadia').first()
    )
    if not producto_pasadia:
        producto_pasadia = Producto.objects.create(
            nombre='Pasadía',
            margen_ganancia=Decimal('0.30'),
            precio_venta_fijo=Decimal('1500.00'),
            visible_cotizador=False,
        )

    TarjetaCatalogo.objects.update_or_create(
        seccion=pasadia, orden=0,
        defaults=dict(
            producto=producto_pasadia,
            titulo='Pasadía en la Quinta',
            descripcion=(
                'Hasta 20 personas · Ampliación a 2 habitaciones disponible '
                '(costo adicional, consulta en el admin).'
            ),
            badge_texto='10:00 a.m. – 7:00 p.m. · hasta 20 personas',
            mostrar_precio=True,
        ),
    )

    # ── 03 · HOSPEDAJE ───────────────────────────────────────────────────
    hospedaje, _ = SeccionCatalogo.objects.update_or_create(
        slug='hospedaje',
        defaults=dict(
            numero='03', titulo='Habitaciones en', titulo_enfasis='la Quinta',
            descripcion=(
                'Escapa del ritmo de la ciudad sin salir de Yucatán. Dos '
                'habitaciones únicas disponibles en Airbnb, rodeadas de naturaleza '
                'y a 20 minutos del centro de Mérida. Reserva directamente en '
                'Airbnb · también disponible la casa completa para grupos — '
                'consulta disponibilidad.'
            ),
            nota_pie=(
                'Tarifa dinámica según temporada y demanda · Precio y '
                'disponibilidad en tiempo real solo a través de Airbnb.'
            ),
            orden=3,
        ),
    )
    for i, texto in enumerate([
        'Cama doble o matrimonial',
        'Baño privado con amenidades',
        'Acceso a alberca y jardines',
        'Wi-Fi incluido',
        'Corredor colonial y áreas verdes',
        'A 20 min del centro de Mérida',
    ]):
        CaracteristicaSeccion.objects.update_or_create(
            seccion=hospedaje, texto=texto, defaults={'orden': i}
        )

    # Sin Producto: la tarifa es dinámica vía Airbnb, no hay precio fijo del
    # ERP que mostrar. mostrar_precio=False — el rango se explica en el texto.
    TarjetaCatalogo.objects.update_or_create(
        seccion=hospedaje, orden=0,
        defaults=dict(
            titulo="Ka'an Room",
            subtitulo='airbnb.mx/h/kaanroombyqkt',
            descripcion=(
                'Diseño único con vista a la naturaleza y un ambiente sereno '
                'para desconectarte. Desde $700–$800 MXN/noche.'
            ),
            badge_texto='Habitación · Airbnb',
            mostrar_precio=False,
        ),
    )
    TarjetaCatalogo.objects.update_or_create(
        seccion=hospedaje, orden=1,
        defaults=dict(
            titulo='Otoch Room',
            subtitulo='airbnb.mx/h/otochroombyqkt',
            descripcion=(
                'Ambiente acogedor y privado, ideal para una escapada tranquila '
                'en pareja o individual. Desde $700–$800 MXN/noche.'
            ),
            badge_texto='Habitación · Airbnb',
            mostrar_precio=False,
        ),
    )

    # ── 04 · MOBILIARIO ──────────────────────────────────────────────────
    mobiliario, _ = SeccionCatalogo.objects.update_or_create(
        slug='mobiliario',
        defaults=dict(
            numero='04', titulo='Líneas de', titulo_enfasis='mobiliario',
            descripcion=(
                'Mesas, sillas y montaje de mesa para crear el ambiente que '
                'imaginas. Un set completo por cada 10 invitados.'
            ),
            nota_pie='Mobiliario en colaboración con David Vera Banquetes',
            orden=4,
        ),
    )

    MOBILIARIO_DATA = {
        'Mobiliario Tiffany': dict(
            subtitulo='Clásico, limpio y luminoso',
            descripcion=(
                '1 mesa redonda o cuadrada con mantel a elegir · 10 sillas Tiffany '
                'en blanco o dorado · 10 cojines blancos.'
            ),
            orden=0,
        ),
        'Mobiliario Crossback': dict(
            subtitulo='Madera natural con aire cálido',
            descripcion=(
                '1 mesa redonda o cuadrada con mantel a elegir · 10 sillas '
                'crossback en nogal o natural.'
            ),
            orden=1,
        ),
        'Mobiliario Vintage': dict(
            subtitulo='Carácter rústico y atemporal',
            descripcion=(
                '1 mesa de madera cuadrada en acabado nogal o vintage · 10 sillas '
                'crossback en nogal o natural.'
            ),
            orden=2,
        ),
    }
    for nombre, datos in MOBILIARIO_DATA.items():
        producto = Producto.objects.filter(nombre=nombre).first()
        if not producto:
            continue  # sembrado en 0043/0048 — si falta, se liga manualmente después
        TarjetaCatalogo.objects.update_or_create(
            seccion=mobiliario, producto=producto,
            defaults=dict(
                subtitulo=datos['subtitulo'],
                descripcion=datos['descripcion'],
                badge_texto='SET PARA 10 INVITADOS',
                orden=datos['orden'],
                mostrar_precio=True,
            ),
        )

    # ── Paquetes completos (David Vera Banquetes) — "Precios por confirmar" ──
    PAQUETES_DATA = {
        'Básico': dict(
            orden=0,
            mobiliario=[
                '1 mesa cuadrada o redonda, mantel color básico',
                '10 sillas Tiffany blancas o doradas',
                '10 cojines blancos',
            ],
            cristaleria_grupo='CRISTALERIA',
            cristaleria=[
                '10 platos trinche blancos',
                '10 platos botaneros blancos',
                '10 bajo platos dorados',
                '10 vasos cubero',
                '10 copas flauta',
                '10 cubiertos de plata (tenedor y cuchillo)',
                '10 paños de boca',
            ],
        ),
        'Tiffany': dict(
            orden=1,
            mobiliario=[
                '1 mesa cuadrada o redonda, mantel color básico',
                '10 sillas Tiffany blancas o doradas',
                '10 cojines blancos',
            ],
            cristaleria_grupo='CRISTALERIA_PREMIUM',
            cristaleria=[
                '10 platos blancos, borde dorado o plato negro',
                '10 platos botaneros a juego',
                '10 bajo platos: macramé, dorado, perlas o mimbre',
                '10 vasos old fashion, cortado o cubero',
                '10 copas (vino, flauta o de color)',
                '10 cubiertos dorados o plata (tenedor y cuchillo)',
                '10 paños de boca',
            ],
        ),
        'Crossback': dict(
            orden=2,
            mobiliario=[
                '1 mesa de madera',
                '10 sillas de madera crossback',
            ],
            cristaleria_grupo='CRISTALERIA_PREMIUM',
            cristaleria=[
                '10 platos blancos, borde dorado o plato negro',
                '10 platos botaneros a juego',
                '10 bajo platos: macramé, dorado, perlas o mimbre',
                '10 vasos old fashion, cortado o cubero',
                '10 copas (vino, flauta o de color)',
                '10 cubiertos dorados o plata (tenedor y cuchillo)',
                '10 paños de boca',
            ],
        ),
    }
    for nombre, datos in PAQUETES_DATA.items():
        paquete, _ = PaqueteCatalogo.objects.update_or_create(
            nombre=nombre,
            defaults=dict(proveedor='David Vera Banquetes', orden=datos['orden']),
            # precio_venta_fijo se deja vacío a propósito: "Precios por confirmar"
        )
        paquete.items.all().delete()  # re-sembrado limpio, evita duplicados si se re-corre
        orden = 0
        for texto in datos['mobiliario']:
            ItemPaqueteCatalogo.objects.create(
                paquete=paquete, grupo='MOBILIARIO', texto=texto, orden=orden
            )
            orden += 1
        orden = 0
        for texto in datos['cristaleria']:
            ItemPaqueteCatalogo.objects.create(
                paquete=paquete, grupo=datos['cristaleria_grupo'], texto=texto, orden=orden
            )
            orden += 1

    # ── 05 · SERVICIOS ADICIONALES ───────────────────────────────────────
    # No encaja en una de las 4 secciones numeradas del PDF original (es una
    # grilla suelta de 6 extras); se modela como su propia sección, sin precio
    # (cada extra requiere cotización particular).
    adicionales, _ = SeccionCatalogo.objects.update_or_create(
        slug='servicios-adicionales',
        defaults=dict(
            numero='05', titulo='Personaliza', titulo_enfasis='tu evento',
            descripcion='Agrega los servicios que necesitas y construye la celebración exacta que imaginas.',
            orden=5,
        ),
    )
    SERVICIOS_ADICIONALES = [
        ('ESPACIO ADICIONAL', 'Carpa',
         'Espacio opcional con costo adicional. Brinda protección climática y '
         'realza el montaje. Costo según dimensiones requeridas.'),
        ('BEBIDAS', 'Servicio de Barra',
         'Cerveza Nacional ilimitada · Barra Nacional y Premium · Cócteles '
         'clásicos y de autor · Mixología.'),
        ('ALIMENTOS', 'Catering y Taquiza',
         'Menú personalizado con staff de meseros · Taquiza con taquero, '
         'guisados y complementos.'),
        ('MÚSICA', 'Servicio de DJ',
         'DJ Básico con sonido profesional · DJ con Iluminación, setup '
         'completo con luces · Programación personalizada.'),
        ('ARRENDAMIENTO', 'Solo Mobiliario',
         'Renta de mesas y sillas para eventos externos. Líneas Tiffany, '
         'Crossback y Vintage disponibles.'),
        ('RESERVACIONES', 'Disponibilidad',
         'Sujeta a disponibilidad — reserva con anticipación. Consulta '
         'precios según fecha y número de invitados.'),
    ]
    for i, (badge, titulo, desc) in enumerate(SERVICIOS_ADICIONALES):
        TarjetaCatalogo.objects.update_or_create(
            seccion=adicionales, titulo=titulo,
            defaults=dict(
                badge_texto=badge, descripcion=desc, orden=i, mostrar_precio=False,
            ),
        )


def revertir(apps, schema_editor):
    # No se borra nada: es contenido editorial, no auditoría. Si algo salió
    # mal, se corrige a mano en el admin.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0002_paquetecatalogo_producto_and_more"),
        ("comercial", "0050_eliminar_montaje_de_lujo"),
    ]

    operations = [
        migrations.RunPython(cargar, revertir),
    ]
