# Generated by Django 5.1.15 on 2026-07-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0003_cargar_contenido_real_v17"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracioncatalogo",
            name="eyebrow_contacto",
            field=models.CharField(default="Reserva tu fecha", max_length=60),
        ),
        migrations.AddField(
            model_name="configuracioncatalogo",
            name="nombre_empresa_enfasis",
            field=models.CharField(
                default="Ko'ox Tanil",
                help_text='Parte en cursiva/dorado del nombre en la portada (ej. "Ko\'ox Tanil").',
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="configuracioncatalogo",
            name="subtitulo_contacto",
            field=models.CharField(
                default="Estamos para acompañarte en cada detalle", max_length=150
            ),
        ),
        migrations.AddField(
            model_name="configuracioncatalogo",
            name="tagline_cierre",
            field=models.CharField(
                default="A 20 minutos de Mérida · Abiertos 365 días al año",
                help_text="Frase final de la última página, junto al nombre de la empresa.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="configuracioncatalogo",
            name="titulo_catalogo",
            field=models.CharField(
                default="Catálogo",
                max_length=60,
                verbose_name="Título del catálogo (portada)",
            ),
        ),
        migrations.AddField(
            model_name="configuracioncatalogo",
            name="titulo_catalogo_enfasis",
            field=models.CharField(
                default="de Servicios",
                max_length=60,
                verbose_name="Título del catálogo — énfasis (portada)",
            ),
        ),
        migrations.AddField(
            model_name="configuracioncatalogo",
            name="titulo_contacto",
            field=models.CharField(default="Hablemos de", max_length=100),
        ),
        migrations.AddField(
            model_name="configuracioncatalogo",
            name="titulo_contacto_enfasis",
            field=models.CharField(default="tu evento", max_length=100),
        ),
        migrations.AddField(
            model_name="configuracioncatalogo",
            name="url_kaan_room",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Link Ka'an Room (Airbnb)"
            ),
        ),
        migrations.AddField(
            model_name="configuracioncatalogo",
            name="url_otoch_room",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Link Otoch Room (Airbnb)"
            ),
        ),
        migrations.AddField(
            model_name="seccioncatalogo",
            name="categoria",
            field=models.CharField(
                blank=True,
                help_text="Texto corto junto al número, ej: 'Eventos sociales y bodas'. Si se deja vacío, se usa el título completo.",
                max_length=80,
                verbose_name="Categoría (encabezado corto)",
            ),
        ),
        migrations.AlterField(
            model_name="configuracioncatalogo",
            name="nombre_empresa",
            field=models.CharField(
                default="Quinta",
                help_text="Parte NO destacada del nombre en la portada (ej. 'Quinta').",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="seccioncatalogo",
            name="numero",
            field=models.CharField(
                blank=True,
                help_text="Ej: 01, 02, 03. Vacío = sección sin numerar (ej. servicios adicionales).",
                max_length=4,
            ),
        ),
    ]
