# Generated by Django 5.1.15 on 2026-07-09 20:02
"""
Restablece el contenido del catálogo (portada, badges, categorías de
sección, contacto) a los valores EXACTOS del PDF original (Catalogo_QKT_v17),
sobreescribiendo cualquier edición manual previa hecha desde el admin
(Elian reportó diferencias de texto tras configurar a mano). Idempotente.

No toca imágenes ni el campo producto ligado de las tarjetas — solo texto
y estructura, tal como se pidió: "no te preocupes por qué producto ligar,
lo que me interesa ahorita es la estructura, títulos, subtítulos y textos".
"""
from django.db import migrations


def resetear(apps, schema_editor):
    ConfiguracionCatalogo = apps.get_model('catalogo', 'ConfiguracionCatalogo')
    BadgeServicio = apps.get_model('catalogo', 'BadgeServicio')
    SeccionCatalogo = apps.get_model('catalogo', 'SeccionCatalogo')

    # ── Configuración: portada + contacto ────────────────────────────────
    config, _ = ConfiguracionCatalogo.objects.get_or_create(pk=1)
    config.nombre_empresa = 'Quinta'
    config.nombre_empresa_enfasis = "Ko'ox Tanil"
    config.ubicacion = 'Umán, Yucatán · México'
    config.titulo_catalogo = 'Catálogo'
    config.titulo_catalogo_enfasis = 'de Servicios'
    config.subtitulo_portada = 'Donde los momentos se vuelven recuerdos'
    config.telefono = '(999) 445 71 78'
    config.sitio_web = 'quintakooxtanil.com'
    config.url_cotizador = 'quintakooxtanil.com/cotizar'
    config.url_portal_clientes = 'quintakooxtanil.com/mi-evento'
    config.url_kaan_room = 'airbnb.mx/h/kaanroombyqkt'
    config.url_otoch_room = 'airbnb.mx/h/otochroombyqkt'
    config.direccion = 'Carretera Tanil — Ticimul Km 1.92, Umán, Yucatán'
    config.facebook = 'Facebook'
    config.instagram = '@quintakooxtanil'
    config.eyebrow_contacto = 'Reserva tu fecha'
    config.titulo_contacto = 'Hablemos de'
    config.titulo_contacto_enfasis = 'tu evento'
    config.subtitulo_contacto = 'Estamos para acompañarte en cada detalle'
    config.tagline_cierre = 'A 20 minutos de Mérida · Abiertos 365 días al año'
    config.save()

    # ── Badges de portada: se limpian y recrean para eliminar cualquier
    #    edición manual con texto acortado (ej. "EVENTOS" en vez de
    #    "EVENTOS Y BODAS"). ──────────────────────────────────────────────
    BadgeServicio.objects.all().delete()
    for i, texto in enumerate([
        'EVENTOS Y BODAS', 'PASADÍA', 'HOSPEDAJE AIRBNB',
        'MOBILIARIO Y MONTAJE', 'BARRA Y CATERING',
    ]):
        BadgeServicio.objects.create(texto=texto, orden=i)

    # ── Categoría (encabezado corto) de cada sección ─────────────────────
    # Nota: se usa .save() por instancia (no .filter().update()) a propósito:
    # .update() en queryset NO dispara auto_now, y el caché del PDF depende
    # de que actualizado_en cambie para invalidarse correctamente.
    CATEGORIAS = {
        'eventos': 'Eventos sociales y bodas',
        'pasadia': 'Pasadía en la Quinta',
        'hospedaje': 'Hospedaje',
        'mobiliario': 'Mobiliario',
    }
    for slug, categoria in CATEGORIAS.items():
        seccion = SeccionCatalogo.objects.filter(slug=slug).first()
        if seccion:
            seccion.categoria = categoria
            seccion.save()

    # La sección "servicios-adicionales" es una adición propia (no existía
    # como sección numerada en el PDF original) — se deja sin número para
    # que no aparezca como "05 —", más fiel al original.
    adicionales = SeccionCatalogo.objects.filter(slug='servicios-adicionales').first()
    if adicionales:
        adicionales.numero = ''
        adicionales.categoria = 'Servicios adicionales'
        adicionales.save()


def revertir(apps, schema_editor):
    # Contenido editorial, no auditoría: no se revierte automáticamente.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0004_portada_contacto_categoria"),
    ]

    operations = [
        migrations.RunPython(resetear, revertir),
    ]
