# Generated by Django 5.1.15 on 2026-07-09 21:49
"""
La migración 0005 usó .filter().update() para SeccionCatalogo, lo cual NO
dispara auto_now en actualizado_en (comportamiento documentado de Django:
QuerySet.update() no pasa por Model.save()). El caché del PDF (24h) se
invalida con un hash de actualizado_en de 5 tablas — si ese campo no se
mueve, el hash puede no reflejar el cambio real de contenido.

Esta migración "toca" cada SeccionCatalogo con un save() real (no
update()) para forzar un actualizado_en fresco y garantizar que el
próximo /catalogo.pdf regenere en vez de servir una copia cacheada.
No cambia ningún dato, solo el timestamp.
"""
from django.db import migrations


def tocar_secciones(apps, schema_editor):
    SeccionCatalogo = apps.get_model('catalogo', 'SeccionCatalogo')
    for seccion in SeccionCatalogo.objects.all():
        seccion.save()


def revertir(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0005_resetear_contenido_igual_original"),
    ]

    operations = [
        migrations.RunPython(tocar_secciones, revertir),
    ]
