# Generated by Django 5.1.15 on 2026-07-10 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0006_forzar_actualizacion_cache_pdf"),
    ]

    operations = [
        migrations.CreateModel(
            name="EstadisticaQuienesSomos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor",
                    models.CharField(
                        help_text="Ej: +50, 365, 100%, 20 min", max_length=20
                    ),
                ),
                (
                    "etiqueta",
                    models.CharField(help_text="Ej: EVENTOS REALIZADOS", max_length=60),
                ),
                ("orden", models.PositiveIntegerField(default=0)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Estadística",
                "verbose_name_plural": "Quiénes Somos — Estadísticas",
                "ordering": ["orden"],
            },
        ),
        migrations.CreateModel(
            name="PasoProceso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(help_text="Ej: 01, 02, 03", max_length=4)),
                ("titulo", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True)),
                ("orden", models.PositiveIntegerField(default=0)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Paso del proceso",
                "verbose_name_plural": "Quiénes Somos — Cómo Funciona (pasos)",
                "ordering": ["orden"],
            },
        ),
        migrations.CreateModel(
            name="QuienesSomos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activa",
                    models.BooleanField(
                        default=True,
                        help_text="Desactiva para ocultar esta página del PDF.",
                    ),
                ),
                ("eyebrow", models.CharField(default="Quiénes somos", max_length=60)),
                (
                    "titulo",
                    models.CharField(default="Una familia con amor", max_length=150),
                ),
                (
                    "titulo_enfasis",
                    models.CharField(
                        default="por los grandes momentos", max_length=150
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
                ("eyebrow_proceso", models.CharField(default="Proceso", max_length=60)),
                ("titulo_proceso", models.CharField(default="Cómo", max_length=100)),
                (
                    "titulo_proceso_enfasis",
                    models.CharField(default="funciona", max_length=100),
                ),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Quiénes Somos",
                "verbose_name_plural": "Quiénes Somos",
            },
        ),
        migrations.AddField(
            model_name="badgeservicio",
            name="actualizado_en",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="seccioncatalogo",
            name="descripcion_cover",
            field=models.TextField(
                blank=True,
                help_text="Texto corto de la portada de capítulo (distinto al de la página de detalle).",
                verbose_name="Descripción (portada de capítulo)",
            ),
        ),
        migrations.AddField(
            model_name="seccioncatalogo",
            name="imagen_cover",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="catalogo/secciones_cover/",
                verbose_name="Imagen de portada de capítulo",
            ),
        ),
        migrations.AddField(
            model_name="seccioncatalogo",
            name="nombre_corto",
            field=models.CharField(
                blank=True,
                help_text="Título grande de la portada de capítulo, ej: 'Eventos'. Si se deja vacío, no se genera portada de capítulo para esta sección.",
                max_length=40,
                verbose_name="Nombre corto (portada de capítulo)",
            ),
        ),
        migrations.CreateModel(
            name="GaleriaSeccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "eyebrow",
                    models.CharField(
                        help_text="Ej: Ambientación, Instalaciones", max_length=60
                    ),
                ),
                (
                    "titulo",
                    models.CharField(help_text="Ej: Cada detalle,", max_length=100),
                ),
                (
                    "titulo_enfasis",
                    models.CharField(
                        blank=True, help_text="Ej: pensado para ti", max_length=100
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "seccion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="galeria",
                        to="catalogo.seccioncatalogo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Galería de sección",
                "verbose_name_plural": "Galerías de sección",
            },
        ),
        migrations.CreateModel(
            name="GaleriaSeccionBullet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.CharField(max_length=200)),
                ("orden", models.PositiveIntegerField(default=0)),
                (
                    "galeria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bullets",
                        to="catalogo.galeriaseccion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bullet de galería",
                "verbose_name_plural": "Bullets de galería",
                "ordering": ["orden"],
            },
        ),
        migrations.CreateModel(
            name="GaleriaSeccionFoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(
                        blank=True, null=True, upload_to="catalogo/galerias/"
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0)),
                (
                    "galeria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fotos",
                        to="catalogo.galeriaseccion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Foto de galería",
                "verbose_name_plural": "Fotos de galería",
                "ordering": ["orden"],
            },
        ),
        migrations.CreateModel(
            name="OcasionCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icono",
                    models.CharField(
                        blank=True, help_text="Emoji, ej: 💍", max_length=10
                    ),
                ),
                ("titulo", models.CharField(max_length=60)),
                ("descripcion", models.TextField(blank=True)),
                ("orden", models.PositiveIntegerField(default=0)),
                (
                    "seccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocasiones",
                        to="catalogo.seccioncatalogo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarjeta de ocasión",
                "verbose_name_plural": "Tarjetas de ocasión ('Para cada ocasión')",
                "ordering": ["orden"],
            },
        ),
        migrations.CreateModel(
            name="SeccionBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.CharField(max_length=40)),
                ("orden", models.PositiveIntegerField(default=0)),
                (
                    "seccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badges_cover",
                        to="catalogo.seccioncatalogo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Badge de portada de capítulo",
                "verbose_name_plural": "Badges de portada de capítulo",
                "ordering": ["orden"],
            },
        ),
    ]
