# Generated by Django 5.1.15 on 2026-07-10 00:11
"""
Carga el contenido de las páginas que faltaban por completo tras comparar
página por página contra Catalogo_QKT_v17.pdf (16 páginas):

- Página 2: "Quiénes somos" + "Cómo funciona" (nueva, no existía ningún
  modelo para esto).
- Portada de capítulo por sección (páginas 3, 7, 10, 13 del original):
  cada una de las 4 secciones numeradas tiene su propia página oscura
  tipo "portada" ANTES de la página de detalle blanca — esto no se
  reproducía en absoluto, solo se generaba la página de detalle.
- Página 5: "Para cada ocasión" (6 tarjetas con ícono, dentro de Eventos).
- Página 6: "Ambientación" (dentro de Eventos) y página 9: "Instalaciones"
  (dentro de Pasadía) — ambas como su propia página de galería.
- Reordena "Servicios adicionales" para que quede entre Hospedaje y
  Mobiliario (antes quedaba después de Mobiliario, orden equivocado).
- Quita las 4 características de "Instalaciones" que se habían fusionado
  a la lista principal de Pasadía en la migración 0003 — ahora viven en
  su propia página de galería (GaleriaSeccion), como en el original.

Idempotente (update_or_create). No requiere correr ningún comando manual.
"""
from django.db import migrations


def cargar(apps, schema_editor):
    QuienesSomos = apps.get_model('catalogo', 'QuienesSomos')
    EstadisticaQuienesSomos = apps.get_model('catalogo', 'EstadisticaQuienesSomos')
    PasoProceso = apps.get_model('catalogo', 'PasoProceso')
    SeccionCatalogo = apps.get_model('catalogo', 'SeccionCatalogo')
    SeccionBadge = apps.get_model('catalogo', 'SeccionBadge')
    OcasionCard = apps.get_model('catalogo', 'OcasionCard')
    GaleriaSeccion = apps.get_model('catalogo', 'GaleriaSeccion')
    GaleriaSeccionBullet = apps.get_model('catalogo', 'GaleriaSeccionBullet')
    CaracteristicaSeccion = apps.get_model('catalogo', 'CaracteristicaSeccion')

    # ── Quiénes somos + Cómo funciona ─────────────────────────────────────
    qs, _ = QuienesSomos.objects.get_or_create(pk=1)
    qs.activa = True
    qs.eyebrow = 'Quiénes somos'
    qs.titulo = 'Una familia con amor'
    qs.titulo_enfasis = 'por los grandes momentos'
    qs.descripcion = (
        'Quinta Ko\'ox Tanil es un proyecto familiar nacido de la convicción de '
        'que la vida merece celebrarse. Nuestro nombre, en maya "verde corazón '
        'de la tierra", refleja nuestra conexión con la naturaleza yucateca. '
        'Trabajamos para que cada detalle esté pensado y cree experiencias que '
        'permanezcan en la memoria.'
    )
    qs.eyebrow_proceso = 'Proceso'
    qs.titulo_proceso = 'Cómo'
    qs.titulo_proceso_enfasis = 'funciona'
    qs.save()

    EstadisticaQuienesSomos.objects.all().delete()
    for i, (valor, etiqueta) in enumerate([
        ('+50', 'Eventos realizados'),
        ('365', 'Días al año'),
        ('100%', 'Familia QKT'),
        ('20 min', 'De Mérida'),
    ]):
        EstadisticaQuienesSomos.objects.create(valor=valor, etiqueta=etiqueta, orden=i)

    PasoProceso.objects.all().delete()
    for i, (numero, titulo, desc) in enumerate([
        ('01', 'Cotiza en línea',
         'Formulario corto, cotización al instante en quintakooxtanil.com/cotizar'),
        ('02', 'Recibe tu portal',
         'Acceso privado con tu cotización, plan de pagos y contrato en un solo lugar.'),
        ('03', 'Confirma tu fecha',
         'Aparta con tu anticipo y te acompañamos hasta el día de tu evento.'),
    ]):
        PasoProceso.objects.create(numero=numero, titulo=titulo, descripcion=desc, orden=i)

    # ── Portadas de capítulo + reordenamiento ─────────────────────────────
    COVERS = {
        'eventos': dict(
            nombre_corto='Eventos',
            descripcion_cover=(
                'El jardín, los árboles centenarios y los arcos coloniales de la '
                'Quinta como escenario de tu celebración.'
            ),
        ),
        'pasadia': dict(
            nombre_corto='Pasadía',
            descripcion_cover=(
                'Alberca privada, jardín con palmeras, área de juegos y las '
                'instalaciones completas de la Quinta. La escapada perfecta para '
                'grupos de hasta 20 personas.'
            ),
        ),
        'hospedaje': dict(
            nombre_corto='Hospedaje',
            descripcion_cover=(
                'Dos habitaciones únicas disponibles en Airbnb, rodeadas de '
                'naturaleza yucateca y a 20 minutos de Mérida.'
            ),
        ),
        'mobiliario': dict(
            nombre_corto='Mobiliario',
            descripcion_cover=(
                'Mesas, sillas y montaje de mesa para crear el ambiente que '
                'imaginas. Un set completo por cada 10 invitados.'
            ),
        ),
    }
    for slug, datos in COVERS.items():
        seccion = SeccionCatalogo.objects.filter(slug=slug).first()
        if not seccion:
            continue
        seccion.nombre_corto = datos['nombre_corto']
        seccion.descripcion_cover = datos['descripcion_cover']
        seccion.save()

    # Reordena: Eventos(1) Pasadía(2) Hospedaje(3) ServiciosAdicionales(4)
    # Mobiliario(5) — en el original, "Servicios adicionales" va justo
    # después de Hospedaje, antes de Mobiliario.
    mobiliario = SeccionCatalogo.objects.filter(slug='mobiliario').first()
    if mobiliario:
        mobiliario.orden = 5
        mobiliario.save()
    adicionales = SeccionCatalogo.objects.filter(slug='servicios-adicionales').first()
    if adicionales:
        adicionales.orden = 4
        adicionales.save()

    # Badges de la portada de capítulo de Eventos (7 sub-ocasiones).
    eventos = SeccionCatalogo.objects.filter(slug='eventos').first()
    if eventos:
        SeccionBadge.objects.filter(seccion=eventos).delete()
        for i, texto in enumerate([
            'Bodas', 'XV Años', 'Graduaciones', 'Cumpleaños',
            'Bautizos', 'Aniversarios', 'Corporativos',
        ]):
            SeccionBadge.objects.create(seccion=eventos, texto=texto.upper(), orden=i)

        # "Para cada ocasión" (6 tarjetas con ícono).
        OcasionCard.objects.filter(seccion=eventos).delete()
        # Nota: se usan símbolos Unicode simples (no emoji a color) — el
        # motor de PDF (WeasyPrint) no renderiza emoji a color de forma
        # confiable en el servidor, solo símbolos estándar.
        for i, (icono, titulo, desc) in enumerate([
            ('⚭', 'Bodas',
             'El día más importante merece el escenario perfecto. Atención '
             'personalizada desde la primera consulta.'),
            ('⚜', 'XV Años',
             'Elegancia y naturaleza para la celebración más especial de tu '
             'quinceañera.'),
            ('★', 'Graduaciones',
             'El inicio de una nueva etapa, celebrado como merece, con ambiente '
             'y diversión.'),
            ('✦', 'Cumpleaños',
             'Desde fiestas íntimas hasta grandes celebraciones. La Quinta se '
             'adapta a tu visión.'),
            ('♦', 'Corporativos',
             'Cenas de fin de año, convenciones y reuniones de equipo en un '
             'entorno natural único.'),
            ('♡', 'Bautizos y más',
             'Primeras comuniones, aniversarios, reuniones familiares. Todo '
             'motivo es bueno para celebrar.'),
        ]):
            OcasionCard.objects.create(
                seccion=eventos, icono=icono, titulo=titulo, descripcion=desc, orden=i
            )

        # "Ambientación" (galería, sin bullets, 2 fotos pendientes).
        galeria_eventos, _ = GaleriaSeccion.objects.update_or_create(
            seccion=eventos,
            defaults=dict(
                eyebrow='Ambientación',
                titulo='Cada detalle,',
                titulo_enfasis='pensado para ti',
                descripcion=(
                    'Nuestro espacio es el lienzo. Tú y tus proveedores de '
                    'confianza traen la decoración que imaginas: arcos de globos, '
                    'mamparas, flores, fuegos artificiales o lo que sueñes. La '
                    'Quinta se convierte en lo que quieres que sea.'
                ),
            ),
        )

    # "Instalaciones" (galería de Pasadía, con 4 bullets + 3 fotos pendientes).
    pasadia = SeccionCatalogo.objects.filter(slug='pasadia').first()
    if pasadia:
        galeria_pasadia, _ = GaleriaSeccion.objects.update_or_create(
            seccion=pasadia,
            defaults=dict(
                eyebrow='Instalaciones',
                titulo='Diversión para',
                titulo_enfasis='toda la familia',
                descripcion=(
                    'El corredor colonial con vista a la alberca, el amplio patio '
                    'para actividades al aire libre y el área de juegos infantiles '
                    'hacen de la pasadía la escapada perfecta para grupos '
                    'familiares.'
                ),
            ),
        )
        GaleriaSeccionBullet.objects.filter(galeria=galeria_pasadia).delete()
        for i, texto in enumerate([
            'Corredor colonial techado con vista al jardín y alberca',
            'Patio amplio para actividades al aire libre',
            'Área de foam y juegos para los más pequeños',
            'Ambiente familiar, privado y tranquilo',
        ]):
            GaleriaSeccionBullet.objects.create(galeria=galeria_pasadia, texto=texto, orden=i)

        # Estas 4 características se habían fusionado (por error, en 0003) a
        # la lista principal de Pasadía — ahora viven en su propia galería
        # (arriba), así que se quitan de aquí para no duplicarlas.
        CaracteristicaSeccion.objects.filter(
            seccion=pasadia,
            texto__in=[
                'Corredor colonial techado con vista al jardín y alberca',
                'Área de foam y juegos para los más pequeños',
                'Patio amplio para actividades al aire libre',
                'Ambiente familiar, privado y tranquilo',
            ],
        ).delete()


def revertir(apps, schema_editor):
    # Contenido editorial, no auditoría: no se revierte automáticamente.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0007_paginas_completas_v17"),
    ]

    operations = [
        migrations.RunPython(cargar, revertir),
    ]
