# Generated by Django 5.1.15 on 2026-07-10 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0008_paginas_faltantes_contenido"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="estadisticaquienessomos",
            options={
                "ordering": ["orden"],
                "verbose_name": "Estadística",
                "verbose_name_plural": "Estadísticas",
            },
        ),
        migrations.AlterModelOptions(
            name="pasoproceso",
            options={
                "ordering": ["orden"],
                "verbose_name": "Paso del proceso",
                "verbose_name_plural": "Cómo Funciona (pasos)",
            },
        ),
    ]
