# Generated by Django 5.1.15 on 2026-07-10 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0009_alter_estadisticaquienessomos_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="configuracioncatalogo",
            options={
                "verbose_name": "Configuración",
                "verbose_name_plural": "Configuración",
            },
        ),
        migrations.AlterModelOptions(
            name="seccioncatalogo",
            options={
                "ordering": ["orden"],
                "verbose_name": "Sección",
                "verbose_name_plural": "Secciones",
            },
        ),
        migrations.AlterModelOptions(
            name="tarjetacatalogo",
            options={
                "ordering": ["orden"],
                "verbose_name": "Tarjeta",
                "verbose_name_plural": "Tarjetas",
            },
        ),
    ]
