# Generated by Django 6.0.7 on 2026-08-02 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("legal", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="aceptacionlegal",
            new_name="legal_acept_cliente_a23851_idx",
            old_name="legal_acept_cli_fec_idx",
        ),
        migrations.RenameIndex(
            model_name="aceptacionlegal",
            new_name="legal_acept_correo_f1798b_idx",
            old_name="legal_acept_cor_fec_idx",
        ),
        migrations.RenameIndex(
            model_name="documentolegal",
            new_name="legal_docum_tipo_1f4ac6_idx",
            old_name="legal_docum_tipo_vig_idx",
        ),
        migrations.RenameIndex(
            model_name="solicitudarco",
            new_name="legal_solic_estado_172611_idx",
            old_name="legal_solic_est_lim_idx",
        ),
    ]
