# Generated by Django 6.1 on 2026-08-09 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0002_rename_legal_acept_cli_fec_idx_legal_acept_cliente_a23851_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudarco',
            options={'ordering': ['-recibida_en'], 'permissions': [('ver_identificacion_arco', 'Puede ver la identificación de solicitudes ARCO')], 'verbose_name': 'Solicitud ARCO', 'verbose_name_plural': 'Solicitudes ARCO'},
        ),
        migrations.CreateModel(
            name='AccesoIdentificacionARCO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos_identificacion', to='legal.solicitudarco')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accesos_identificacion_arco', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acceso a identificación ARCO',
                'verbose_name_plural': 'Accesos a identificaciones ARCO',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['solicitud', '-fecha'], name='legal_acces_solicit_b6e604_idx')],
            },
        ),
    ]
