# Generated by Django 6.1 on 2026-08-12 03:19

import core_erp.storages_qkt
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legal", "0003_alter_solicitudarco_options_accesoidentificacionarco"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solicitudarco",
            name="identificacion",
            field=models.FileField(
                blank=True,
                storage=core_erp.storages_qkt.storage_privado,
                upload_to="arco/identificaciones/",
            ),
        ),
    ]
