# Generated by Django 6.1 on 2026-09-26 00:03

import core_erp.storages_qkt
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legal", "0004_alter_solicitudarco_identificacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesoidentificacionarco",
            name="ip",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="IP"
            ),
        ),
        migrations.AlterField(
            model_name="aceptacionlegal",
            name="ip",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="IP"
            ),
        ),
        migrations.AlterField(
            model_name="aceptacionlegal",
            name="snapshot_documentos",
            field=models.JSONField(
                default=list,
                help_text="[{'tipo':..., 'version':..., 'hash':...}] congelado al aceptar.",
                verbose_name="Copia de los documentos aceptados",
            ),
        ),
        migrations.AlterField(
            model_name="aceptacionlegal",
            name="user_agent",
            field=models.TextField(blank=True, verbose_name="Navegador (user agent)"),
        ),
        migrations.AlterField(
            model_name="documentolegal",
            name="contenido_md",
            field=models.TextField(
                help_text="Contenido en Markdown. Inmutable una vez guardado.",
                verbose_name="Contenido (Markdown)",
            ),
        ),
        migrations.AlterField(
            model_name="documentolegal",
            name="hash_contenido",
            field=models.CharField(
                db_index=True,
                editable=False,
                max_length=64,
                verbose_name="Hash del contenido",
            ),
        ),
        migrations.AlterField(
            model_name="documentolegal",
            name="titulo",
            field=models.CharField(max_length=200, verbose_name="Título"),
        ),
        migrations.AlterField(
            model_name="documentolegal",
            name="version",
            field=models.CharField(
                help_text="Ej. '2.0'", max_length=16, verbose_name="Versión"
            ),
        ),
        migrations.AlterField(
            model_name="finalidad",
            name="descripcion",
            field=models.TextField(blank=True, verbose_name="Descripción"),
        ),
        migrations.AlterField(
            model_name="solicitudarco",
            name="descripcion",
            field=models.TextField(verbose_name="Descripción"),
        ),
        migrations.AlterField(
            model_name="solicitudarco",
            name="fecha_limite",
            field=models.DateField(editable=False, verbose_name="Fecha límite"),
        ),
        migrations.AlterField(
            model_name="solicitudarco",
            name="identificacion",
            field=models.FileField(
                blank=True,
                storage=core_erp.storages_qkt.storage_privado,
                upload_to="arco/identificaciones/",
                verbose_name="Identificación",
            ),
        ),
        migrations.AlterField(
            model_name="solicitudarco",
            name="telefono",
            field=models.CharField(blank=True, max_length=20, verbose_name="Teléfono"),
        ),
    ]
