# Generated by Django 6.1 on 2026-08-17 22:44

import core_erp.storages_qkt
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legal", "0004_alter_solicitudarco_identificacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solicitudarco",
            name="identificacion",
            field=models.FileField(
                blank=True,
                storage=core_erp.storages_qkt.storage_privado,
                upload_to="arco/identificaciones/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
    ]
