# Generated by Django 6.1 on 2026-09-28 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("legal", "0005_alter_accesoidentificacionarco_ip_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aceptacionlegal",
            options={
                "ordering": ["-aceptado_en"],
                "verbose_name": "Aceptación legal",
                "verbose_name_plural": "Aceptaciones",
            },
        ),
        migrations.AlterModelOptions(
            name="documentolegal",
            options={
                "ordering": ["tipo", "-vigente_desde"],
                "verbose_name": "Documento legal",
                "verbose_name_plural": "Documentos",
            },
        ),
        migrations.AlterModelOptions(
            name="finalidad",
            options={
                "ordering": ["orden", "clave"],
                "verbose_name": "Finalidad del tratamiento",
                "verbose_name_plural": "Finalidades",
            },
        ),
        migrations.AlterModelOptions(
            name="solicitudarco",
            options={
                "ordering": ["-recibida_en"],
                "permissions": [
                    (
                        "ver_identificacion_arco",
                        "Puede ver la identificación de solicitudes ARCO",
                    )
                ],
                "verbose_name": "Solicitud ARCO",
                "verbose_name_plural": "ARCO",
            },
        ),
    ]
