# Generated by Django 6.1 on 2026-10-07 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legal", "0006_nombres_cortos_menu"),
    ]

    operations = [
        migrations.AddField(
            model_name="aceptacionlegal",
            name="referencia_externa",
            field=models.CharField(
                blank=True,
                help_text="ID del mensaje de WhatsApp con el que aceptó (origen WhatsApp).",
                max_length=191,
                verbose_name="Referencia externa",
            ),
        ),
        migrations.AlterField(
            model_name="aceptacionlegal",
            name="origen",
            field=models.CharField(
                choices=[
                    ("FORM_COTIZACION", "Formulario público de cotización"),
                    ("PORTAL_CLIENTE", "Portal de clientes"),
                    ("CHECKOUT", "Checkout de pago"),
                    ("CONTRATO", "Firma de contrato"),
                    ("ADMIN", "Captura administrativa"),
                    ("WHATSAPP", "Botón en el chat de WhatsApp"),
                ],
                max_length=24,
            ),
        ),
    ]
