# Generated by Django 6.0.1 on 2026-01-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='puesto',
            field=models.CharField(choices=[('MESERO', 'Mesero'), ('COCINA', 'Cocina/Chef'), ('STAFF', 'Staff General'), ('CHOFER', 'Chofer'), ('SEGURIDAD', 'Seguridad'), ('OTRO', 'Otro')], default='MESERO', max_length=20),
        ),
        migrations.AddField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(help_text='Debe coincidir con el nombre en el Excel si usas carga masiva', max_length=200),
        ),
    ]
