# Generated by Django 5.1.15 on 2026-07-10 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nomina", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recibonomina",
            options={"verbose_name": "Recibo", "verbose_name_plural": "Recibos"},
        ),
    ]
