# Generated by Django 5.1.15 on 2026-07-13 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nomina", "0002_alter_recibonomina_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="recibonomina",
            name="estado",
            field=models.CharField(
                choices=[
                    ("CALCULADO", "Calculado (sin pagar)"),
                    ("PAGADO", "Pagado en efectivo"),
                    ("CANCELADO", "Cancelado"),
                ],
                default="CALCULADO",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="recibonomina",
            name="fecha_pago",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de pago en efectivo"
            ),
        ),
        migrations.AddField(
            model_name="recibonomina",
            name="pagado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nominas_pagadas_por",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Pagado por",
            ),
        ),
        migrations.AlterField(
            model_name="recibonomina",
            name="total_pagado",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Total a pagar"
            ),
        ),
    ]
