# Generated by Django 6.1 on 2026-08-12 03:19

import core_erp.storages_qkt
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nomina", "0003_recibonomina_estado_recibonomina_fecha_pago_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recibonomina",
            name="archivo_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                storage=core_erp.storages_qkt.storage_privado,
                upload_to="nominas_pdf/",
            ),
        ),
    ]
