# Generated by Django 6.1 on 2026-09-26 00:03

import core_erp.storages_qkt
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nomina", "0004_alter_recibonomina_archivo_pdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empleado",
            name="telefono",
            field=models.CharField(blank=True, max_length=20, verbose_name="Teléfono"),
        ),
        migrations.AlterField(
            model_name="recibonomina",
            name="archivo_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                storage=core_erp.storages_qkt.storage_privado,
                upload_to="nominas_pdf/",
                verbose_name="Archivo PDF",
            ),
        ),
        migrations.AlterField(
            model_name="recibonomina",
            name="fecha_generacion",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de generación"
            ),
        ),
    ]
