# Generated by Django 6.1 on 2026-08-17 22:44

import core_erp.storages_qkt
import core_erp.validadores_archivos
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nomina", "0004_alter_recibonomina_archivo_pdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recibonomina",
            name="archivo_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                storage=core_erp.storages_qkt.storage_privado,
                upload_to="nominas_pdf/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    ),
                    core_erp.validadores_archivos.validar_firma_pdf,
                ],
            ),
        ),
    ]
