# Generated by Django 5.2.12 on 2026-04-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoriaGasto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "clave",
                    models.CharField(
                        help_text="Identificador corto (ej: LIMPIEZA, BEBIDAS_CON_ALCOHOL)",
                        max_length=30,
                        unique=True,
                        verbose_name="Clave",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre visible en dropdowns y reportes",
                        max_length=100,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "activa",
                    models.BooleanField(
                        default=True,
                        help_text="Las categorías inactivas no aparecen en el dropdown pero se conservan en gastos históricos",
                        verbose_name="Activa",
                    ),
                ),
                (
                    "orden",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Menor número = aparece primero en la lista",
                        verbose_name="Orden",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría de Gasto",
                "verbose_name_plural": "Categorías de Gasto",
                "ordering": ["orden", "nombre"],
            },
        ),
    ]
