# Generated by Django 6.0.1 on 2026-01-19 22:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comercial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(default=django.utils.timezone.now)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('concepto', models.TextField()),
                ('forma_pago', models.CharField(choices=[('03 - Transferencia electrónica de fondos', '03 - Transferencia'), ('01 - Efectivo', '01 - Efectivo'), ('04 - Tarjeta de crédito', '04 - Tarjeta de crédito'), ('28 - Tarjeta de débito', '28 - Tarjeta de débito'), ('99 - Por definir', '99 - Por definir')], max_length=100)),
                ('metodo_pago', models.CharField(choices=[('PUE - Pago en una sola exhibición', 'PUE - Una sola exhibición'), ('PPD - Pago en parcialidades o diferido', 'PPD - Parcialidades')], max_length=100)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='solicitudes_pdf/')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.cliente', verbose_name='Cliente')),
                ('cotizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_factura', to='comercial.cotizacion', verbose_name='Cotización Origen')),
            ],
        ),
    ]
