# Generated by Django 6.0.1 on 2026-01-18 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0001_initial'),
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudfactura',
            name='cotizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_factura', to='comercial.cotizacion', verbose_name='Cotización Origen'),
        ),
    ]
