# Generated by Django 6.0.1 on 2026-01-21 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudfactura',
            name='forma_pago',
            field=models.CharField(choices=[('01', '01 - Efectivo'), ('02', '02 - Cheque nominativo'), ('03', '03 - Transferencia electrónica de fondos'), ('04', '04 - Tarjeta de crédito'), ('05', '05 - Monedero electrónico'), ('08', '08 - Vales de despensa'), ('12', '12 - Dación en pago'), ('28', '28 - Tarjeta de débito'), ('99', '99 - Por definir')], default='03', max_length=2, verbose_name='Forma de Pago'),
        ),
        migrations.AlterField(
            model_name='solicitudfactura',
            name='metodo_pago',
            field=models.CharField(choices=[('PUE', 'PUE - Pago en una sola exhibición'), ('PPD', 'PPD - Pago en parcialidades o diferido')], default='PUE', max_length=3, verbose_name='Método de Pago'),
        ),
    ]
