# Generated by Django 5.2.12 on 2026-04-09 23:20

import cloudinary_storage.storage
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "contabilidad",
            "0007_rename_contabilida_codigo__a1b2c3_idx_contabilida_codigo__b58027_idx_and_more",
        ),
        ("facturacion", "0003_add_desglose_fiscal"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmisorFiscal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_interno",
                    models.CharField(
                        help_text="Nombre corto para distinguir en el admin (ej: 'Eventos Elian')",
                        max_length=100,
                        unique=True,
                        verbose_name="Nombre interno",
                    ),
                ),
                (
                    "rfc",
                    models.CharField(max_length=13, unique=True, verbose_name="RFC"),
                ),
                (
                    "razon_social",
                    models.CharField(
                        help_text="Como aparece en la Constancia de Situación Fiscal",
                        max_length=300,
                        verbose_name="Razón Social",
                    ),
                ),
                (
                    "regimen_fiscal",
                    models.CharField(
                        choices=[
                            ("601", "601 - General de Ley Personas Morales"),
                            ("603", "603 - Personas Morales con Fines no Lucrativos"),
                            ("623", "623 - Opcional para Grupos de Sociedades"),
                            ("624", "624 - Coordinados"),
                            ("626", "626 - Régimen Simplificado de Confianza (RESICO)"),
                            (
                                "605",
                                "605 - Sueldos y Salarios e Ingresos Asimilados a Salarios",
                            ),
                            ("606", "606 - Arrendamiento"),
                            (
                                "607",
                                "607 - Régimen de Enajenación o Adquisición de Bienes",
                            ),
                            ("608", "608 - Demás ingresos"),
                            (
                                "610",
                                "610 - Residentes en el Extranjero sin Establecimiento Permanente en México",
                            ),
                            (
                                "611",
                                "611 - Ingresos por Dividendos (socios y accionistas)",
                            ),
                            (
                                "612",
                                "612 - Personas Físicas con Actividades Empresariales y Profesionales",
                            ),
                            ("614", "614 - Ingresos por intereses"),
                            (
                                "615",
                                "615 - Régimen de los ingresos por obtención de premios",
                            ),
                            ("616", "616 - Sin obligaciones fiscales"),
                            ("620", "620 - Sociedades Cooperativas de Producción"),
                            ("621", "621 - Incorporación Fiscal (RIF)"),
                            (
                                "622",
                                "622 - Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras",
                            ),
                            ("625", "625 - Plataformas Tecnológicas"),
                        ],
                        max_length=3,
                        verbose_name="Régimen Fiscal",
                    ),
                ),
                (
                    "codigo_postal",
                    models.CharField(max_length=5, verbose_name="C.P. Fiscal"),
                ),
                (
                    "serie_folio",
                    models.CharField(
                        default="A",
                        help_text="Serie que se usará al emitir CFDIs (ej: A, WEB, EVT)",
                        max_length=10,
                        verbose_name="Serie de folio",
                    ),
                ),
                (
                    "lugar_expedicion",
                    models.CharField(
                        blank=True,
                        help_text="CP del lugar de expedición. Si se deja vacío se usa el CP fiscal.",
                        max_length=5,
                        verbose_name="Lugar de expedición",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Solo los emisores activos pueden emitir CFDIs",
                        verbose_name="Activo",
                    ),
                ),
                ("notas", models.TextField(blank=True, verbose_name="Notas internas")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Emisor Fiscal",
                "verbose_name_plural": "Emisores Fiscales",
                "ordering": ["nombre_interno"],
            },
        ),
        migrations.AlterModelOptions(
            name="solicitudfactura",
            options={
                "ordering": ["-fecha_solicitud"],
                "verbose_name": "Solicitud de Factura",
                "verbose_name_plural": "Solicitudes de Factura",
            },
        ),
        migrations.RenameIndex(
            model_name="solicitudfactura",
            new_name="facturacion_estado_5293c7_idx",
            old_name="facturacion_estado_fecha_idx",
        ),
        migrations.RenameIndex(
            model_name="solicitudfactura",
            new_name="facturacion_cliente_4f70e2_idx",
            old_name="facturacion_cliente_fecha_idx",
        ),
        migrations.AlterField(
            model_name="solicitudfactura",
            name="archivo_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                upload_to="facturas_pdf/",
                verbose_name="Factura PDF",
            ),
        ),
        migrations.AlterField(
            model_name="solicitudfactura",
            name="archivo_xml",
            field=models.FileField(
                blank=True,
                null=True,
                storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                upload_to="facturas_xml/",
                verbose_name="Factura XML",
            ),
        ),
        migrations.AlterField(
            model_name="solicitudfactura",
            name="archivo_zip",
            field=models.FileField(
                blank=True,
                help_text="Archivo ZIP con la factura (PDF + XML)",
                null=True,
                storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                upload_to="facturas_zip/",
                verbose_name="ZIP con PDF y XML",
            ),
        ),
        migrations.AlterField(
            model_name="solicitudfactura",
            name="concepto",
            field=models.TextField(verbose_name="Concepto / Descripción"),
        ),
        migrations.AlterField(
            model_name="solicitudfactura",
            name="fecha_solicitud",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Fecha de Solicitud"
            ),
        ),
        migrations.AlterField(
            model_name="solicitudfactura",
            name="monto",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Monto a Facturar"
            ),
        ),
        migrations.AlterField(
            model_name="solicitudfactura",
            name="regimen_fiscal",
            field=models.CharField(
                choices=[
                    ("601", "601 - General de Ley Personas Morales"),
                    ("603", "603 - Personas Morales con Fines no Lucrativos"),
                    ("623", "623 - Opcional para Grupos de Sociedades"),
                    ("624", "624 - Coordinados"),
                    ("626", "626 - Régimen Simplificado de Confianza (RESICO)"),
                    (
                        "605",
                        "605 - Sueldos y Salarios e Ingresos Asimilados a Salarios",
                    ),
                    ("606", "606 - Arrendamiento"),
                    ("607", "607 - Régimen de Enajenación o Adquisición de Bienes"),
                    ("608", "608 - Demás ingresos"),
                    (
                        "610",
                        "610 - Residentes en el Extranjero sin Establecimiento Permanente en México",
                    ),
                    ("611", "611 - Ingresos por Dividendos (socios y accionistas)"),
                    (
                        "612",
                        "612 - Personas Físicas con Actividades Empresariales y Profesionales",
                    ),
                    ("614", "614 - Ingresos por intereses"),
                    ("615", "615 - Régimen de los ingresos por obtención de premios"),
                    ("616", "616 - Sin obligaciones fiscales"),
                    ("620", "620 - Sociedades Cooperativas de Producción"),
                    ("621", "621 - Incorporación Fiscal (RIF)"),
                    (
                        "622",
                        "622 - Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras",
                    ),
                    ("625", "625 - Plataformas Tecnológicas"),
                ],
                max_length=3,
                verbose_name="Régimen Fiscal",
            ),
        ),
        migrations.AlterField(
            model_name="solicitudfactura",
            name="uso_cfdi",
            field=models.CharField(
                choices=[
                    ("G01", "G01 - Adquisición de mercancías"),
                    ("G02", "G02 - Devoluciones, descuentos o bonificaciones"),
                    ("G03", "G03 - Gastos en general"),
                    ("I01", "I01 - Construcciones"),
                    ("I02", "I02 - Mobiliario y equipo de oficina"),
                    ("I03", "I03 - Equipo de transporte"),
                    ("I04", "I04 - Equipo de computo y accesorios"),
                    (
                        "D01",
                        "D01 - Honorarios médicos, dentales y gastos hospitalarios",
                    ),
                    ("D02", "D02 - Gastos médicos por incapacidad"),
                    ("D03", "D03 - Gastos funerales"),
                    ("D04", "D04 - Donativos"),
                    ("D05", "D05 - Intereses reales hipotecarios"),
                    ("D06", "D06 - Aportaciones voluntarias al SAR"),
                    ("D07", "D07 - Primas por seguros de gastos médicos"),
                    ("D08", "D08 - Gastos de transportación escolar obligatoria"),
                    ("D09", "D09 - Depósitos en cuentas para el ahorro"),
                    ("D10", "D10 - Pagos por servicios educativos (Colegiaturas)"),
                    ("S01", "S01 - Sin efectos fiscales"),
                    ("CP01", "CP01 - Pagos"),
                    ("CN01", "CN01 - Nómina"),
                ],
                default="G03",
                max_length=4,
                verbose_name="Uso CFDI",
            ),
        ),
        migrations.AddField(
            model_name="emisorfiscal",
            name="unidad_negocio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="emisores_fiscales",
                to="contabilidad.unidadnegocio",
                verbose_name="Unidad de negocio",
            ),
        ),
        migrations.AddField(
            model_name="solicitudfactura",
            name="emisor",
            field=models.ForeignKey(
                blank=True,
                help_text="RFC desde el que se emitirá este CFDI",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="solicitudes",
                to="facturacion.emisorfiscal",
                verbose_name="Emisor Fiscal",
            ),
        ),
    ]
