# Generated by Django 6.0.7 on 2026-08-02 23:32

import cloudinary_storage.storage
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0004_alter_solicitudfactura_regimen_fiscal"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="solicitudfactura",
            options={
                "ordering": ["-fecha_solicitud"],
                "verbose_name": "Solicitud de Factura",
                "verbose_name_plural": "Solicitudes de Factura",
            },
        ),
        migrations.RenameIndex(
            model_name="solicitudfactura",
            new_name="facturacion_estado_5293c7_idx",
            old_name="facturacion_estado_fecha_idx",
        ),
        migrations.RenameIndex(
            model_name="solicitudfactura",
            new_name="facturacion_cliente_4f70e2_idx",
            old_name="facturacion_cliente_fecha_idx",
        ),
        migrations.AlterField(
            model_name="solicitudfactura",
            name="archivo_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                upload_to="facturas_pdf/",
                verbose_name="Factura PDF",
            ),
        ),
        migrations.AlterField(
            model_name="solicitudfactura",
            name="archivo_xml",
            field=models.FileField(
                blank=True,
                null=True,
                storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                upload_to="facturas_xml/",
                verbose_name="Factura XML",
            ),
        ),
        migrations.AlterField(
            model_name="solicitudfactura",
            name="archivo_zip",
            field=models.FileField(
                blank=True,
                help_text="Archivo ZIP con la factura (PDF + XML)",
                null=True,
                storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                upload_to="facturas_zip/",
                verbose_name="ZIP con PDF y XML",
            ),
        ),
        migrations.AlterField(
            model_name="solicitudfactura",
            name="concepto",
            field=models.TextField(verbose_name="Concepto / Descripción"),
        ),
        migrations.AlterField(
            model_name="solicitudfactura",
            name="fecha_solicitud",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Fecha de Solicitud"
            ),
        ),
        migrations.AlterField(
            model_name="solicitudfactura",
            name="monto",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Monto a Facturar"
            ),
        ),
        migrations.AlterField(
            model_name="solicitudfactura",
            name="uso_cfdi",
            field=models.CharField(
                choices=[
                    ("G01", "G01 - Adquisición de mercancías"),
                    ("G02", "G02 - Devoluciones, descuentos o bonificaciones"),
                    ("G03", "G03 - Gastos en general"),
                    ("I01", "I01 - Construcciones"),
                    ("I02", "I02 - Mobiliario y equipo de oficina"),
                    ("I03", "I03 - Equipo de transporte"),
                    ("I04", "I04 - Equipo de computo y accesorios"),
                    (
                        "D01",
                        "D01 - Honorarios médicos, dentales y gastos hospitalarios",
                    ),
                    ("D02", "D02 - Gastos médicos por incapacidad"),
                    ("D03", "D03 - Gastos funerales"),
                    ("D04", "D04 - Donativos"),
                    ("D05", "D05 - Intereses reales hipotecarios"),
                    ("D06", "D06 - Aportaciones voluntarias al SAR"),
                    ("D07", "D07 - Primas por seguros de gastos médicos"),
                    ("D08", "D08 - Gastos de transportación escolar obligatoria"),
                    ("D09", "D09 - Depósitos en cuentas para el ahorro"),
                    ("D10", "D10 - Pagos por servicios educativos (Colegiaturas)"),
                    ("S01", "S01 - Sin efectos fiscales"),
                    ("CP01", "CP01 - Pagos"),
                    ("CN01", "CN01 - Nómina"),
                ],
                default="G03",
                max_length=4,
                verbose_name="Uso CFDI",
            ),
        ),
    ]
