# Generated by Django 6.0.7 on 2026-08-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0005_alter_solicitudfactura_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solicitudfactura",
            name="archivo_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="facturas_pdf/",
                verbose_name="Factura PDF",
            ),
        ),
        migrations.AlterField(
            model_name="solicitudfactura",
            name="archivo_xml",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="facturas_xml/",
                verbose_name="Factura XML",
            ),
        ),
        migrations.AlterField(
            model_name="solicitudfactura",
            name="archivo_zip",
            field=models.FileField(
                blank=True,
                help_text="Archivo ZIP con la factura (PDF + XML)",
                null=True,
                upload_to="facturas_zip/",
                verbose_name="ZIP con PDF y XML",
            ),
        ),
    ]
