# Generated by Django 6.1 on 2026-08-17 22:44

import core_erp.validadores_archivos
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0006_alter_solicitudfactura_archivo_pdf_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solicitudfactura",
            name="archivo_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="facturas_pdf/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    ),
                    core_erp.validadores_archivos.validar_firma_pdf,
                ],
                verbose_name="Factura PDF",
            ),
        ),
        migrations.AlterField(
            model_name="solicitudfactura",
            name="archivo_xml",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="facturas_xml/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["xml"]
                    ),
                    core_erp.validadores_archivos.validar_firma_xml,
                ],
                verbose_name="Factura XML",
            ),
        ),
        migrations.AlterField(
            model_name="solicitudfactura",
            name="archivo_zip",
            field=models.FileField(
                blank=True,
                help_text="Archivo ZIP con la factura (PDF + XML)",
                null=True,
                upload_to="facturas_zip/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["zip"]
                    ),
                    core_erp.validadores_archivos.validar_firma_zip,
                ],
                verbose_name="ZIP con PDF y XML",
            ),
        ),
    ]
