# Generated by Django 6.1 on 2026-08-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0006_alter_solicitudfactura_archivo_pdf_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitudfactura",
            name="ultimo_recordatorio_enviado",
            field=models.DateTimeField(
                blank=True,
                help_text="Lo escribe el cron de recordatorios al contador — no confundir con fecha_envio (el primer envío). Evita que un recordatorio se mande dos veces el mismo día si el comando se corre más de una vez.",
                null=True,
                verbose_name="Último recordatorio enviado",
            ),
        ),
    ]
