# Generated by Django 6.1 on 2026-08-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0007_solicitudfactura_ultimo_recordatorio_enviado"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitudfactura",
            name="linea_negocio",
            field=models.CharField(
                choices=[("QUINTA", "Quinta Ko'ox Tanil"), ("AIRBNB", "Airbnb")],
                default="QUINTA",
                help_text="Bajo qué RFC propio se debe timbrar: PECE010202IA0 para Quinta Ko'ox Tanil (Eventos, Pasadías y Hospedajes Directos) o CERU580518QZ5 para ingresos directos de Airbnb.",
                max_length=10,
                verbose_name="Línea de Negocio",
            ),
        ),
    ]
