# Generated by Django 6.1 on 2026-09-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0008_solicitudfactura_linea_negocio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solicitudfactura",
            name="linea_negocio",
            field=models.CharField(
                choices=[("QUINTA", "Quinta Ko'ox Tanil")],
                default="QUINTA",
                help_text="Bajo qué RFC propio se debe timbrar: PECE010202IA0 para Quinta Ko'ox Tanil (Eventos, Pasadías y Hospedaje directo).",
                max_length=10,
                verbose_name="Línea de Negocio",
            ),
        ),
    ]
