# Generated by Django 6.1 on 2026-09-25 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0009_retiro_airbnb_linea_negocio"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitudfactura",
            name="impuesto_hospedaje",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="ISH (impuesto local)",
            ),
        ),
    ]
