# Generated by Django 6.1 on 2026-09-26 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0010_solicitudfactura_impuesto_hospedaje"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuracioncontador",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
        ),
        migrations.AlterField(
            model_name="configuracioncontador",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
        ),
        migrations.AlterField(
            model_name="solicitudfactura",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
        ),
        migrations.AlterField(
            model_name="solicitudfactura",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
        ),
    ]
