# Generated by Django 6.1 on 2026-09-28 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0011_alter_configuracioncontador_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="configuracioncontador",
            options={
                "verbose_name": "Configuración del Contador",
                "verbose_name_plural": "Contador",
            },
        ),
        migrations.AlterModelOptions(
            name="solicitudfactura",
            options={
                "ordering": ["-fecha_solicitud"],
                "verbose_name": "Solicitud de Factura",
                "verbose_name_plural": "Solicitudes",
            },
        ),
    ]
