# Generated by Django 6.0.1 on 2026-03-27 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0005_cargar_configuracion_contable'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cuentacontable',
            new_name='contabilida_codigo__b58027_idx',
            old_name='contabilida_codigo__a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='cuentacontable',
            new_name='contabilida_tipo_6d3f01_idx',
            old_name='contabilida_tipo_ac_d4e5f6_idx',
        ),
        migrations.RenameIndex(
            model_name='movimientocontable',
            new_name='contabilida_cuenta__d8586a_idx',
            old_name='contabilida_cuenta__p6q7r8_idx',
        ),
        migrations.RenameIndex(
            model_name='poliza',
            new_name='contabilida_fecha_80446c_idx',
            old_name='contabilida_fecha_t_g7h8i9_idx',
        ),
        migrations.RenameIndex(
            model_name='poliza',
            new_name='contabilida_estado_2a92fe_idx',
            old_name='contabilida_estado_j0k1l2_idx',
        ),
        migrations.RenameIndex(
            model_name='poliza',
            new_name='contabilida_unidad__ae3cc3_idx',
            old_name='contabilida_unidad__m3n4o5_idx',
        ),
        migrations.AddField(
            model_name='unidadnegocio',
            name='razon_social',
            field=models.CharField(blank=True, max_length=300, verbose_name='Razón Social'),
        ),
        migrations.AddField(
            model_name='unidadnegocio',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, verbose_name='RFC'),
        ),
    ]
