# Generated by Django 5.1.15 on 2026-07-10 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contabilidad", "0006_add_rfc_razon_social_unidad"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="configuracioncontable",
            options={
                "ordering": ["operacion"],
                "verbose_name": "Configuración contable",
                "verbose_name_plural": "Configuración",
            },
        ),
        migrations.AlterModelOptions(
            name="movimientocontable",
            options={
                "ordering": ["id"],
                "verbose_name": "Movimiento contable",
                "verbose_name_plural": "Movimientos",
            },
        ),
        migrations.AlterModelOptions(
            name="poliza",
            options={
                "ordering": ["-fecha", "-folio"],
                "verbose_name": "Póliza contable",
                "verbose_name_plural": "Pólizas",
            },
        ),
    ]
