# Generated by Django 5.2.12 on 2026-04-09 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contabilidad", "0006_add_rfc_razon_social_unidad"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="cuentacontable",
            new_name="contabilida_codigo__b58027_idx",
            old_name="contabilida_codigo__a1b2c3_idx",
        ),
        migrations.RenameIndex(
            model_name="cuentacontable",
            new_name="contabilida_tipo_6d3f01_idx",
            old_name="contabilida_tipo_ac_d4e5f6_idx",
        ),
        migrations.RenameIndex(
            model_name="movimientocontable",
            new_name="contabilida_cuenta__d8586a_idx",
            old_name="contabilida_cuenta__p6q7r8_idx",
        ),
        migrations.RenameIndex(
            model_name="poliza",
            new_name="contabilida_fecha_80446c_idx",
            old_name="contabilida_fecha_t_g7h8i9_idx",
        ),
        migrations.RenameIndex(
            model_name="poliza",
            new_name="contabilida_estado_2a92fe_idx",
            old_name="contabilida_estado_j0k1l2_idx",
        ),
        migrations.RenameIndex(
            model_name="poliza",
            new_name="contabilida_unidad__ae3cc3_idx",
            old_name="contabilida_unidad__m3n4o5_idx",
        ),
        migrations.AlterField(
            model_name="configuracioncontable",
            name="operacion",
            field=models.CharField(
                choices=[
                    ("PAGO_CLIENTE_EFECTIVO", "Pago cliente - Efectivo"),
                    ("PAGO_CLIENTE_TRANSFERENCIA", "Pago cliente - Transferencia"),
                    ("PAGO_CLIENTE_TARJETA", "Pago cliente - Tarjeta"),
                    ("INGRESO_EVENTOS", "Ingreso por eventos"),
                    ("IVA_TRASLADADO", "IVA trasladado"),
                    ("ANTICIPO_CLIENTES", "Anticipo de clientes"),
                    ("ISR_RETENIDO_CLIENTES", "ISR retenido por clientes"),
                    ("INGRESO_AIRBNB", "Ingreso Airbnb"),
                    ("RETENCION_ISR_AIRBNB", "Retención ISR Airbnb"),
                    ("RETENCION_IVA_AIRBNB", "Retención IVA Airbnb"),
                    ("IMPUESTO_HOSPEDAJE", "Impuesto al hospedaje"),
                    ("COMISION_AIRBNB", "Comisión Airbnb"),
                    ("PROVEEDORES", "Proveedores"),
                    ("IVA_ACREDITABLE", "IVA acreditable"),
                    ("GASTOS_GENERALES", "Gastos generales"),
                    ("GASTO_INSUMOS", "Gastos - Insumos y bebidas"),
                    ("GASTO_SERVICIOS", "Gastos - Servicios (agua, luz, internet)"),
                    ("GASTO_MANTENIMIENTO", "Gastos - Mantenimiento y limpieza"),
                    ("GASTO_PUBLICIDAD", "Gastos - Publicidad y marketing"),
                    ("GASTO_EQUIPO", "Gastos - Equipo y mobiliario"),
                    ("GASTO_VEHICULOS", "Gastos - Vehículos y combustible"),
                    ("GASTO_OFICINA", "Gastos - Oficina y papelería"),
                    ("GASTO_IMPUESTOS", "Gastos - Impuestos y derechos"),
                    ("GASTO_SEGUROS", "Gastos - Seguros y fianzas"),
                    ("GASTO_BANCARIOS", "Gastos - Comisiones bancarias"),
                    ("GASTOS_BEBIDAS", "Gastos bebidas"),
                    ("GASTOS_NOMINA_EXT", "Gastos nómina externa"),
                    ("SUELDOS_SALARIOS", "Sueldos y salarios"),
                    ("IMSS_PATRONAL", "IMSS patronal"),
                    ("BANCO_PRINCIPAL", "Banco principal"),
                    ("BANCO_SECUNDARIO", "Banco secundario"),
                    ("CAJA", "Caja"),
                ],
                max_length=50,
                unique=True,
                verbose_name="Tipo de operación",
            ),
        ),
        migrations.AlterField(
            model_name="poliza",
            name="concepto",
            field=models.CharField(max_length=500, verbose_name="Concepto"),
        ),
        migrations.AlterField(
            model_name="unidadnegocio",
            name="razon_social",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Razón Social"
            ),
        ),
    ]
