# Generated by Django 5.1.15 on 2026-07-13 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contabilidad", "0008_cuenta_ajuste_apertura"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SaldoApertura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_corte", models.DateField(verbose_name="Fecha de corte")),
                (
                    "saldo_certificado",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Saldo real según estado de cuenta bancario a la fecha de corte.",
                        max_digits=14,
                        verbose_name="Saldo certificado",
                    ),
                ),
                ("notas", models.TextField(blank=True, verbose_name="Notas / soporte")),
                (
                    "aplicado",
                    models.BooleanField(default=False, verbose_name="Póliza generada"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Saldo de apertura",
                "verbose_name_plural": "Saldos de apertura",
                "ordering": ["-fecha_corte"],
            },
        ),
        migrations.AlterField(
            model_name="configuracioncontable",
            name="operacion",
            field=models.CharField(
                choices=[
                    ("PAGO_CLIENTE_EFECTIVO", "Pago cliente - Efectivo"),
                    ("PAGO_CLIENTE_TRANSFERENCIA", "Pago cliente - Transferencia"),
                    ("PAGO_CLIENTE_TARJETA", "Pago cliente - Tarjeta"),
                    ("INGRESO_EVENTOS", "Ingreso por eventos"),
                    ("IVA_TRASLADADO", "IVA trasladado"),
                    ("ANTICIPO_CLIENTES", "Anticipo de clientes"),
                    ("ISR_RETENIDO_CLIENTES", "ISR retenido por clientes"),
                    ("INGRESO_AIRBNB", "Ingreso Airbnb"),
                    ("RETENCION_ISR_AIRBNB", "Retención ISR Airbnb"),
                    ("RETENCION_IVA_AIRBNB", "Retención IVA Airbnb"),
                    ("IMPUESTO_HOSPEDAJE", "Impuesto al hospedaje"),
                    ("COMISION_AIRBNB", "Comisión Airbnb"),
                    ("PROVEEDORES", "Proveedores"),
                    ("IVA_ACREDITABLE", "IVA acreditable"),
                    ("GASTOS_GENERALES", "Gastos generales"),
                    ("GASTO_INSUMOS", "Gastos - Insumos y bebidas"),
                    ("GASTO_SERVICIOS", "Gastos - Servicios (agua, luz, internet)"),
                    ("GASTO_MANTENIMIENTO", "Gastos - Mantenimiento y limpieza"),
                    ("GASTO_PUBLICIDAD", "Gastos - Publicidad y marketing"),
                    ("GASTO_EQUIPO", "Gastos - Equipo y mobiliario"),
                    ("GASTO_VEHICULOS", "Gastos - Vehículos y combustible"),
                    ("GASTO_OFICINA", "Gastos - Oficina y papelería"),
                    ("GASTO_IMPUESTOS", "Gastos - Impuestos y derechos"),
                    ("GASTO_SEGUROS", "Gastos - Seguros y fianzas"),
                    ("GASTO_BANCARIOS", "Gastos - Comisiones bancarias"),
                    ("GASTOS_BEBIDAS", "Gastos bebidas"),
                    ("GASTOS_NOMINA_EXT", "Gastos nómina externa"),
                    ("SUELDOS_SALARIOS", "Sueldos y salarios"),
                    ("IMSS_PATRONAL", "IMSS patronal"),
                    ("BANCO_PRINCIPAL", "Banco principal"),
                    ("BANCO_SECUNDARIO", "Banco secundario"),
                    ("CAJA", "Caja"),
                    (
                        "AJUSTE_APERTURA",
                        "Ajuste de apertura / resultados de ejercicios anteriores",
                    ),
                ],
                max_length=50,
                unique=True,
                verbose_name="Tipo de operación",
            ),
        ),
        migrations.AlterField(
            model_name="poliza",
            name="origen",
            field=models.CharField(
                choices=[
                    ("MANUAL", "Captura manual"),
                    ("PAGO_CLIENTE", "Pago de cliente"),
                    ("PAGO_AIRBNB", "Pago Airbnb"),
                    ("COMPRA", "Compra/Gasto"),
                    ("NOMINA", "Nómina"),
                    ("AJUSTE", "Ajuste contable"),
                    ("APERTURA", "Saldo de apertura"),
                ],
                default="MANUAL",
                max_length=20,
                verbose_name="Origen",
            ),
        ),
        migrations.AddField(
            model_name="saldoapertura",
            name="certificado_por",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="saldos_certificados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Certificado por",
            ),
        ),
        migrations.AddField(
            model_name="saldoapertura",
            name="cuenta_bancaria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="saldos_apertura",
                to="contabilidad.cuentabancaria",
                verbose_name="Cuenta",
            ),
        ),
        migrations.AddField(
            model_name="saldoapertura",
            name="poliza",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="saldo_apertura",
                to="contabilidad.poliza",
                verbose_name="Póliza de apertura",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="saldoapertura",
            unique_together={("cuenta_bancaria", "fecha_corte")},
        ),
    ]
