# Generated by Django 5.1.15 on 2026-07-14 03:55

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contabilidad", "0009_saldoapertura_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EstadoCuentaBancario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "banco",
                    models.CharField(
                        default="BBVA", max_length=20, verbose_name="Banco"
                    ),
                ),
                ("periodo_mes", models.PositiveSmallIntegerField(verbose_name="Mes")),
                ("periodo_anio", models.PositiveSmallIntegerField(verbose_name="Año")),
                (
                    "archivo",
                    models.FileField(
                        upload_to="estados_cuenta/%Y/%m/", verbose_name="Archivo"
                    ),
                ),
                (
                    "formato",
                    models.CharField(
                        choices=[("PDF", "PDF"), ("XML", "XML")],
                        max_length=5,
                        verbose_name="Formato",
                    ),
                ),
                (
                    "origen",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Carga manual"),
                            ("API", "Descarga automática (futuro)"),
                        ],
                        default="MANUAL",
                        max_length=10,
                    ),
                ),
                (
                    "saldo_inicial_estado",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "saldo_final_estado",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "fecha_corte_real",
                    models.DateField(
                        blank=True,
                        help_text="La que imprime el propio banco en el PDF ('Fecha de Corte'). No asumir fin de mes calendario — algunas cuentas BBVA cortan a mitad de mes (ej. Libretón Básico corta el día 14). La conciliación usa esta fecha, no el fin del mes de periodo_mes/periodo_anio.",
                        null=True,
                        verbose_name="Fecha de corte real",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("SUBIDO", "Subido, sin procesar"),
                            ("PROCESADO", "Procesado (movimientos extraídos)"),
                            ("ERROR", "Error al procesar"),
                            ("CONCILIADO", "Conciliación confirmada"),
                        ],
                        default="SUBIDO",
                        max_length=12,
                    ),
                ),
                (
                    "error_detalle",
                    models.TextField(
                        blank=True, verbose_name="Detalle del error de procesamiento"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Estado de cuenta bancario",
                "verbose_name_plural": "Estados de cuenta bancarios",
                "ordering": ["-periodo_anio", "-periodo_mes"],
            },
        ),
        migrations.CreateModel(
            name="MovimientoEstadoCuenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("descripcion", models.CharField(blank=True, max_length=300)),
                ("referencia", models.CharField(blank=True, max_length=100)),
                (
                    "cargo",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "abono",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "saldo_parcial",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "match_automatico",
                    models.BooleanField(
                        default=False, verbose_name="Emparejado automáticamente"
                    ),
                ),
                (
                    "confirmado",
                    models.BooleanField(
                        default=False,
                        help_text="El usuario revisó y confirmó (o corrigió) este emparejamiento.",
                        verbose_name="Confirmado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de estado de cuenta",
                "verbose_name_plural": "Movimientos de estado de cuenta",
                "ordering": ["fecha", "id"],
            },
        ),
        migrations.AddField(
            model_name="estadocuentabancario",
            name="cargado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="estadocuentabancario",
            name="conciliacion",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="estado_cuenta_origen",
                to="contabilidad.conciliacionbancaria",
            ),
        ),
        migrations.AddField(
            model_name="estadocuentabancario",
            name="cuenta_bancaria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="estados_cuenta",
                to="contabilidad.cuentabancaria",
            ),
        ),
        migrations.AddField(
            model_name="movimientoestadocuenta",
            name="estado_cuenta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movimientos",
                to="contabilidad.estadocuentabancario",
            ),
        ),
        migrations.AddField(
            model_name="movimientoestadocuenta",
            name="movimiento_contable",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movimientos_banco_emparejados",
                to="contabilidad.movimientocontable",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="estadocuentabancario",
            unique_together={("cuenta_bancaria", "periodo_mes", "periodo_anio")},
        ),
    ]
