# Generated by Django 5.1.15 on 2026-07-15 17:27

from django.db import migrations, models


def cargar_configuracion_otros_ingresos(apps, schema_editor):
    """Mapea OTROS_INGRESOS_CLIENTE a la cuenta 402.02 'Otros ingresos', que
    ya existe en el catálogo SAT cargado desde la migración 0002."""
    CuentaContable = apps.get_model('contabilidad', 'CuentaContable')
    ConfiguracionContable = apps.get_model('contabilidad', 'ConfiguracionContable')
    try:
        cuenta = CuentaContable.objects.get(codigo_sat='402.02')
    except CuentaContable.DoesNotExist:
        return
    ConfiguracionContable.objects.get_or_create(
        operacion='OTROS_INGRESOS_CLIENTE',
        defaults={
            'cuenta': cuenta,
            'descripcion': 'Propinas, comisiones u otros cobros al cliente ajenos al precio de la venta',
            'activa': True,
        }
    )


def revertir_configuracion_otros_ingresos(apps, schema_editor):
    ConfiguracionContable = apps.get_model('contabilidad', 'ConfiguracionContable')
    ConfiguracionContable.objects.filter(operacion='OTROS_INGRESOS_CLIENTE').delete()


class Migration(migrations.Migration):

    dependencies = [
        ("contabilidad", "0010_estadocuentabancario_movimientoestadocuenta_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuracioncontable",
            name="operacion",
            field=models.CharField(
                choices=[
                    ("PAGO_CLIENTE_EFECTIVO", "Pago cliente - Efectivo"),
                    ("PAGO_CLIENTE_TRANSFERENCIA", "Pago cliente - Transferencia"),
                    ("PAGO_CLIENTE_TARJETA", "Pago cliente - Tarjeta"),
                    ("INGRESO_EVENTOS", "Ingreso por eventos"),
                    ("IVA_TRASLADADO", "IVA trasladado"),
                    ("ANTICIPO_CLIENTES", "Anticipo de clientes"),
                    ("ISR_RETENIDO_CLIENTES", "ISR retenido por clientes"),
                    (
                        "OTROS_INGRESOS_CLIENTE",
                        "Otros ingresos de cliente (propinas, comisiones, etc.)",
                    ),
                    ("INGRESO_AIRBNB", "Ingreso Airbnb"),
                    ("RETENCION_ISR_AIRBNB", "Retención ISR Airbnb"),
                    ("RETENCION_IVA_AIRBNB", "Retención IVA Airbnb"),
                    ("IMPUESTO_HOSPEDAJE", "Impuesto al hospedaje"),
                    ("COMISION_AIRBNB", "Comisión Airbnb"),
                    ("PROVEEDORES", "Proveedores"),
                    ("IVA_ACREDITABLE", "IVA acreditable"),
                    ("GASTOS_GENERALES", "Gastos generales"),
                    ("GASTO_INSUMOS", "Gastos - Insumos y bebidas"),
                    ("GASTO_SERVICIOS", "Gastos - Servicios (agua, luz, internet)"),
                    ("GASTO_MANTENIMIENTO", "Gastos - Mantenimiento y limpieza"),
                    ("GASTO_PUBLICIDAD", "Gastos - Publicidad y marketing"),
                    ("GASTO_EQUIPO", "Gastos - Equipo y mobiliario"),
                    ("GASTO_VEHICULOS", "Gastos - Vehículos y combustible"),
                    ("GASTO_OFICINA", "Gastos - Oficina y papelería"),
                    ("GASTO_IMPUESTOS", "Gastos - Impuestos y derechos"),
                    ("GASTO_SEGUROS", "Gastos - Seguros y fianzas"),
                    ("GASTO_BANCARIOS", "Gastos - Comisiones bancarias"),
                    ("GASTOS_BEBIDAS", "Gastos bebidas"),
                    ("GASTOS_NOMINA_EXT", "Gastos nómina externa"),
                    ("SUELDOS_SALARIOS", "Sueldos y salarios"),
                    ("IMSS_PATRONAL", "IMSS patronal"),
                    ("BANCO_PRINCIPAL", "Banco principal"),
                    ("BANCO_SECUNDARIO", "Banco secundario"),
                    ("CAJA", "Caja"),
                    (
                        "AJUSTE_APERTURA",
                        "Ajuste de apertura / resultados de ejercicios anteriores",
                    ),
                ],
                max_length=50,
                unique=True,
                verbose_name="Tipo de operación",
            ),
        ),
        migrations.RunPython(cargar_configuracion_otros_ingresos, revertir_configuracion_otros_ingresos),
    ]
