# Generated by Django 6.0.7 on 2026-07-23 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contabilidad", "0012_renombrar_unidad_negocio_eventos_a_quinta"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="cuentacontable",
            new_name="contabilida_codigo__b58027_idx",
            old_name="contabilida_codigo__a1b2c3_idx",
        ),
        migrations.RenameIndex(
            model_name="cuentacontable",
            new_name="contabilida_tipo_6d3f01_idx",
            old_name="contabilida_tipo_ac_d4e5f6_idx",
        ),
        migrations.RenameIndex(
            model_name="movimientocontable",
            new_name="contabilida_cuenta__d8586a_idx",
            old_name="contabilida_cuenta__p6q7r8_idx",
        ),
        migrations.RenameIndex(
            model_name="poliza",
            new_name="contabilida_fecha_80446c_idx",
            old_name="contabilida_fecha_t_g7h8i9_idx",
        ),
        migrations.RenameIndex(
            model_name="poliza",
            new_name="contabilida_estado_2a92fe_idx",
            old_name="contabilida_estado_j0k1l2_idx",
        ),
        migrations.RenameIndex(
            model_name="poliza",
            new_name="contabilida_unidad__ae3cc3_idx",
            old_name="contabilida_unidad__m3n4o5_idx",
        ),
        migrations.AlterField(
            model_name="poliza",
            name="concepto",
            field=models.CharField(max_length=500, verbose_name="Concepto"),
        ),
        migrations.AlterField(
            model_name="poliza",
            name="origen",
            field=models.CharField(
                choices=[
                    ("MANUAL", "Captura manual"),
                    ("PAGO_CLIENTE", "Pago de cliente"),
                    ("PAGO_AIRBNB", "Pago Airbnb"),
                    ("COMPRA", "Compra/Gasto"),
                    ("NOMINA", "Nómina"),
                    ("COMISION_OPENPAY", "Comisión Openpay"),
                    ("AJUSTE", "Ajuste contable"),
                    ("APERTURA", "Saldo de apertura"),
                ],
                default="MANUAL",
                max_length=20,
                verbose_name="Origen",
            ),
        ),
        migrations.AlterField(
            model_name="unidadnegocio",
            name="razon_social",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Razón Social"
            ),
        ),
    ]
