# Generated by Django 6.0.7 on 2026-07-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contabilidad", "0014_configurar_gasto_bancarios"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimientoestadocuenta",
            name="periodo_devengo",
            field=models.DateField(
                blank=True,
                help_text="Mes contable real del gasto (primer día del mes). Distinto de 'fecha' cuando el banco cobra a mes vencido — ej. comisión SPEI de banca por internet (Contrato de Banca en Línea BBVA, Cláusula Cuarta: 'a mes vencido'). 'fecha' sigue siendo la fecha real del cargo, para conciliar contra el estado de cuenta.",
                null=True,
                verbose_name="Periodo de devengo",
            ),
        ),
        migrations.AlterField(
            model_name="poliza",
            name="origen",
            field=models.CharField(
                choices=[
                    ("MANUAL", "Captura manual"),
                    ("PAGO_CLIENTE", "Pago de cliente"),
                    ("PAGO_AIRBNB", "Pago Airbnb"),
                    ("COMPRA", "Compra/Gasto"),
                    ("NOMINA", "Nómina"),
                    ("COMISION_OPENPAY", "Comisión Openpay"),
                    ("COMISION_TPV", "Comisión terminal (TPV)"),
                    ("AJUSTE", "Ajuste contable"),
                    ("APERTURA", "Saldo de apertura"),
                ],
                default="MANUAL",
                max_length=20,
                verbose_name="Origen",
            ),
        ),
    ]
