# Generated by Django 6.1 on 2026-08-12 03:19

import core_erp.storages_qkt
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contabilidad", "0015_movimientoestadocuenta_periodo_devengo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estadocuentabancario",
            name="archivo",
            field=models.FileField(
                storage=core_erp.storages_qkt.storage_privado,
                upload_to="estados_cuenta/%Y/%m/",
                verbose_name="Archivo",
            ),
        ),
    ]
