# Generated by Django 6.1 on 2026-08-06 18:25

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contabilidad", "0015_movimientoestadocuenta_periodo_devengo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estadocuentabancario",
            name="archivo",
            field=models.FileField(
                storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                upload_to="estados_cuenta/%Y/%m/",
                verbose_name="Archivo",
            ),
        ),
    ]
