# Generated by Django 6.1 on 2026-08-14 18:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contabilidad", "0016_alter_estadocuentabancario_archivo"),
    ]

    operations = [
        migrations.AddField(
            model_name="conciliacionbancaria",
            name="diferencia_arrastrada",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Distancia que ya existía entre libros y banco ANTES del primer día de este estado de cuenta. No se origina en este periodo: viene de pólizas anteriores al primer estado de cuenta cargado o de asientos sobre la cuenta de bancos sin respaldo bancario.",
                max_digits=14,
                verbose_name="Diferencia arrastrada de periodos anteriores",
            ),
        ),
        migrations.AddField(
            model_name="conciliacionbancaria",
            name="fecha_corte",
            field=models.DateField(
                blank=True,
                help_text="Fecha de corte impresa por el banco, que es la usada para calcular el saldo según libros. No es necesariamente el último día del mes: distintas cuentas BBVA cortan en días distintos.",
                null=True,
                verbose_name="Fecha de corte",
            ),
        ),
        migrations.AddField(
            model_name="conciliacionbancaria",
            name="fecha_inicio_periodo",
            field=models.DateField(
                blank=True,
                help_text="Fecha del primer movimiento del estado de cuenta.",
                null=True,
                verbose_name="Primer día conciliado",
            ),
        ),
        migrations.AlterField(
            model_name="conciliacionbancaria",
            name="abonos_empresa_no_abonados",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Cobros ya asentados en pólizas que el banco todavía no acredita.",
                max_digits=14,
                verbose_name="Depósitos en tránsito",
            ),
        ),
        migrations.AlterField(
            model_name="conciliacionbancaria",
            name="cargos_empresa_no_cobrados",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Pagos ya asentados en pólizas (cheques, transferencias) que todavía no aparecen en el estado de cuenta.",
                max_digits=14,
                verbose_name="Salidas registradas que el banco no ha cobrado",
            ),
        ),
        migrations.AlterField(
            model_name="conciliacionbancaria",
            name="diferencia",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=14,
                verbose_name="Diferencia del periodo",
            ),
        ),
    ]
