# Generated by Django 6.1 on 2026-08-14 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contabilidad", "0017_conciliacionbancaria_diferencia_arrastrada_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="poliza",
            name="aplicada_por",
            field=models.ForeignKey(
                blank=True,
                help_text="Quién autorizó el paso de borrador a definitiva.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="polizas_aplicadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Aplicada por",
            ),
        ),
        migrations.AddField(
            model_name="poliza",
            name="fecha_aplicacion",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
