# Generated by Django 6.1 on 2026-08-17 22:44

import core_erp.storages_qkt
import core_erp.validadores_archivos
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contabilidad", "0018_poliza_aplicada_por_poliza_fecha_aplicacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estadocuentabancario",
            name="archivo",
            field=models.FileField(
                storage=core_erp.storages_qkt.storage_privado,
                upload_to="estados_cuenta/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "xml"]
                    ),
                    core_erp.validadores_archivos.validar_firma_pdf_o_xml,
                ],
                verbose_name="Archivo",
            ),
        ),
    ]
