# Generated by Django 6.1 on 2026-09-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contabilidad", "0018_poliza_aplicada_por_poliza_fecha_aplicacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuracioncontable",
            name="operacion",
            field=models.CharField(
                choices=[
                    ("PAGO_CLIENTE_EFECTIVO", "Pago cliente - Efectivo"),
                    ("PAGO_CLIENTE_TRANSFERENCIA", "Pago cliente - Transferencia"),
                    ("PAGO_CLIENTE_TARJETA", "Pago cliente - Tarjeta"),
                    ("INGRESO_EVENTOS", "Ingreso por eventos"),
                    ("IVA_TRASLADADO", "IVA trasladado"),
                    ("ANTICIPO_CLIENTES", "Anticipo de clientes"),
                    ("ISR_RETENIDO_CLIENTES", "ISR retenido por clientes"),
                    (
                        "OTROS_INGRESOS_CLIENTE",
                        "Otros ingresos de cliente (propinas, comisiones, etc.)",
                    ),
                    ("IMPUESTO_HOSPEDAJE", "Impuesto al hospedaje"),
                    ("PROVEEDORES", "Proveedores"),
                    ("IVA_ACREDITABLE", "IVA acreditable"),
                    ("GASTOS_GENERALES", "Gastos generales"),
                    ("GASTO_INSUMOS", "Gastos - Insumos y bebidas"),
                    ("GASTO_SERVICIOS", "Gastos - Servicios (agua, luz, internet)"),
                    ("GASTO_MANTENIMIENTO", "Gastos - Mantenimiento y limpieza"),
                    ("GASTO_PUBLICIDAD", "Gastos - Publicidad y marketing"),
                    ("GASTO_EQUIPO", "Gastos - Equipo y mobiliario"),
                    ("GASTO_VEHICULOS", "Gastos - Vehículos y combustible"),
                    ("GASTO_OFICINA", "Gastos - Oficina y papelería"),
                    ("GASTO_IMPUESTOS", "Gastos - Impuestos y derechos"),
                    ("GASTO_SEGUROS", "Gastos - Seguros y fianzas"),
                    ("GASTO_BANCARIOS", "Gastos - Comisiones bancarias"),
                    ("GASTOS_BEBIDAS", "Gastos bebidas"),
                    ("GASTOS_NOMINA_EXT", "Gastos nómina externa"),
                    ("SUELDOS_SALARIOS", "Sueldos y salarios"),
                    ("IMSS_PATRONAL", "IMSS patronal"),
                    ("BANCO_PRINCIPAL", "Banco principal"),
                    ("BANCO_SECUNDARIO", "Banco secundario"),
                    ("CAJA", "Caja"),
                    (
                        "AJUSTE_APERTURA",
                        "Ajuste de apertura / resultados de ejercicios anteriores",
                    ),
                ],
                max_length=50,
                unique=True,
                verbose_name="Tipo de operación",
            ),
        ),
        migrations.AlterField(
            model_name="poliza",
            name="origen",
            field=models.CharField(
                choices=[
                    ("MANUAL", "Captura manual"),
                    ("PAGO_CLIENTE", "Pago de cliente"),
                    ("COMPRA", "Compra/Gasto"),
                    ("NOMINA", "Nómina"),
                    ("COMISION_OPENPAY", "Comisión Openpay"),
                    ("COMISION_TPV", "Comisión terminal (TPV)"),
                    ("AJUSTE", "Ajuste contable"),
                    ("APERTURA", "Saldo de apertura"),
                ],
                default="MANUAL",
                max_length=20,
                verbose_name="Origen",
            ),
        ),
        migrations.AlterField(
            model_name="unidadnegocio",
            name="clave",
            field=models.CharField(
                help_text="Identificador corto (ej: QUINTA)",
                max_length=20,
                unique=True,
                verbose_name="Clave",
            ),
        ),
    ]
