# Generated by Django 6.1 on 2026-09-26 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contabilidad", "0023_choices_deposito_garantia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conciliacionbancaria",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
        ),
        migrations.AlterField(
            model_name="conciliacionbancaria",
            name="fecha_conciliacion",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de conciliación"
            ),
        ),
        migrations.AlterField(
            model_name="conciliacionbancaria",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
        ),
        migrations.AlterField(
            model_name="cuentabancaria",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
        ),
        migrations.AlterField(
            model_name="cuentabancaria",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
        ),
        migrations.AlterField(
            model_name="cuentacontable",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
        ),
        migrations.AlterField(
            model_name="cuentacontable",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
        ),
        migrations.AlterField(
            model_name="estadocuentabancario",
            name="conciliacion",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="estado_cuenta_origen",
                to="contabilidad.conciliacionbancaria",
                verbose_name="Conciliación",
            ),
        ),
        migrations.AlterField(
            model_name="estadocuentabancario",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
        ),
        migrations.AlterField(
            model_name="estadocuentabancario",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
        ),
        migrations.AlterField(
            model_name="movimientoestadocuenta",
            name="descripcion",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Descripción"
            ),
        ),
        migrations.AlterField(
            model_name="poliza",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
        ),
        migrations.AlterField(
            model_name="poliza",
            name="fecha_aplicacion",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de aplicación"
            ),
        ),
        migrations.AlterField(
            model_name="poliza",
            name="fecha_cancelacion",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de cancelación"
            ),
        ),
        migrations.AlterField(
            model_name="poliza",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
        ),
        migrations.AlterField(
            model_name="saldoapertura",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
        ),
        migrations.AlterField(
            model_name="saldoapertura",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
        ),
    ]
