# Generated by Django 6.1 on 2026-09-26 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contabilidad", "0024_alter_conciliacionbancaria_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuracioncontable",
            name="operacion",
            field=models.CharField(
                choices=[
                    ("PAGO_CLIENTE_EFECTIVO", "Pago cliente - Efectivo"),
                    ("PAGO_CLIENTE_TRANSFERENCIA", "Pago cliente - Transferencia"),
                    ("PAGO_CLIENTE_TARJETA", "Pago cliente - Tarjeta"),
                    ("INGRESO_EVENTOS", "Ingreso por eventos"),
                    ("IVA_TRASLADADO", "IVA trasladado"),
                    ("ANTICIPO_CLIENTES", "Anticipo de clientes"),
                    ("ISR_RETENIDO_CLIENTES", "ISR retenido por clientes"),
                    (
                        "OTROS_INGRESOS_CLIENTE",
                        "Otros ingresos de cliente (propinas, comisiones, etc.)",
                    ),
                    ("DEPOSITOS_GARANTIA", "Depósitos en garantía de clientes"),
                    ("IMPUESTO_HOSPEDAJE", "Impuesto al hospedaje"),
                    ("PROVEEDORES", "Proveedores"),
                    ("IVA_ACREDITABLE", "IVA acreditable"),
                    ("GASTOS_GENERALES", "Gastos generales"),
                    ("GASTO_INSUMOS", "Gastos - Insumos y bebidas"),
                    ("GASTO_SERVICIOS", "Gastos - Servicios (agua, luz, internet)"),
                    ("GASTO_MANTENIMIENTO", "Gastos - Mantenimiento y limpieza"),
                    ("GASTO_PUBLICIDAD", "Gastos - Publicidad y marketing"),
                    ("GASTO_EQUIPO", "Gastos - Equipo y mobiliario"),
                    ("GASTO_VEHICULOS", "Gastos - Vehículos y combustible"),
                    ("GASTO_OFICINA", "Gastos - Oficina y papelería"),
                    ("GASTO_IMPUESTOS", "Gastos - Impuestos y derechos"),
                    ("GASTO_SEGUROS", "Gastos - Seguros y fianzas"),
                    ("GASTO_BANCARIOS", "Gastos - Comisiones bancarias"),
                    ("GASTOS_BEBIDAS", "Gastos bebidas"),
                    ("GASTOS_NOMINA_EXT", "Gastos nómina externa"),
                    ("SUELDOS_SALARIOS", "Sueldos y salarios"),
                    ("IMSS_PATRONAL", "IMSS patronal"),
                    ("BANCO_PRINCIPAL", "Banco principal"),
                    ("BANCO_SECUNDARIO", "Banco secundario"),
                    ("CAJA", "Caja"),
                    (
                        "AJUSTE_APERTURA",
                        "Ajuste de apertura / resultados de ejercicios anteriores",
                    ),
                    (
                        "RETIROS_DUENO",
                        "Retiros del dueño (traspasos a cuentas propias)",
                    ),
                    (
                        "APORTACIONES_DUENO",
                        "Aportaciones del dueño (traspasos desde cuentas propias)",
                    ),
                    ("GASTO_NO_DEDUCIBLE", "Gastos no deducibles (sin CFDI)"),
                    ("PARTIDAS_POR_IDENTIFICAR", "Partidas bancarias por identificar"),
                ],
                max_length=50,
                unique=True,
                verbose_name="Tipo de operación",
            ),
        ),
        migrations.AlterField(
            model_name="poliza",
            name="origen",
            field=models.CharField(
                choices=[
                    ("MANUAL", "Captura manual"),
                    ("PAGO_CLIENTE", "Pago de cliente"),
                    ("COMPRA", "Compra/Gasto"),
                    ("NOMINA", "Nómina"),
                    ("COMISION_OPENPAY", "Comisión Openpay"),
                    ("COMISION_TPV", "Comisión terminal (TPV)"),
                    ("DEPOSITO_GARANTIA", "Depósito en garantía"),
                    ("BANCO", "Movimiento bancario (regla de conciliación)"),
                    ("AJUSTE", "Ajuste contable"),
                    ("APERTURA", "Saldo de apertura"),
                ],
                default="MANUAL",
                max_length=20,
                verbose_name="Origen",
            ),
        ),
        migrations.CreateModel(
            name="ReglaConciliacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120, verbose_name="Nombre")),
                (
                    "tipo_movimiento",
                    models.CharField(
                        choices=[
                            ("CARGO", "Cargos (sale dinero)"),
                            ("ABONO", "Abonos (entra dinero)"),
                            ("AMBOS", "Cargos y abonos"),
                        ],
                        default="AMBOS",
                        max_length=5,
                        verbose_name="Aplica a",
                    ),
                ),
                (
                    "patrones",
                    models.CharField(
                        blank=True,
                        help_text="Separados por «|». Basta con que el concepto del banco contenga uno (sin distinguir mayúsculas ni acentos). Ej: TRASPAS|RETIRO",
                        max_length=300,
                        verbose_name="Textos a buscar",
                    ),
                ),
                (
                    "cuenta_tercero",
                    models.CharField(
                        blank=True,
                        help_text="Número de cuenta que aparece en el concepto (destino u origen). Más confiable que el texto: no depende de cómo se escriba el concepto.",
                        max_length=20,
                        verbose_name="Cuenta o CLABE del tercero",
                    ),
                ),
                (
                    "operacion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PAGO_CLIENTE_EFECTIVO", "Pago cliente - Efectivo"),
                            (
                                "PAGO_CLIENTE_TRANSFERENCIA",
                                "Pago cliente - Transferencia",
                            ),
                            ("PAGO_CLIENTE_TARJETA", "Pago cliente - Tarjeta"),
                            ("INGRESO_EVENTOS", "Ingreso por eventos"),
                            ("IVA_TRASLADADO", "IVA trasladado"),
                            ("ANTICIPO_CLIENTES", "Anticipo de clientes"),
                            ("ISR_RETENIDO_CLIENTES", "ISR retenido por clientes"),
                            (
                                "OTROS_INGRESOS_CLIENTE",
                                "Otros ingresos de cliente (propinas, comisiones, etc.)",
                            ),
                            ("DEPOSITOS_GARANTIA", "Depósitos en garantía de clientes"),
                            ("IMPUESTO_HOSPEDAJE", "Impuesto al hospedaje"),
                            ("PROVEEDORES", "Proveedores"),
                            ("IVA_ACREDITABLE", "IVA acreditable"),
                            ("GASTOS_GENERALES", "Gastos generales"),
                            ("GASTO_INSUMOS", "Gastos - Insumos y bebidas"),
                            (
                                "GASTO_SERVICIOS",
                                "Gastos - Servicios (agua, luz, internet)",
                            ),
                            (
                                "GASTO_MANTENIMIENTO",
                                "Gastos - Mantenimiento y limpieza",
                            ),
                            ("GASTO_PUBLICIDAD", "Gastos - Publicidad y marketing"),
                            ("GASTO_EQUIPO", "Gastos - Equipo y mobiliario"),
                            ("GASTO_VEHICULOS", "Gastos - Vehículos y combustible"),
                            ("GASTO_OFICINA", "Gastos - Oficina y papelería"),
                            ("GASTO_IMPUESTOS", "Gastos - Impuestos y derechos"),
                            ("GASTO_SEGUROS", "Gastos - Seguros y fianzas"),
                            ("GASTO_BANCARIOS", "Gastos - Comisiones bancarias"),
                            ("GASTOS_BEBIDAS", "Gastos bebidas"),
                            ("GASTOS_NOMINA_EXT", "Gastos nómina externa"),
                            ("SUELDOS_SALARIOS", "Sueldos y salarios"),
                            ("IMSS_PATRONAL", "IMSS patronal"),
                            ("BANCO_PRINCIPAL", "Banco principal"),
                            ("BANCO_SECUNDARIO", "Banco secundario"),
                            ("CAJA", "Caja"),
                            (
                                "AJUSTE_APERTURA",
                                "Ajuste de apertura / resultados de ejercicios anteriores",
                            ),
                            (
                                "RETIROS_DUENO",
                                "Retiros del dueño (traspasos a cuentas propias)",
                            ),
                            (
                                "APORTACIONES_DUENO",
                                "Aportaciones del dueño (traspasos desde cuentas propias)",
                            ),
                            ("GASTO_NO_DEDUCIBLE", "Gastos no deducibles (sin CFDI)"),
                            (
                                "PARTIDAS_POR_IDENTIFICAR",
                                "Partidas bancarias por identificar",
                            ),
                        ],
                        help_text="La cuenta sale de la Configuración contable. Usa esto o «Cuenta contrapartida».",
                        max_length=50,
                        verbose_name="Operación contable",
                    ),
                ),
                (
                    "prioridad",
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text="Se evalúan de menor a mayor.",
                        verbose_name="Prioridad",
                    ),
                ),
                (
                    "aplicar_automaticamente",
                    models.BooleanField(
                        default=True,
                        help_text="Si no, la póliza queda en borrador para revisión.",
                        verbose_name="Aplicar sola",
                    ),
                ),
                (
                    "origen",
                    models.CharField(
                        choices=[
                            ("SISTEMA", "Sistema"),
                            ("APRENDIDA", "Aprendida al clasificar"),
                            ("MANUAL", "Capturada a mano"),
                        ],
                        default="MANUAL",
                        max_length=10,
                        verbose_name="Origen",
                    ),
                ),
                ("activa", models.BooleanField(default=True, verbose_name="Activa")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creada"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizada"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reglas_conciliacion_creadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creada por",
                    ),
                ),
                (
                    "cuenta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reglas_conciliacion",
                        to="contabilidad.cuentacontable",
                        verbose_name="Cuenta contrapartida",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reglas_conciliacion_editadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Editada por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Regla de conciliación",
                "verbose_name_plural": "Reglas de conciliación",
                "ordering": ["prioridad", "id"],
            },
        ),
    ]
