# Generated by Django 6.1 on 2026-09-28 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contabilidad", "0029_config_gastos_nomina_externa"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conciliacionbancaria",
            options={
                "ordering": ["-anio", "-mes"],
                "verbose_name": "Conciliación bancaria",
                "verbose_name_plural": "Conciliaciones",
            },
        ),
        migrations.AlterModelOptions(
            name="cuentabancaria",
            options={
                "ordering": ["banco", "nombre"],
                "verbose_name": "Cuenta bancaria",
                "verbose_name_plural": "Bancos",
            },
        ),
        migrations.AlterModelOptions(
            name="cuentacontable",
            options={
                "ordering": ["codigo_sat"],
                "verbose_name": "Cuenta contable",
                "verbose_name_plural": "Catálogo",
            },
        ),
        migrations.AlterModelOptions(
            name="estadocuentabancario",
            options={
                "ordering": ["-periodo_anio", "-periodo_mes"],
                "verbose_name": "Estado de cuenta bancario",
                "verbose_name_plural": "Estados",
            },
        ),
        migrations.AlterModelOptions(
            name="reglaconciliacion",
            options={
                "ordering": ["prioridad", "id"],
                "verbose_name": "Regla de conciliación",
                "verbose_name_plural": "Reglas",
            },
        ),
        migrations.AlterModelOptions(
            name="saldoapertura",
            options={
                "ordering": ["-fecha_corte"],
                "verbose_name": "Saldo de apertura",
                "verbose_name_plural": "Apertura",
            },
        ),
        migrations.AlterModelOptions(
            name="unidadnegocio",
            options={
                "ordering": ["clave"],
                "verbose_name": "Unidad de negocio",
                "verbose_name_plural": "Unidades",
            },
        ),
    ]
