# Generated by Django 6.1 on 2026-09-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contabilidad", "0030_nombres_cortos_menu_2"),
    ]

    operations = [
        migrations.AddField(
            model_name="cuentabancaria",
            name="rol",
            field=models.CharField(
                choices=[
                    ("AMBOS", "Cobros y pagos"),
                    ("COBRO", "Solo cobros"),
                    ("PAGO", "Cuenta pagadora"),
                ],
                default="AMBOS",
                help_text="La cuenta pagadora es la que asientan solas las compras nuevas y los reembolsos por transferencia. Los cobros siguen en el Banco principal.",
                max_length=5,
                verbose_name="Uso",
            ),
        ),
        migrations.AddField(
            model_name="cuentabancaria",
            name="textos_traspaso",
            field=models.CharField(
                blank=True,
                help_text="Cómo aparece EN ESTE estado de cuenta un envío a (o desde) otra cuenta propia, separado por «|». Ej. BBVA: *STP|REVOLUT; Revolut: BBVA MEXICO. Un «*» al inicio acepta texto pegado antes (BBVA imprime «RECIBIDOSTP»).",
                max_length=200,
                verbose_name="Textos de traspaso entre cuentas propias",
            ),
        ),
        migrations.AlterField(
            model_name="configuracioncontable",
            name="operacion",
            field=models.CharField(
                choices=[
                    ("PAGO_CLIENTE_EFECTIVO", "Pago cliente - Efectivo"),
                    ("PAGO_CLIENTE_TRANSFERENCIA", "Pago cliente - Transferencia"),
                    ("PAGO_CLIENTE_TARJETA", "Pago cliente - Tarjeta"),
                    ("INGRESO_EVENTOS", "Ingreso por eventos"),
                    ("IVA_TRASLADADO", "IVA trasladado"),
                    ("ANTICIPO_CLIENTES", "Anticipo de clientes"),
                    ("ISR_RETENIDO_CLIENTES", "ISR retenido por clientes"),
                    (
                        "OTROS_INGRESOS_CLIENTE",
                        "Otros ingresos de cliente (propinas, comisiones, etc.)",
                    ),
                    ("DEPOSITOS_GARANTIA", "Depósitos en garantía de clientes"),
                    ("IMPUESTO_HOSPEDAJE", "Impuesto al hospedaje"),
                    ("PROVEEDORES", "Proveedores"),
                    ("IVA_ACREDITABLE", "IVA acreditable"),
                    ("GASTOS_GENERALES", "Gastos generales"),
                    ("GASTO_INSUMOS", "Gastos - Insumos y bebidas"),
                    ("GASTO_SERVICIOS", "Gastos - Servicios (agua, luz, internet)"),
                    ("GASTO_MANTENIMIENTO", "Gastos - Mantenimiento y limpieza"),
                    ("GASTO_PUBLICIDAD", "Gastos - Publicidad y marketing"),
                    ("GASTO_EQUIPO", "Gastos - Equipo y mobiliario"),
                    ("GASTO_VEHICULOS", "Gastos - Vehículos y combustible"),
                    ("GASTO_OFICINA", "Gastos - Oficina y papelería"),
                    ("GASTO_IMPUESTOS", "Gastos - Impuestos y derechos"),
                    ("GASTO_SEGUROS", "Gastos - Seguros y fianzas"),
                    ("GASTO_BANCARIOS", "Gastos - Comisiones bancarias"),
                    ("GASTOS_BEBIDAS", "Gastos bebidas"),
                    ("GASTOS_NOMINA_EXT", "Gastos nómina externa"),
                    ("SUELDOS_SALARIOS", "Sueldos y salarios"),
                    ("IMSS_PATRONAL", "IMSS patronal"),
                    ("BANCO_PRINCIPAL", "Banco principal"),
                    ("BANCO_SECUNDARIO", "Banco secundario"),
                    ("CAJA", "Caja"),
                    (
                        "AJUSTE_APERTURA",
                        "Ajuste de apertura / resultados de ejercicios anteriores",
                    ),
                    (
                        "RETIROS_DUENO",
                        "Retiros del dueño (traspasos a cuentas propias)",
                    ),
                    (
                        "APORTACIONES_DUENO",
                        "Aportaciones del dueño (traspasos desde cuentas propias)",
                    ),
                    (
                        "INVERSIONES",
                        "Inversiones (dinero enviado a o recuperado de una inversión)",
                    ),
                    ("GASTO_NO_DEDUCIBLE", "Gastos no deducibles (sin CFDI)"),
                    ("PARTIDAS_POR_IDENTIFICAR", "Partidas bancarias por identificar"),
                    (
                        "INGRESOS_FINANCIEROS",
                        "Ingresos financieros (intereses de la cuenta)",
                    ),
                ],
                max_length=50,
                unique=True,
                verbose_name="Tipo de operación",
            ),
        ),
        migrations.AlterField(
            model_name="estadocuentabancario",
            name="formato",
            field=models.CharField(
                choices=[("PDF", "PDF"), ("XML", "XML"), ("CSV", "CSV (Revolut)")],
                max_length=5,
                verbose_name="Formato",
            ),
        ),
        migrations.AlterField(
            model_name="reglaconciliacion",
            name="operacion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PAGO_CLIENTE_EFECTIVO", "Pago cliente - Efectivo"),
                    ("PAGO_CLIENTE_TRANSFERENCIA", "Pago cliente - Transferencia"),
                    ("PAGO_CLIENTE_TARJETA", "Pago cliente - Tarjeta"),
                    ("INGRESO_EVENTOS", "Ingreso por eventos"),
                    ("IVA_TRASLADADO", "IVA trasladado"),
                    ("ANTICIPO_CLIENTES", "Anticipo de clientes"),
                    ("ISR_RETENIDO_CLIENTES", "ISR retenido por clientes"),
                    (
                        "OTROS_INGRESOS_CLIENTE",
                        "Otros ingresos de cliente (propinas, comisiones, etc.)",
                    ),
                    ("DEPOSITOS_GARANTIA", "Depósitos en garantía de clientes"),
                    ("IMPUESTO_HOSPEDAJE", "Impuesto al hospedaje"),
                    ("PROVEEDORES", "Proveedores"),
                    ("IVA_ACREDITABLE", "IVA acreditable"),
                    ("GASTOS_GENERALES", "Gastos generales"),
                    ("GASTO_INSUMOS", "Gastos - Insumos y bebidas"),
                    ("GASTO_SERVICIOS", "Gastos - Servicios (agua, luz, internet)"),
                    ("GASTO_MANTENIMIENTO", "Gastos - Mantenimiento y limpieza"),
                    ("GASTO_PUBLICIDAD", "Gastos - Publicidad y marketing"),
                    ("GASTO_EQUIPO", "Gastos - Equipo y mobiliario"),
                    ("GASTO_VEHICULOS", "Gastos - Vehículos y combustible"),
                    ("GASTO_OFICINA", "Gastos - Oficina y papelería"),
                    ("GASTO_IMPUESTOS", "Gastos - Impuestos y derechos"),
                    ("GASTO_SEGUROS", "Gastos - Seguros y fianzas"),
                    ("GASTO_BANCARIOS", "Gastos - Comisiones bancarias"),
                    ("GASTOS_BEBIDAS", "Gastos bebidas"),
                    ("GASTOS_NOMINA_EXT", "Gastos nómina externa"),
                    ("SUELDOS_SALARIOS", "Sueldos y salarios"),
                    ("IMSS_PATRONAL", "IMSS patronal"),
                    ("BANCO_PRINCIPAL", "Banco principal"),
                    ("BANCO_SECUNDARIO", "Banco secundario"),
                    ("CAJA", "Caja"),
                    (
                        "AJUSTE_APERTURA",
                        "Ajuste de apertura / resultados de ejercicios anteriores",
                    ),
                    (
                        "RETIROS_DUENO",
                        "Retiros del dueño (traspasos a cuentas propias)",
                    ),
                    (
                        "APORTACIONES_DUENO",
                        "Aportaciones del dueño (traspasos desde cuentas propias)",
                    ),
                    (
                        "INVERSIONES",
                        "Inversiones (dinero enviado a o recuperado de una inversión)",
                    ),
                    ("GASTO_NO_DEDUCIBLE", "Gastos no deducibles (sin CFDI)"),
                    ("PARTIDAS_POR_IDENTIFICAR", "Partidas bancarias por identificar"),
                    (
                        "INGRESOS_FINANCIEROS",
                        "Ingresos financieros (intereses de la cuenta)",
                    ),
                ],
                help_text="La cuenta sale de la Configuración contable. Usa esto o «Cuenta contrapartida».",
                max_length=50,
                verbose_name="Operación contable",
            ),
        ),
    ]
