# Generated by Django 6.1 on 2026-09-29 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contabilidad", "0033_retiro_cuenta_pagadora"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PolizaEliminada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=1, verbose_name="Tipo de póliza")),
                ("folio", models.PositiveIntegerField(verbose_name="Folio")),
                ("fecha", models.DateField(verbose_name="Fecha de póliza")),
                ("concepto", models.CharField(max_length=500, verbose_name="Concepto")),
                ("origen", models.CharField(max_length=20, verbose_name="Origen")),
                (
                    "estado",
                    models.CharField(max_length=10, verbose_name="Estado al borrarse"),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Total (debe)"
                    ),
                ),
                (
                    "detalle",
                    models.JSONField(
                        help_text="Póliza y movimientos tal como estaban.",
                        verbose_name="Detalle",
                    ),
                ),
                ("motivo", models.TextField(verbose_name="Motivo")),
                (
                    "eliminada_el",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Eliminada el"
                    ),
                ),
                (
                    "eliminada_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="polizas_eliminadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Eliminada por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Póliza eliminada",
                "verbose_name_plural": "Pólizas eliminadas",
                "ordering": ["-eliminada_el"],
            },
        ),
    ]
