# Generated by Django 6.1 on 2026-09-29 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contabilidad", "0034_poliza_eliminada"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="polizaeliminada",
            options={
                "ordering": ["-eliminada_el"],
                "verbose_name": "Póliza eliminada",
                "verbose_name_plural": "Eliminadas",
            },
        ),
    ]
