# Generated by Django 6.0.3 on 2026-03-19 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReporteGenerado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("BALANZA", "Balanza de Comprobación"),
                            ("EDO_RESULTADOS", "Estado de Resultados"),
                            ("BALANCE_GRAL", "Balance General"),
                            ("LIBRO_MAYOR", "Libro Mayor"),
                            ("AUXILIAR", "Auxiliar de Cuentas"),
                            ("CXC_CARTERA", "CxC / Antigüedad de Saldos"),
                            ("COT_PERIODO", "Cotizaciones por Período"),
                            ("OCUPACION", "Ocupación por Listing"),
                            ("COMPARATIVO", "Comparativo Mensual Airbnb"),
                            ("FACTURAS", "Facturas Emitidas"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Reporte",
                    ),
                ),
                (
                    "formato",
                    models.CharField(
                        choices=[("PDF", "PDF"), ("HTML", "Vista en Pantalla")],
                        default="PDF",
                        max_length=10,
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(verbose_name="Fecha Inicio del Período"),
                ),
                ("fecha_fin", models.DateField(verbose_name="Fecha Fin del Período")),
                (
                    "parametros",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Filtros aplicados (unidad negocio, cuenta, listing, etc.)",
                        verbose_name="Parámetros",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Generación"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Generado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reporte Generado",
                "verbose_name_plural": "Reportes Generados",
                "ordering": ["-created_at"],
            },
        ),
    ]
