# Generated by Django 5.1.15 on 2026-07-10 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reportes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reportegenerado",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Generado",
                "verbose_name_plural": "Historial",
            },
        ),
    ]
