# Generated by Django 6.1 on 2026-09-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportes", "0002_alter_reportegenerado_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportegenerado",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("BALANZA", "Balanza de Comprobación"),
                    ("EDO_RESULTADOS", "Estado de Resultados"),
                    ("BALANCE_GRAL", "Balance General"),
                    ("LIBRO_MAYOR", "Libro Mayor"),
                    ("AUXILIAR", "Auxiliar de Cuentas"),
                    ("CXC_CARTERA", "CxC / Antigüedad de Saldos"),
                    ("COT_PERIODO", "Cotizaciones por Período"),
                    ("FACTURAS", "Facturas Emitidas"),
                ],
                max_length=20,
                verbose_name="Tipo de Reporte",
            ),
        ),
    ]
