# Generated by Django 6.1 on 2026-10-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportes", "0003_retiro_reportes_airbnb"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportegenerado",
            name="formato",
            field=models.CharField(
                choices=[
                    ("PDF", "PDF"),
                    ("HTML", "Vista en Pantalla"),
                    ("EXCEL", "Excel"),
                ],
                default="PDF",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="reportegenerado",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("BALANZA", "Balanza de Comprobación"),
                    ("EDO_RESULTADOS", "Estado de Resultados"),
                    ("BALANCE_GRAL", "Balance General"),
                    ("LIBRO_MAYOR", "Libro Mayor"),
                    ("AUXILIAR", "Auxiliar de Cuentas"),
                    ("CXC_CARTERA", "CxC / Antigüedad de Saldos"),
                    ("COT_PERIODO", "Cotizaciones por Período"),
                    ("RENTABILIDAD", "Rentabilidad por Evento"),
                    ("PAGOS", "Pagos Recibidos"),
                    ("FACTURAS", "Facturas Emitidas"),
                ],
                max_length=20,
                verbose_name="Tipo de Reporte",
            ),
        ),
    ]
