# Generated by Django 6.1 on 2026-10-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportes", "0004_tipos_rentabilidad_pagos_excel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportegenerado",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("BALANZA", "Balanza de Comprobación"),
                    ("EDO_RESULTADOS", "Estado de Resultados"),
                    ("BALANCE_GRAL", "Balance General"),
                    ("LIBRO_MAYOR", "Libro Mayor"),
                    ("AUXILIAR", "Auxiliar de Cuentas"),
                    ("FLUJO", "Flujo de Efectivo"),
                    ("CONCILIACION", "Conciliación Bancaria"),
                    ("GASTOS", "Gastos por Categoría"),
                    ("CXC_CARTERA", "CxC / Antigüedad de Saldos"),
                    ("COT_PERIODO", "Cotizaciones por Período"),
                    ("RENTABILIDAD", "Rentabilidad por Evento"),
                    ("PAGOS", "Pagos Recibidos"),
                    ("OCUPACION", "Ocupación"),
                    ("DEPOSITOS", "Depósitos en Garantía"),
                    ("CORTESIAS", "Cortesías y Descuentos"),
                    ("KOOXI", "Agente Kooxi"),
                    ("NOMINA", "Nómina por Periodo"),
                    ("FACTURAS", "Facturas Emitidas"),
                ],
                max_length=20,
                verbose_name="Tipo de Reporte",
            ),
        ),
    ]
