# Generated by Django 6.1 on 2026-08-27 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("comercial", "0076_cotizacion_identificacion_revisada_and_more"),
        ("nomina", "0004_alter_recibonomina_archivo_pdf"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlantillaChecklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("TURNOVER_EVENTO", "Preparación — Evento"),
                            ("TURNOVER_PASADIA", "Preparación — Pasadía"),
                            ("TURNOVER_HOSPEDAJE", "Preparación — Hospedaje"),
                            ("TURNOVER_ARRENDAMIENTO", "Preparación — Arrendamiento"),
                            ("MANTENIMIENTO_RECURRENTE", "Mantenimiento recurrente"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "encabezado",
                    models.CharField(
                        blank=True,
                        help_text="Título del mensaje, ej. 'Preparación — Hospedaje'. Vacío usa el nombre.",
                        max_length=100,
                    ),
                ),
                (
                    "duracion_estimada_horas",
                    models.DecimalField(
                        decimal_places=1,
                        default=2.0,
                        help_text="Solo turnover: cuánto antes de la hora límite debe entrar el colaborador a preparar.",
                        max_digits=4,
                    ),
                ),
                (
                    "hora_limite_default",
                    models.TimeField(
                        blank=True,
                        help_text="Solo mantenimiento recurrente: hora límite del día. Turnover usa la hora de inicio real del servicio.",
                        null=True,
                    ),
                ),
                (
                    "cadencia",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DIARIA", "Diaria"),
                            ("SEMANAL", "Semanal"),
                            ("MENSUAL", "Mensual"),
                        ],
                        help_text="Solo mantenimiento recurrente.",
                        max_length=10,
                    ),
                ),
                (
                    "dia_semana",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "Lunes"),
                            (1, "Martes"),
                            (2, "Miércoles"),
                            (3, "Jueves"),
                            (4, "Viernes"),
                            (5, "Sábado"),
                            (6, "Domingo"),
                        ],
                        help_text="Solo cadencia semanal.",
                        null=True,
                    ),
                ),
                (
                    "dia_mes",
                    models.IntegerField(
                        blank=True,
                        help_text="Solo cadencia mensual (1-28, para evitar meses cortos).",
                        null=True,
                    ),
                ),
                ("activa", models.BooleanField(default=True)),
                (
                    "responsable_default",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plantillas_checklist",
                        to="nomina.empleado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plantilla de checklist",
                "verbose_name_plural": "Plantillas de checklist",
                "ordering": ["tipo", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="ItemChecklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "orden",
                    models.PositiveIntegerField(
                        default=1, help_text="Orden de ejecución física, no alfabético."
                    ),
                ),
                (
                    "texto",
                    models.CharField(
                        help_text="Verbo + objeto + criterio de terminado. Ej. 'Tallar y trapear los 2 baños — sin manchas ni cabello en el piso'.",
                        max_length=300,
                    ),
                ),
                (
                    "plantilla",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="operaciones.plantillachecklist",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarea del checklist",
                "verbose_name_plural": "Tareas del checklist",
                "ordering": ["plantilla", "orden"],
            },
        ),
        migrations.CreateModel(
            name="TareaProgramada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.DateField(help_text="Día en que se ejecuta la tarea."),
                ),
                (
                    "hora_entrada",
                    models.TimeField(
                        help_text="Hora de entrada del colaborador ese día."
                    ),
                ),
                (
                    "hora_limite",
                    models.TimeField(help_text="Hora límite para tener todo listo."),
                ),
                ("requiere_tiempo_extra", models.BooleanField(default=False)),
                (
                    "estado_aviso_horario",
                    models.CharField(
                        choices=[
                            ("NO_APLICA", "No aplica"),
                            ("PENDIENTE", "Pendiente"),
                            ("ENVIADO", "Enviado"),
                            ("FALLIDO", "Fallido"),
                        ],
                        default="NO_APLICA",
                        max_length=10,
                    ),
                ),
                (
                    "estado_operativo",
                    models.CharField(
                        choices=[
                            ("NO_APLICA", "No aplica"),
                            ("PENDIENTE", "Pendiente"),
                            ("ENVIADO", "Enviado"),
                            ("FALLIDO", "Fallido"),
                        ],
                        default="PENDIENTE",
                        max_length=10,
                    ),
                ),
                (
                    "estado_resumen_propietario",
                    models.CharField(
                        choices=[
                            ("NO_APLICA", "No aplica"),
                            ("PENDIENTE", "Pendiente"),
                            ("ENVIADO", "Enviado"),
                            ("FALLIDO", "Fallido"),
                        ],
                        default="PENDIENTE",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cotizacion",
                    models.ForeignKey(
                        blank=True,
                        help_text="Solo turnover: la cotización cuyo servicio se está preparando.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tareas_operativas",
                        to="comercial.cotizacion",
                    ),
                ),
                (
                    "plantilla",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tareas",
                        to="operaciones.plantillachecklist",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tareas_programadas",
                        to="nomina.empleado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarea programada",
                "verbose_name_plural": "Tareas programadas",
                "ordering": ["-fecha", "hora_entrada"],
                "indexes": [
                    models.Index(
                        fields=["fecha", "responsable"],
                        name="operaciones_fecha_c3bde7_idx",
                    ),
                    models.Index(
                        fields=["estado_operativo"],
                        name="operaciones_estado__20d650_idx",
                    ),
                    models.Index(
                        fields=["estado_resumen_propietario"],
                        name="operaciones_estado__152f67_idx",
                    ),
                    models.Index(
                        fields=["estado_aviso_horario"],
                        name="operaciones_estado__cc7f89_idx",
                    ),
                ],
                "unique_together": {("plantilla", "cotizacion", "fecha")},
            },
        ),
    ]
