# Generated by Django 6.1 on 2026-08-29 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("operaciones", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plantillachecklist",
            options={
                "ordering": ["tipo", "nombre"],
                "verbose_name": "Plantilla de checklist",
                "verbose_name_plural": "Plantillas",
            },
        ),
        migrations.AlterModelOptions(
            name="tareaprogramada",
            options={
                "ordering": ["-fecha", "hora_entrada"],
                "verbose_name": "Tarea programada",
                "verbose_name_plural": "Tareas",
            },
        ),
    ]
