# Generated by Django 6.1 on 2026-09-26 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0103_alter_subproducto_options_and_more"),
        ("operaciones", "0002_alter_plantillachecklist_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plantillachecklist",
            name="dia_mes",
            field=models.IntegerField(
                blank=True,
                help_text="Solo cadencia mensual (1-28, para evitar meses cortos).",
                null=True,
                verbose_name="Día del mes",
            ),
        ),
        migrations.AlterField(
            model_name="plantillachecklist",
            name="dia_semana",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Lunes"),
                    (1, "Martes"),
                    (2, "Miércoles"),
                    (3, "Jueves"),
                    (4, "Viernes"),
                    (5, "Sábado"),
                    (6, "Domingo"),
                ],
                help_text="Solo cadencia semanal.",
                null=True,
                verbose_name="Día de la semana",
            ),
        ),
        migrations.AlterField(
            model_name="plantillachecklist",
            name="duracion_estimada_horas",
            field=models.DecimalField(
                decimal_places=1,
                default=2.0,
                help_text="Solo turnover: cuánto antes de la hora límite debe entrar el colaborador a preparar.",
                max_digits=4,
                verbose_name="Duración estimada (horas)",
            ),
        ),
        migrations.AlterField(
            model_name="plantillachecklist",
            name="hora_limite_default",
            field=models.TimeField(
                blank=True,
                help_text="Solo mantenimiento recurrente: hora límite del día. Turnover usa la hora de inicio real del servicio.",
                null=True,
                verbose_name="Hora límite por defecto",
            ),
        ),
        migrations.AlterField(
            model_name="tareaprogramada",
            name="cotizacion",
            field=models.ForeignKey(
                blank=True,
                help_text="Solo turnover: la cotización cuyo servicio se está preparando.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tareas_operativas",
                to="comercial.cotizacion",
                verbose_name="Cotización",
            ),
        ),
        migrations.AlterField(
            model_name="tareaprogramada",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
        ),
        migrations.AlterField(
            model_name="tareaprogramada",
            name="hora_limite",
            field=models.TimeField(
                help_text="Hora límite para tener todo listo.",
                verbose_name="Hora límite",
            ),
        ),
    ]
