# Generated by Django 6.0.1 on 2026-01-27 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('origen', models.CharField(choices=[('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('Google', 'Google'), ('Recomendacion', 'Recomendación'), ('Otro', 'Otro')], default='Otro', max_length=50)),
                ('es_cliente_fiscal', models.BooleanField(default=False, verbose_name='¿Datos Fiscales Completos?')),
                ('tipo_persona', models.CharField(choices=[('FISICA', 'Persona Física (Juan Pérez)'), ('MORAL', 'Persona Moral (Empresa S.A. de C.V.)')], default='FISICA', max_length=10)),
                ('rfc', models.CharField(blank=True, max_length=13, null=True, verbose_name='RFC')),
                ('razon_social', models.CharField(blank=True, max_length=200, null=True, verbose_name='Razón Social')),
                ('codigo_postal_fiscal', models.CharField(blank=True, max_length=5, null=True, verbose_name='C.P. Fiscal')),
                ('regimen_fiscal', models.CharField(blank=True, choices=[('601', '601 - General de Ley Personas Morales'), ('603', '603 - Personas Morales con Fines no Lucrativos'), ('623', '623 - Opcional para Grupos de Sociedades'), ('624', '624 - Coordinados'), ('626', '626 - Régimen Simplificado de Confianza (RESICO)'), ('605', '605 - Sueldos y Salarios e Ingresos Asimilados a Salarios'), ('606', '606 - Arrendamiento'), ('607', '607 - Régimen de Enajenación o Adquisición de Bienes'), ('608', '608 - Demás ingresos'), ('610', '610 - Residentes en el Extranjero sin Establecimiento Permanente en México'), ('611', '611 - Ingresos por Dividendos (socios y accionistas)'), ('612', '612 - Personas Físicas con Actividades Empresariales y Profesionales'), ('614', '614 - Ingresos por intereses'), ('615', '615 - Régimen de los ingresos por obtención de premios'), ('616', '616 - Sin obligaciones fiscales'), ('620', '620 - Sociedades Cooperativas de Producción'), ('621', '621 - Incorporación Fiscal (RIF)'), ('622', '622 - Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras'), ('625', '625 - Plataformas Tecnológicas')], default='616', max_length=3, null=True)),
                ('uso_cfdi', models.CharField(blank=True, choices=[('G01', 'G01 - Adquisición de mercancías'), ('G02', 'G02 - Devoluciones, descuentos o bonificaciones'), ('G03', 'G03 - Gastos en general'), ('I01', 'I01 - Construcciones'), ('I02', 'I02 - Mobiliario y equipo de oficina'), ('I03', 'I03 - Equipo de transporte'), ('I04', 'I04 - Equipo de computo y accesorios'), ('D01', 'D01 - Honorarios médicos, dentales y gastos hospitalarios'), ('D02', 'D02 - Gastos médicos por incapacidad'), ('D03', 'D03 - Gastos funerales'), ('D04', 'D04 - Donativos'), ('D05', 'D05 - Intereses reales hipotecarios'), ('D06', 'D06 - Aportaciones voluntarias al SAR'), ('D07', 'D07 - Primas por seguros de gastos médicos'), ('D08', 'D08 - Gastos de transportación escolar obligatoria'), ('D09', 'D09 - Depósitos en cuentas para el ahorro'), ('D10', 'D10 - Pagos por servicios educativos (Colegiaturas)'), ('S01', 'S01 - Sin efectos fiscales'), ('CP01', 'CP01 - Pagos'), ('CN01', 'CN01 - Nómina')], default='G03', max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('unidad_medida', models.CharField(max_length=50)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_stock', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('categoria', models.CharField(choices=[('CONSUMIBLE', 'Consumible (Se gasta: Hielo, Comida, Desechables)'), ('MOBILIARIO', 'Mobiliario (Se renta: Sillas, Mesas, Manteles)'), ('SERVICIO', 'Personal (RH: Meseros, Seguridad, Staff)')], default='CONSUMIBLE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('margen_ganancia', models.DecimalField(decimal_places=2, default=0.3, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='SubProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_evento', models.CharField(default='Evento General', help_text='Ej: Boda de Laura y Luis', max_length=200)),
                ('fecha_evento', models.DateField()),
                ('hora_inicio', models.TimeField(blank=True, null=True, verbose_name='Hora Inicio')),
                ('hora_fin', models.TimeField(blank=True, null=True, verbose_name='Hora Fin')),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Descuento ($)')),
                ('requiere_factura', models.BooleanField(default=False, help_text='Si se marca, calcula IVA y Retenciones')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, help_text='Suma de todos los ítems', max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('retencion_isr', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('retencion_iva', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('precio_final', models.DecimalField(decimal_places=2, editable=False, help_text='Total a Pagar (Neto)', max_digits=10)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONFIRMADA', 'Venta Confirmada'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='cotizaciones_pdf/')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.cliente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Elaborado por')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_gasto', models.DateField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('categoria', models.CharField(choices=[('PROVEEDOR', 'Pago a Proveedor (Hielo, Comida)'), ('NOMINA', 'Pago de Nómina (Meseros, Staff)'), ('SERVICIOS', 'Servicios (Luz, Agua, Gas)'), ('MANTENIMIENTO', 'Mantenimiento Quinta'), ('IMPUESTOS', 'Pago de Impuestos'), ('OTRO', 'Otros Gastos')], default='PROVEEDOR', max_length=20)),
                ('proveedor', models.CharField(blank=True, max_length=200)),
                ('archivo_xml', models.FileField(blank=True, null=True, upload_to='xml_gastos/')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='pdf_gastos/')),
                ('uuid', models.CharField(blank=True, max_length=36, null=True, unique=True)),
                ('evento_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comercial.cotizacion')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia Electrónica'), ('TARJETA_CREDITO', 'Tarjeta de Crédito'), ('TARJETA_DEBITO', 'Tarjeta de Débito'), ('CHEQUE', 'Cheque Nominativo'), ('DEPOSITO', 'Depósito Bancario'), ('PLATAFORMA', 'Plataforma (PayPal/Stripe)'), ('CONDONACION', 'Condonación / Cortesía'), ('OTRO', 'Otro Método')], max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='comercial.cotizacion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Recibido por')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, help_text='Opcional: Detalle específico', max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='comercial.cotizacion')),
                ('insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comercial.insumo', verbose_name='Insumo Individual (Extra)')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comercial.producto', verbose_name='Producto (Paquete)')),
            ],
        ),
        migrations.CreateModel(
            name='RecetaSubProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, help_text='Cantidad de insumo por unidad de SubProducto', max_digits=10)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comercial.insumo')),
                ('subproducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receta', to='comercial.subproducto')),
            ],
        ),
        migrations.CreateModel(
            name='ComponenteProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Ej: 50 Margaritas en este paquete', max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='comercial.producto')),
                ('subproducto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comercial.subproducto')),
            ],
        ),
    ]
