# Generated by Django 6.0.1 on 2026-01-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='cantidad_stock',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
