# Generated by Django 6.0.1 on 2026-01-29 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(blank=True, max_length=200)),
                ('rfc_emisor', models.CharField(blank=True, max_length=13)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('ret_isr', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('ret_iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('archivo_xml', models.FileField(upload_to='xml_compras/')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='pdf_compras/')),
                ('uuid', models.CharField(blank=True, max_length=36, null=True, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='archivo_pdf',
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='archivo_xml',
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='monto',
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='uuid',
        ),
        migrations.AddField(
            model_name='gasto',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='gasto',
            name='clave_sat',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='gasto',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='gasto',
            name='total_linea',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='gasto',
            name='unidad_medida',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_persona',
            field=models.CharField(choices=[('FISICA', 'Persona Física'), ('MORAL', 'Persona Moral')], default='FISICA', max_length=10),
        ),
        migrations.AlterField(
            model_name='componenteproducto',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='nombre_evento',
            field=models.CharField(default='Evento General', max_length=200),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='precio_final',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='requiere_factura',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='retencion_isr',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='retencion_iva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='categoria',
            field=models.CharField(choices=[('SIN_CLASIFICAR', '⚠️ Sin Clasificar'), ('INSUMO_COCINA', 'Insumos Cocina (Carne, Verdura)'), ('BEBIDAS', 'Bebidas y Alcohol'), ('DESECHABLES', 'Desechables y Limpieza'), ('MOBILIARIO_EQ', 'Mobiliario y Equipo'), ('MANTENIMIENTO', 'Mantenimiento y Reparaciones'), ('NOMINA_EXT', 'Servicios Staff Externo'), ('IMPUESTOS', 'Pago de Impuestos'), ('PUBLICIDAD', 'Publicidad y Marketing'), ('COMBUSTIBLE', 'Combustible y Viáticos'), ('OFICINA', 'Papelería y Oficina'), ('OTRO', 'Otros Gastos')], default='SIN_CLASIFICAR', max_length=20),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='descripcion',
            field=models.CharField(default='Gasto General', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemcotizacion',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='itemcotizacion',
            name='insumo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comercial.insumo'),
        ),
        migrations.AlterField(
            model_name='itemcotizacion',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comercial.producto'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia Electrónica'), ('TARJETA_CREDITO', 'Tarjeta de Crédito'), ('TARJETA_DEBITO', 'Tarjeta de Débito'), ('CHEQUE', 'Cheque Nominativo'), ('DEPOSITO', 'Depósito Bancario'), ('PLATAFORMA', 'Plataforma'), ('CONDONACION', 'Condonación / Cortesía'), ('OTRO', 'Otro Método')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recetasubproducto',
            name='cantidad',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AddField(
            model_name='gasto',
            name='compra',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='comercial.compra'),
            preserve_default=False,
        ),
    ]
