# Generated by Django 6.0.1 on 2026-01-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='cotizaciones_pdf/'),
        ),
    ]
