# Generated by Django 6.0.1 on 2026-01-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0002_insumo_cantidad_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='categoria',
            field=models.CharField(choices=[('CONSUMIBLE', 'Consumible (Se gasta: Hielo, Comida, Desechables)'), ('MOBILIARIO', 'Mobiliario/Equipo (Se renta: Sillas, Mesas, Manteles)')], default='CONSUMIBLE', max_length=20),
        ),
    ]
