# Generated by Django 6.0.1 on 2026-01-29 23:03

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0002_compra_remove_gasto_archivo_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='pdf_gastos/'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='archivo_xml',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='xml_gastos/'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='pdf_compras/'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='archivo_xml',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='xml_compras/'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='cotizaciones_pdf/'),
        ),
    ]
