# Generated by Django 6.0.1 on 2026-01-14 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0003_insumo_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='categoria',
            field=models.CharField(choices=[('CONSUMIBLE', 'Consumible (Se gasta: Hielo, Comida)'), ('MOBILIARIO', 'Mobiliario (Se renta: Sillas, Mesas)'), ('SERVICIO', 'Personal (RH: Meseros, Seguridad, Staff)')], default='CONSUMIBLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='margen_ganancia',
            field=models.DecimalField(decimal_places=2, default=0.3, max_digits=4),
        ),
    ]
