# Generated by Django 6.0.1 on 2026-01-19 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0003_cliente_fecha_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='codigo_postal_fiscal',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='C.P. Fiscal'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='es_cliente_fiscal',
            field=models.BooleanField(default=False, verbose_name='¿Datos Fiscales Completos?'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='razon_social',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Razón Social'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='regimen_fiscal',
            field=models.CharField(blank=True, choices=[('601', '601 - General de Ley Personas Morales'), ('612', '612 - Personas Físicas con Actividades Empresariales'), ('626', '626 - Régimen Simplificado de Confianza (RESICO)'), ('605', '605 - Sueldos y Salarios'), ('603', '603 - Personas Morales con Fines no Lucrativos')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='RFC'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_persona',
            field=models.CharField(choices=[('FISICA', 'Persona Física (Juan Pérez)'), ('MORAL', 'Persona Moral (Empresa S.A. de C.V.)')], default='FISICA', help_text='Define si lleva Retenciones', max_length=10),
        ),
        migrations.AddField(
            model_name='cliente',
            name='uso_cfdi',
            field=models.CharField(blank=True, choices=[('G03', 'G03 - Gastos en general'), ('P01', 'P01 - Por definir'), ('G01', 'G01 - Adquisición de mercancías'), ('D04', 'D04 - Donativos')], max_length=100, null=True),
        ),
    ]
