# Generated by Django 6.0.1 on 2026-01-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0004_cotizacion_hora_fin_cotizacion_hora_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='metodo',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia Electrónica'), ('TARJETA_CREDITO', 'Tarjeta de Crédito'), ('TARJETA_DEBITO', 'Tarjeta de Débito'), ('CHEQUE', 'Cheque Nominativo'), ('DEPOSITO', 'Depósito Bancario'), ('PLATAFORMA', 'Plataforma (PayPal/Stripe)'), ('CONDONACION', 'Condonación / Cortesía'), ('OTRO', 'Otro Método')], max_length=20),
        ),
    ]
