# Generated by Django 6.0.1 on 2026-01-30 18:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0004_alter_gasto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Pago'),
        ),
    ]
