# Generated by Django 6.0.1 on 2026-01-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0004_alter_insumo_categoria_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacion',
            options={'verbose_name': 'Cotización', 'verbose_name_plural': 'Cotizaciones'},
        ),
        migrations.AlterField(
            model_name='insumo',
            name='categoria',
            field=models.CharField(choices=[('CONSUMIBLE', 'Consumible (Se gasta: Hielo, Comida, Desechables)'), ('MOBILIARIO', 'Mobiliario (Se renta: Sillas, Mesas, Manteles)'), ('SERVICIO', 'Personal (RH: Meseros, Seguridad, Staff)')], default='CONSUMIBLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='margen_ganancia',
            field=models.DecimalField(decimal_places=2, default=0.3, help_text='Ej: 0.30 para 30%', max_digits=4),
        ),
    ]
