# Generated by Django 6.0.1 on 2026-01-23 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0005_alter_pago_metodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Descuento ($)'),
        ),
    ]
