# Generated by Django 6.0.1 on 2026-02-05 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0005_alter_pago_fecha_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='crear_como_subproducto',
            field=models.BooleanField(default=False, help_text='Si marcas esto, se creará un Subproducto automático y su receta (1 a 1) al guardar.', verbose_name='¿Crear también como Subproducto?'),
        ),
    ]
