# Generated by Django 6.0.1 on 2026-01-15 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0005_alter_cotizacion_options_alter_insumo_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_gasto', models.DateField(help_text='Si subes XML, se llena sola')),
                ('descripcion', models.CharField(help_text='Se llena sola con el XML', max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, help_text='Se llena sola con el XML', max_digits=10)),
                ('categoria', models.CharField(choices=[('PROVEEDOR', 'Pago a Proveedor (Hielo, Comida)'), ('NOMINA', 'Pago de Nómina (Meseros, Staff)'), ('SERVICIOS', 'Servicios (Luz, Agua, Gas)'), ('MANTENIMIENTO', 'Mantenimiento Quinta'), ('IMPUESTOS', 'Pago de Impuestos'), ('OTRO', 'Otros Gastos')], default='PROVEEDOR', max_length=20)),
                ('proveedor', models.CharField(blank=True, help_text='Nombre del Emisor (del XML)', max_length=200)),
                ('archivo_xml', models.FileField(blank=True, help_text='Sube aquí tu CFDI 4.0', null=True, upload_to='xml_gastos/')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='pdf_gastos/')),
                ('uuid', models.CharField(blank=True, help_text='Folio Fiscal para evitar duplicados', max_length=36, null=True, unique=True)),
                ('evento_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comercial.cotizacion')),
            ],
        ),
    ]
