# Generated by Django 6.0.1 on 2026-01-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0006_gasto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='descripcion',
            field=models.CharField(blank=True, help_text='Se llena sola con el XML', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='fecha_gasto',
            field=models.DateField(blank=True, help_text='Si subes XML, se llena sola', null=True),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Se llena sola con el XML', max_digits=10, null=True),
        ),
    ]
