# Generated by Django 6.0.1 on 2026-02-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0006_insumo_crear_como_subproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='horas_servicio',
            field=models.IntegerField(default=5, verbose_name='Horas de Servicio Barra'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='num_personas',
            field=models.IntegerField(default=50, verbose_name='Número de Personas'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='tipo_barra',
            field=models.CharField(choices=[('ninguna', 'Sin Servicio de Alcohol'), ('basico', 'Paquete Básico (Botellas 1L - Nacional)'), ('premium', 'Paquete Premium (Botellas 1L - Importado)')], default='ninguna', max_length=20, verbose_name='Tipo de Barra Libre'),
        ),
    ]
