# Generated by Django 6.0.1 on 2026-02-06 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0007_cotizacion_horas_servicio_cotizacion_num_personas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='factor_utilidad_barra',
            field=models.DecimalField(decimal_places=2, default=2.2, help_text='Ej: 2.2 = 220%. Sugerido: 2.2 para Alcohol, 3.0 para Refrescos.', max_digits=5, verbose_name='Factor Utilidad Barra'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='tipo_barra',
            field=models.CharField(choices=[('ninguna', 'Sin Servicio de Alcohol'), ('sin_alcohol', 'Barra Refrescos (Solo Mezcladores)'), ('basico', 'Paquete Básico (Botellas 1L - Nacional)'), ('premium', 'Paquete Premium (Botellas 1L - Importado)')], default='ninguna', max_length=20, verbose_name='Tipo de Barra Libre'),
        ),
    ]
