# Generated by Django 6.0.1 on 2026-01-15 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0007_alter_gasto_descripcion_alter_gasto_fecha_gasto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='rfc',
            field=models.CharField(blank=True, help_text='Opcional para facturar', max_length=13),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_persona',
            field=models.CharField(choices=[('FISICA', 'Persona Física (Juan Pérez)'), ('MORAL', 'Persona Moral (Empresa S.A. de C.V.)')], default='FISICA', help_text='Define si lleva Retenciones (RESICO)', max_length=10),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='requiere_factura',
            field=models.BooleanField(default=False, help_text='Si se marca, calcula IVA y Retenciones'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='retencion_isr',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='retencion_iva',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio del servicio ANTES de impuestos', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='precio_final',
            field=models.DecimalField(decimal_places=2, editable=False, help_text='Total a Pagar (Neto)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='archivo_xml',
            field=models.FileField(blank=True, null=True, upload_to='xml_gastos/'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='uuid',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='margen_ganancia',
            field=models.DecimalField(decimal_places=2, default=0.3, max_digits=4),
        ),
    ]
