# Generated by Django 6.0.1 on 2026-02-06 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0008_cotizacion_factor_utilidad_barra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='insumo_agua',
            field=models.ForeignKey(blank=True, help_text='Selecciona el garrafón', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='comercial.insumo', verbose_name='Insumo Agua'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='insumo_alcohol_basico',
            field=models.ForeignKey(blank=True, help_text='Ej: Bacardí o Etiqueta Roja', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='comercial.insumo', verbose_name='Alcohol Básico'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='insumo_alcohol_premium',
            field=models.ForeignKey(blank=True, help_text='Ej: Etiqueta Negra o Dobel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='comercial.insumo', verbose_name='Alcohol Premium'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='insumo_auxiliar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='comercial.insumo', verbose_name='Insumo Auxiliar'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='insumo_barman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='comercial.insumo', verbose_name='Insumo Bartender'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='insumo_hielo',
            field=models.ForeignKey(blank=True, help_text='Selecciona la bolsa de hielo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='comercial.insumo', verbose_name='Insumo Hielo (20kg)'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='insumo_refresco',
            field=models.ForeignKey(blank=True, help_text='Selecciona el refresco base', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='comercial.insumo', verbose_name='Insumo Refresco'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='factor_rendimiento',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Ej: Caja de 6 refrescos de 3L = 18 (Litros). Caja de 12 botellas = 12 (Piezas). Si es unitario, deja 1.', max_digits=10, verbose_name='Rendimiento (Divisor)'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='codigo_postal_fiscal',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='es_cliente_fiscal',
            field=models.BooleanField(default=False, verbose_name='¿Datos Fiscales?'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='razon_social',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_persona',
            field=models.CharField(choices=[('FISICA', 'Física'), ('MORAL', 'Moral')], default='FISICA', max_length=10),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='factor_utilidad_barra',
            field=models.DecimalField(decimal_places=2, default=2.2, max_digits=5, verbose_name='Factor Utilidad'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='horas_servicio',
            field=models.IntegerField(default=5, verbose_name='Horas Servicio'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='tipo_barra',
            field=models.CharField(choices=[('ninguna', 'Sin Servicio de Alcohol'), ('sin_alcohol', 'Barra Refrescos (Solo Mezcladores)'), ('basico', 'Paquete Básico (Botellas 1L - Nacional)'), ('premium', 'Paquete Premium (Botellas 1L - Importado)')], default='ninguna', max_length=20, verbose_name='Tipo Barra'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='categoria',
            field=models.CharField(choices=[('CONSUMIBLE', 'Consumible (Hielo, Comida, Desechables)'), ('MOBILIARIO', 'Mobiliario (Sillas, Mesas)'), ('SERVICIO', 'Personal (Bartender, Staff, Seguridad)')], default='CONSUMIBLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo de Compra'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='crear_como_subproducto',
            field=models.BooleanField(default=False, help_text='Si marcas esto, se creará un Subproducto automático.', verbose_name='¿Crear también como Subproducto?'),
        ),
    ]
