# Generated by Django 6.0.1 on 2026-02-06 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0009_cotizacion_insumo_agua_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='categoria',
            field=models.CharField(choices=[('CONSUMIBLE', 'Consumible (Hielo, Comida, Desechables)'), ('MOBILIARIO', 'Mobiliario (Se renta: Sillas, Mesas)'), ('SERVICIO', 'Personal (Bartender, Staff, Seguridad)')], default='CONSUMIBLE', max_length=20),
        ),
    ]
