# Generated by Django 6.0.1 on 2026-02-09 18:35

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0010_alter_insumo_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='archivo_xml',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='xml_compras/'),
        ),
    ]
