# Generated by Django 6.0.1 on 2026-02-10 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0011_alter_compra_archivo_xml'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='clima',
            field=models.CharField(choices=[('normal', 'Interior / Aire Acondicionado (Consumo Normal)'), ('calor', 'Exterior / Calor Mérida (Consumo Alto +30%)'), ('extremo', 'Ola de Calor / Mayo (Consumo Extremo +50%)')], default='calor', max_length=20, verbose_name='Clima / Entorno'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='insumo_agua',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='comercial.insumo', verbose_name='Insumo Agua'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='insumo_alcohol_basico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='comercial.insumo', verbose_name='Alcohol Básico'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='insumo_alcohol_premium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='comercial.insumo', verbose_name='Alcohol Premium'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='insumo_hielo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='comercial.insumo', verbose_name='Insumo Hielo (20kg)'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='insumo_refresco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='comercial.insumo', verbose_name='Insumo Refresco'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='tipo_barra',
            field=models.CharField(choices=[('ninguna', 'Sin Servicio de Alcohol'), ('sin_alcohol', 'Barra Refrescos (Solo Mezcladores)'), ('cocteleria_insumos', 'Barra Coctelería (Solo Insumos, Fruta y Jarabes)'), ('cerveza_refrescos', 'Barra Cerveza y Refrescos'), ('basico', 'Paquete Básico (Botellas 1L - Nacional)'), ('premium', 'Paquete Premium (Botellas 1L - Importado)'), ('premium_cocteleria', '💎 Todo Incluido (Premium + Coctelería + Staff)')], default='ninguna', max_length=20, verbose_name='Tipo Barra'),
        ),
    ]
