# Generated by Django 6.0.1 on 2026-02-10 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0012_cotizacion_clima_alter_cotizacion_insumo_agua_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='tipo_barra',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='incluye_cerveza',
            field=models.BooleanField(default=False, verbose_name='✅ Cerveza'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='incluye_cocteleria',
            field=models.BooleanField(default=False, verbose_name='✅ Coctelería (Mixología)'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='incluye_licor',
            field=models.BooleanField(default=False, verbose_name='✅ Licores (Alcohol)'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='incluye_refrescos',
            field=models.BooleanField(default=True, verbose_name='✅ Refrescos y Mezcladores'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='insumo_alcohol_premium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='comercial.insumo', verbose_name='Alcohol (Base Costo)'),
        ),
    ]
