# Generated by Django 6.0.1 on 2026-02-10 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0013_remove_cotizacion_tipo_barra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='incluye_cocteleria',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='incluye_licor',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='incluye_cocteleria_basica',
            field=models.BooleanField(default=False, verbose_name='Coctelería Básica (Mojitos, Margaritas)'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='incluye_cocteleria_premium',
            field=models.BooleanField(default=False, verbose_name='Coctelería Premium (Carajillos, Autor)'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='incluye_licor_nacional',
            field=models.BooleanField(default=False, verbose_name='Licores Nacionales (Básico)'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='incluye_licor_premium',
            field=models.BooleanField(default=False, verbose_name='Licores Premium (Importado)'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='incluye_cerveza',
            field=models.BooleanField(default=False, verbose_name='Cerveza'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='incluye_refrescos',
            field=models.BooleanField(default=True, verbose_name='Refrescos y Mezcladores'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='insumo_alcohol_premium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='comercial.insumo', verbose_name='Alcohol Premium'),
        ),
    ]
