# Generated by Django 6.0.1 on 2026-02-12 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0014_remove_cotizacion_incluye_cocteleria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='clima',
            field=models.CharField(choices=[('normal', 'Interior / Aire Acondicionado'), ('calor', 'Exterior / Calor Mérida (+20% Liq)'), ('extremo', 'Ola de Calor / Mayo (+40% Liq)')], default='calor', max_length=20, verbose_name='Clima / Entorno'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='incluye_cerveza',
            field=models.BooleanField(default=False, verbose_name='Cerveza (Caguama)'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='incluye_cocteleria_basica',
            field=models.BooleanField(default=False, verbose_name='Coctelería Básica (Mojitos/Marg)'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='incluye_cocteleria_premium',
            field=models.BooleanField(default=False, verbose_name='Mixología / Carajillos'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='incluye_licor_nacional',
            field=models.BooleanField(default=False, verbose_name='Licores Nacionales'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='incluye_licor_premium',
            field=models.BooleanField(default=False, verbose_name='Licores Premium'),
        ),
    ]
