# Generated by Django 6.0.1 on 2026-02-13 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0015_alter_cotizacion_clima_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstanteSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(help_text='Ej: PRECIO_HIELO_20KG', max_length=50, unique=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Constante del Sistema',
            },
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='clima',
            field=models.CharField(choices=[('normal', 'Interior / Aire Acondicionado'), ('calor', 'Exterior / Calor Mérida (+30% Hielo)'), ('extremo', 'Ola de Calor / Mayo (+60% Hielo)')], default='calor', max_length=20, verbose_name='Clima'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='incluye_cocteleria_basica',
            field=models.BooleanField(default=False, verbose_name='Coctelería Básica'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='incluye_cocteleria_premium',
            field=models.BooleanField(default=False, verbose_name='Mixología'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='insumo_hielo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='comercial.insumo', verbose_name='Insumo Hielo'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='crear_como_subproducto',
            field=models.BooleanField(default=False, verbose_name='¿Crear también como Subproducto?'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='factor_rendimiento',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Rendimiento (Divisor)'),
        ),
    ]
