# Generated by Django 6.0.1 on 2026-02-24 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0016_constantesistema_alter_cotizacion_clima_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='presentacion',
            field=models.CharField(blank=True, help_text='Ej: 940ml, Botella 750ml, Bolsa 20kg, Garrafón 20L', max_length=100, verbose_name='Presentación'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='proveedor',
            field=models.CharField(blank=True, help_text="Ej: Costco, Sam's Club, Distribuidora X", max_length=200, verbose_name='Proveedor'),
        ),
        migrations.CreateModel(
            name='PlantillaBarra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('CERVEZA', 'Cerveza'), ('TEQUILA_NAC', 'Tequila Nacional'), ('WHISKY_NAC', 'Whisky Nacional'), ('RON_NAC', 'Ron Nacional'), ('VODKA_NAC', 'Vodka Nacional'), ('TEQUILA_PREM', 'Tequila Premium'), ('WHISKY_PREM', 'Whisky Premium'), ('GIN_PREM', 'Ginebra / Ron Premium'), ('REFRESCO_COLA', 'Refresco de Cola'), ('REFRESCO_TORONJA', 'Refresco de Toronja'), ('AGUA_MINERAL', 'Agua Mineral'), ('AGUA_NATURAL', 'Agua Natural'), ('HIELO', 'Hielo'), ('LIMON', 'Limón'), ('HIERBABUENA', 'Hierbabuena'), ('JARABE', 'Jarabe Natural'), ('FRUTOS_ROJOS', 'Frutos Rojos'), ('CAFE', 'Café Espresso'), ('SERVILLETAS', 'Servilletas / Popotes')], max_length=30, verbose_name='Concepto de Barra')),
                ('grupo', models.CharField(choices=[('ALCOHOL_NACIONAL', 'Licores Nacionales'), ('ALCOHOL_PREMIUM', 'Licores Premium'), ('CERVEZA', 'Cerveza'), ('MEZCLADOR', 'Bebidas y Mezcladores'), ('HIELO', 'Hielo'), ('COCTELERIA', 'Frutas y Verduras'), ('CONSUMIBLE', 'Abarrotes y Consumibles')], help_text='Sección donde aparece en la lista de compras', max_length=30, verbose_name='Grupo en Lista de Compras')),
                ('proporcion', models.DecimalField(decimal_places=2, default=1.0, help_text='Ej: 0.40 = 40% del total de su grupo de alcohol', max_digits=4, verbose_name='Proporción')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición en la lista')),
                ('insumo', models.ForeignKey(help_text='Selecciona el insumo real del catálogo', on_delete=django.db.models.deletion.CASCADE, to='comercial.insumo', verbose_name='Insumo del Catálogo')),
            ],
            options={
                'verbose_name': 'Plantilla de Barra',
                'verbose_name_plural': 'Plantilla de Barra',
                'ordering': ['grupo', 'orden', 'categoria'],
                'unique_together': {('categoria', 'insumo')},
            },
        ),
    ]
