# Generated by Django 6.0.1 on 2026-02-26 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0017_insumo_presentacion_insumo_proveedor_plantillabarra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre / Razón Social')),
                ('contacto', models.CharField(blank=True, max_length=200, verbose_name='Persona de Contacto')),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('notas', models.TextField(blank=True, help_text='Horarios, condiciones de pago, dirección, etc.', verbose_name='Notas')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='insumo',
            name='proveedor_legacy',
            field=models.CharField(blank=True, editable=False, max_length=200, verbose_name='Proveedor (texto antiguo)'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='proveedor',
            field=models.ForeignKey(blank=True, help_text='Selecciona el proveedor de este insumo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='comercial.proveedor', verbose_name='Proveedor'),
        ),
    ]
