# Generated by Django 6.0.1 on 2026-03-10 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0018_proveedor_insumo_proveedor_legacy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='factor_utilidad_barra',
            field=models.DecimalField(decimal_places=2, default=1.3, max_digits=5, verbose_name='Factor Utilidad'),
        ),
    ]
