# Generated by Django 6.0.1 on 2026-03-10 07:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0019_factor_utilidad_barra_130'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada (Compra / Recepción)'), ('SALIDA', 'Salida (Evento / Consumo)'), ('AJUSTE_POS', 'Ajuste Positivo (Inventario Físico)'), ('AJUSTE_NEG', 'Ajuste Negativo (Merma / Daño)'), ('DEVOLUCION', 'Devolución a Proveedor')], max_length=20, verbose_name='Tipo de Movimiento')),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Siempre positiva. El tipo determina si suma o resta.', max_digits=10, verbose_name='Cantidad')),
                ('nota', models.CharField(blank=True, max_length=255, verbose_name='Nota / Motivo')),
                ('stock_anterior', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Stock Anterior')),
                ('stock_posterior', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Stock Posterior')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='cancelada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_canceladas', to=settings.AUTH_USER_MODEL, verbose_name='Cancelada por'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_cancelacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, verbose_name='Motivo de Cancelación'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Alerta cuando el stock baje de este nivel', max_digits=10, verbose_name='Stock Mínimo'),
        ),
        migrations.AddField(
            model_name='pago',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Registro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pago',
            name='notas',
            field=models.CharField(blank=True, max_length=255, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='pago',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_promocional',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('COTIZADA', 'Cotización Enviada'), ('ANTICIPO', 'Anticipo Recibido'), ('CONFIRMADA', 'Venta Confirmada'), ('EN_PREPARACION', 'En Preparación'), ('EJECUTADA', 'Evento Ejecutado'), ('CERRADA', 'Cerrada / Completada'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=20),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='fecha_gasto',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['estado', 'fecha_evento'], name='comercial_c_estado_21bf6e_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['fecha_evento'], name='comercial_c_fecha_e_6cb381_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['fecha_pago'], name='comercial_p_fecha_p_59acad_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['cotizacion', 'fecha_pago'], name='comercial_p_cotizac_44b7e2_idx'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to='comercial.compra', verbose_name='Compra Relacionada'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='cotizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to='comercial.cotizacion', verbose_name='Evento Relacionado'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='comercial.insumo', verbose_name='Insumo'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['insumo', '-created_at'], name='comercial_m_insumo__1e2923_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['tipo', '-created_at'], name='comercial_m_tipo_c4e037_idx'),
        ),
    ]
