# Generated by Django 6.0.1 on 2026-03-11 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0020_movimientoinventario_cotizacion_cancelada_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True, verbose_name='Notas / Condiciones especiales')),
                ('activo', models.BooleanField(default=True)),
                ('cotizacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_pago', to='comercial.cotizacion', verbose_name='Cotización')),
                ('generado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Generado por')),
            ],
            options={
                'verbose_name': 'Plan de Pago',
                'verbose_name_plural': 'Planes de Pago',
            },
        ),
        migrations.CreateModel(
            name='ParcialidadPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='# Parcialidad')),
                ('concepto', models.CharField(help_text='Ej: Anticipo, 2da parcialidad, Liquidación', max_length=100, verbose_name='Concepto')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='% del Total')),
                ('fecha_limite', models.DateField(verbose_name='Fecha Límite de Pago')),
                ('pagada', models.BooleanField(default=False, verbose_name='¿Pagada?')),
                ('fecha_pago_real', models.DateField(blank=True, null=True, verbose_name='Fecha de Pago Real')),
                ('pago_vinculado', models.ForeignKey(blank=True, help_text='Vincular con el pago real cuando se reciba', null=True, on_delete=django.db.models.deletion.SET_NULL, to='comercial.pago', verbose_name='Pago Registrado')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcialidades', to='comercial.planpago', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Parcialidad',
                'verbose_name_plural': 'Parcialidades',
                'ordering': ['numero'],
                'unique_together': {('plan', 'numero')},
            },
        ),
    ]
