# Generated by Django 6.0.1 on 2026-03-12 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0021_planpago_parcialidadpago'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimientoinventario',
            options={'ordering': ['-created_at'], 'verbose_name': 'Inventario', 'verbose_name_plural': 'Inventarios'},
        ),
    ]
