# Generated by Django 6.0.1 on 2026-03-12 05:13

import cloudinary_storage.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0022_alter_movimientoinventario_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='archivo_contrato',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='contratos_docx/', verbose_name='Contrato (.docx)'),
        ),
        migrations.CreateModel(
            name='ContratoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True, verbose_name='Número de Contrato')),
                ('tipo_servicio', models.CharField(choices=[('EVENTO', 'Evento'), ('PASADIA', 'Pasadía'), ('HOSPEDAJE', 'Hospedaje')], default='EVENTO', max_length=20)),
                ('deposito_garantia', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Depósito en Garantía (MXN)')),
                ('archivo', models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='contratos_docx/', verbose_name='Archivo .docx')),
                ('generado_en', models.DateTimeField(auto_now_add=True)),
                ('enviado_email', models.BooleanField(default=False)),
                ('notas', models.TextField(blank=True)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='comercial.cotizacion')),
                ('generado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contrato de Servicio',
                'verbose_name_plural': 'Contratos de Servicio',
                'ordering': ['-generado_en'],
            },
        ),
    ]
