# Generated by Django 6.0.1 on 2026-03-12 07:14

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0023_cotizacion_archivo_contrato_contratoservicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratoservicio',
            name='archivo',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='contratos_pdf/', verbose_name='Archivo PDF'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='archivo_contrato',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='contratos_pdf/', verbose_name='Contrato PDF'),
        ),
    ]
