# Generated by Django 6.0.1 on 2026-03-16 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0024_alter_contratoservicio_archivo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contratoservicio',
            options={'ordering': ['-generado_en'], 'verbose_name': 'Contrato', 'verbose_name_plural': 'Contratos'},
        ),
        migrations.CreateModel(
            name='RecordatorioPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('ENVIADO', 'Enviado'), ('FALLIDO', 'Fallido'), ('OMITIDO', 'Omitido (sin teléfono)')], default='ENVIADO', max_length=10)),
                ('mensaje_enviado', models.TextField(blank=True, verbose_name='Mensaje enviado')),
                ('respuesta_api', models.TextField(blank=True, verbose_name='Respuesta API WhatsApp')),
                ('error_detalle', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parcialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to='comercial.parcialidadpago', verbose_name='Parcialidad')),
            ],
            options={
                'verbose_name': 'Recordatorio de Pago',
                'verbose_name_plural': 'Recordatorios de Pago',
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
