# Generated by Django 6.0.3 on 2026-03-20 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0026_add_solicitar_factura"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PortalCliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True,
                        help_text="Se genera automáticamente. No editar.",
                        max_length=64,
                        unique=True,
                        verbose_name="Token de Acceso",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(default=True, verbose_name="Portal Activo"),
                ),
                (
                    "visitas",
                    models.PositiveIntegerField(default=0, verbose_name="Visitas"),
                ),
                ("ultima_visita", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cotizacion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal",
                        to="comercial.cotizacion",
                        verbose_name="Cotización",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Portal del Cliente",
                "verbose_name_plural": "Portales de Clientes",
            },
        ),
    ]
