# Generated by Django 6.0.1 on 2026-03-27 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0027_portalcliente'),
        ('contabilidad', '0006_add_rfc_razon_social_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='unidad_negocio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.unidadnegocio', verbose_name='Unidad de Negocio'),
        ),
    ]
