# Generated by Django 5.2.12 on 2026-04-06 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0028_add_unidad_negocio_compra"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cotizacion",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="comercial.cliente"
            ),
        ),
    ]
