# Generated by Django 5.2.12 on 2026-04-07 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0029_alter_cotizacion_cliente"),
    ]

    operations = [
        migrations.AddField(
            model_name="pago",
            name="tipo",
            field=models.CharField(
                choices=[("INGRESO", "Ingreso"), ("REEMBOLSO", "Reembolso")],
                default="INGRESO",
                max_length=10,
                verbose_name="Tipo",
            ),
        ),
    ]
