# Generated by Django 5.2.12 on 2026-04-07 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0030_pago_tipo"),
        ("nomina", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Espacio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("JARDIN", "Jardín"),
                            ("TERRAZA", "Terraza"),
                            ("SALON", "Salón"),
                            ("PALAPA", "Palapa"),
                            ("ALBERCA", "Alberca"),
                            ("OTRO", "Otro"),
                        ],
                        default="OTRO",
                        max_length=20,
                    ),
                ),
                (
                    "capacidad_max",
                    models.PositiveIntegerField(
                        default=50, verbose_name="Capacidad máxima"
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Espacio",
                "verbose_name_plural": "Espacios",
                "ordering": ["nombre"],
            },
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="tipo_servicio",
            field=models.CharField(
                choices=[
                    ("EVENTO", "Evento"),
                    ("PASADIA", "Pasadía"),
                    ("HOSPEDAJE", "Hospedaje"),
                ],
                default="EVENTO",
                max_length=15,
                verbose_name="Tipo de servicio",
            ),
        ),
        migrations.CreateModel(
            name="AsignacionPersonal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("COORDINADOR", "Coordinador"),
                            ("BARMAN", "Barman"),
                            ("MESERO", "Mesero"),
                            ("LIMPIEZA", "Limpieza"),
                            ("SEGURIDAD", "Seguridad"),
                            ("COCINA", "Cocina"),
                            ("OTRO", "Otro"),
                        ],
                        default="OTRO",
                        max_length=20,
                    ),
                ),
                ("fecha", models.DateField()),
                ("hora_inicio", models.TimeField()),
                ("hora_fin", models.TimeField()),
                ("notas", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cotizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_asignado",
                        to="comercial.cotizacion",
                    ),
                ),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asignaciones",
                        to="nomina.empleado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asignación de personal",
                "verbose_name_plural": "Asignaciones de personal",
                "indexes": [
                    models.Index(
                        fields=["empleado", "fecha"],
                        name="comercial_a_emplead_20ff69_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AsignacionEspacio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("hora_inicio", models.TimeField()),
                ("hora_fin", models.TimeField()),
                ("notas", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cotizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="espacios_asignados",
                        to="comercial.cotizacion",
                    ),
                ),
                (
                    "espacio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asignaciones",
                        to="comercial.espacio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asignación de espacio",
                "verbose_name_plural": "Asignaciones de espacios",
                "indexes": [
                    models.Index(
                        fields=["espacio", "fecha"],
                        name="comercial_a_espacio_fd9823_idx",
                    )
                ],
            },
        ),
    ]
