# Generated by Django 5.2.13 on 2026-04-10 03:04

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "comercial",
            "0031_espacio_cotizacion_tipo_servicio_asignacionpersonal_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaBarra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "clave",
                    models.CharField(
                        help_text="Identificador interno. Ej: TEQUILA_NAC",
                        max_length=40,
                        unique=True,
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, verbose_name="Nombre para mostrar"
                    ),
                ),
                (
                    "proporcion_default",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        help_text="0.40 = 40% del total de botellas/unidades de su grupo",
                        max_digits=4,
                        verbose_name="Proporción dentro del grupo",
                    ),
                ),
                (
                    "unidad_compra",
                    models.CharField(
                        default="Botellas",
                        help_text="Unidad para lista de compras: Botellas, Cajas, Bolsas, Kg, etc.",
                        max_length=30,
                    ),
                ),
                (
                    "unidad_contenido",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        help_text="Litros/kg por unidad de compra. Ej: botella 2.5L = 2.50",
                        max_digits=6,
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Categoría de Barra",
                "verbose_name_plural": "Categorías de Barra",
                "ordering": ["grupo", "orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="GrupoBarra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "clave",
                    models.CharField(
                        help_text="Identificador interno. Ej: ALCOHOL_NACIONAL",
                        max_length=40,
                        unique=True,
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, verbose_name="Nombre para mostrar"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#666666",
                        help_text="Color hex para la UI. Ej: #e67e22",
                        max_length=7,
                    ),
                ),
                (
                    "peso_calculadora",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Peso relativo para distribución de tragos. Ej: cerveza=55, nacional=35. 0 = no participa en cálculo de tragos.",
                        verbose_name="Peso en calculadora",
                    ),
                ),
                (
                    "campo_cotizacion",
                    models.CharField(
                        blank=True,
                        help_text="Campo booleano en Cotizacion que activa este grupo. Ej: incluye_cerveza, incluye_licor_nacional",
                        max_length=50,
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Grupo de Barra",
                "verbose_name_plural": "Grupos de Barra",
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.AddField(
            model_name="plantillabarra",
            name="es_default",
            field=models.BooleanField(
                default=False,
                help_text="Insumo preferido para cálculo de costo. Solo uno por categoría.",
            ),
        ),
        migrations.AlterField(
            model_name="plantillabarra",
            name="categoria",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CERVEZA", "Cerveza"),
                    ("TEQUILA_NAC", "Tequila Nacional"),
                    ("WHISKY_NAC", "Whisky Nacional"),
                    ("RON_NAC", "Ron Nacional"),
                    ("VODKA_NAC", "Vodka Nacional"),
                    ("TEQUILA_PREM", "Tequila Premium"),
                    ("WHISKY_PREM", "Whisky Premium"),
                    ("GIN_PREM", "Ginebra / Ron Premium"),
                    ("REFRESCO_COLA", "Refresco de Cola"),
                    ("REFRESCO_TORONJA", "Refresco de Toronja"),
                    ("AGUA_MINERAL", "Agua Mineral"),
                    ("AGUA_NATURAL", "Agua Natural"),
                    ("HIELO", "Hielo"),
                    ("LIMON", "Limón"),
                    ("HIERBABUENA", "Hierbabuena"),
                    ("JARABE", "Jarabe Natural"),
                    ("FRUTOS_ROJOS", "Frutos Rojos"),
                    ("CAFE", "Café Espresso"),
                    ("SERVILLETAS", "Servilletas / Popotes"),
                ],
                default="",
                max_length=30,
                verbose_name="Concepto de Barra",
            ),
        ),
        migrations.AlterField(
            model_name="plantillabarra",
            name="grupo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ALCOHOL_NACIONAL", "Licores Nacionales"),
                    ("ALCOHOL_PREMIUM", "Licores Premium"),
                    ("CERVEZA", "Cerveza"),
                    ("MEZCLADOR", "Bebidas y Mezcladores"),
                    ("HIELO", "Hielo"),
                    ("COCTELERIA", "Frutas y Verduras"),
                    ("CONSUMIBLE", "Abarrotes y Consumibles"),
                ],
                default="",
                help_text="Sección donde aparece en la lista de compras",
                max_length=30,
                verbose_name="Grupo en Lista de Compras",
            ),
        ),
        migrations.AlterField(
            model_name="plantillabarra",
            name="proporcion",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                help_text="Proporción de este insumo dentro de su categoría. Si hay 2 tequilas, cada uno podría ser 0.50.",
                max_digits=4,
                verbose_name="Proporción",
            ),
        ),
        migrations.AddField(
            model_name="plantillabarra",
            name="categoria_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plantillas",
                to="comercial.categoriabarra",
                verbose_name="Categoría de Barra",
            ),
        ),
        migrations.AddField(
            model_name="categoriabarra",
            name="grupo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categorias",
                to="comercial.grupobarra",
                verbose_name="Grupo",
            ),
        ),
    ]
