# Generated by Django 5.1.15 on 2026-06-24 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0041_rename_platillo_botanas"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="imagenlanding",
            options={
                "ordering": ["seccion", "orden"],
                "verbose_name": "Imagen de la página web",
                "verbose_name_plural": "Página Web — Imágenes",
            },
        ),
        migrations.AlterModelOptions(
            name="testimoniolanding",
            options={
                "ordering": ["orden"],
                "verbose_name": "Testimonio de cliente",
                "verbose_name_plural": "Página Web — Testimonios",
            },
        ),
        migrations.AddField(
            model_name="producto",
            name="precio_venta_fijo",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Si se define (>0), sobreescribe el cálculo costo×margen. Para rentas de precio fijo (mobiliario).",
                max_digits=10,
                null=True,
                verbose_name="Precio de venta fijo",
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="estado",
            field=models.CharField(
                choices=[
                    ("BORRADOR", "Borrador"),
                    ("COTIZADA", "Cotización Enviada"),
                    ("CONFIRMADA", "Venta Confirmada"),
                    ("EJECUTADA", "Evento Ejecutado"),
                    ("CERRADA", "Cerrada / Completada"),
                    ("CANCELADA", "Cancelada"),
                ],
                default="BORRADOR",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="es_upgrade",
            field=models.BooleanField(
                default=False,
                help_text="Marca si este producto amplía a otros (sus subproductos base no se duplican en inventario)",
                verbose_name="¿Es un upgrade?",
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="grupo_cotizador",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ENTRETENIMIENTO", "Entretenimiento"),
                    ("COMIDA", "Alimentos y Bebidas"),
                    ("MOBILIARIO", "Mobiliario"),
                    ("DECORACION", "Decoración"),
                    ("INFANTIL", "Infantil"),
                    ("OTRO", "Otros"),
                ],
                max_length=20,
                verbose_name="Grupo en cotizador",
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="hereda_inventario_de",
            field=models.ManyToManyField(
                blank=True,
                help_text="Productos base cuyos subproductos NO se duplicarán al calcular inventario",
                related_name="upgrades",
                to="comercial.producto",
                verbose_name="Hereda inventario de",
            ),
        ),
    ]
