# Generated by Django 5.1.15 on 2026-06-24 23:56

from decimal import Decimal
from django.db import migrations

# PENDIENTE: Elian confirma precios.
# Mobiliario: precio por SET (1 mesa + 10 sillas + mantel).
# Montaje De Lujo: precio POR PERSONA.
PRECIOS = {
    'Mobiliario Tiffany':   Decimal('0.00'),   # ← precio por set
    'Mobiliario Crossback': Decimal('0.00'),   # ← precio por set
    'Mobiliario Vintage':   Decimal('0.00'),   # ← precio por set
    'Montaje De Lujo':      Decimal('0.00'),   # ← precio por persona
}

CONFIG = {
    'Mobiliario Tiffany': {
        'grupo': 'MOBILIARIO', 'factor': 10, 'es_upgrade': False, 'orden': 1,
        'desc': 'Mesa con 10 sillas Tiffany y mantel',
    },
    'Mobiliario Crossback': {
        'grupo': 'MOBILIARIO', 'factor': 10, 'es_upgrade': False, 'orden': 2,
        'desc': 'Mesa con 10 sillas crossback y mantel',
    },
    'Mobiliario Vintage': {
        'grupo': 'MOBILIARIO', 'factor': 10, 'es_upgrade': False, 'orden': 3,
        'desc': 'Mesa de madera con 10 sillas crossback',
    },
    'Montaje De Lujo': {
        'grupo': 'DECORACION', 'factor': 1, 'es_upgrade': True, 'orden': 1,
        'desc': 'Vajilla, bajo plato premium, copas y cubiertos dorados (por persona)',
    },
}


def upsert_productos(apps, schema_editor):
    Producto = apps.get_model('comercial', 'Producto')
    for nombre, cfg in CONFIG.items():
        precio = PRECIOS[nombre]
        config_cotizador = {
            'grupo_cotizador': cfg['grupo'],
            'cotizador_evento': True,
            'cantidad_por_persona': True,
            'factor_personas': cfg['factor'],
            'es_upgrade': cfg['es_upgrade'],
            'descripcion_corta': cfg['desc'],
            'orden_cotizador': cfg['orden'],
            'visible_cotizador': precio > 0,  # guardrail: nunca exponer en $0
        }
        obj, creado = Producto.objects.get_or_create(
            nombre=nombre,
            defaults={**config_cotizador, 'precio_venta_fijo': precio, 'margen_ganancia': Decimal('0.30')},
        )
        if not creado:
            for k, v in config_cotizador.items():
                setattr(obj, k, v)
            if precio > 0:
                obj.precio_venta_fijo = precio
            obj.save()


def revertir(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0042_alter_imagenlanding_options_and_more"),
    ]

    operations = [
        migrations.RunPython(upsert_productos, revertir),
    ]
