# Generated by Django 5.1.15 on 2026-07-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0044_recalcular_totales_iva"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="grupo_cotizador",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PAQUETE", "Paquetes"),
                    ("ENTRETENIMIENTO", "Entretenimiento"),
                    ("COMIDA", "Alimentos y Bebidas"),
                    ("MOBILIARIO", "Mobiliario"),
                    ("DECORACION", "Decoración"),
                    ("INFANTIL", "Infantil"),
                    ("OTRO", "Otros"),
                ],
                max_length=20,
                verbose_name="Grupo en cotizador",
            ),
        ),
    ]
