# Generated by Django 5.1.15 on 2026-07-04 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0045_alter_producto_grupo_cotizador"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Temporada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                ("fecha_inicio", models.DateField(verbose_name="Fecha inicio")),
                ("fecha_fin", models.DateField(verbose_name="Fecha fin")),
                ("anio", models.IntegerField(db_index=True, verbose_name="Año")),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Temporada",
                "verbose_name_plural": "Descuentos — Temporadas",
                "ordering": ["-anio", "fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="TipoEvento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=60, unique=True, verbose_name="Tipo de evento"
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0, verbose_name="Orden")),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Tipo de Evento",
                "verbose_name_plural": "Catálogo — Tipos de Evento",
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Descuento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "tipo_valor",
                    models.CharField(
                        choices=[
                            ("PORCENTAJE", "Porcentaje (%)"),
                            ("MONTO_FIJO", "Monto fijo (MXN)"),
                        ],
                        default="PORCENTAJE",
                        max_length=12,
                        verbose_name="Tipo de valor",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Si es porcentaje, entre 0 y 100. Si es monto fijo, en MXN.",
                        max_digits=10,
                        verbose_name="Valor",
                    ),
                ),
                (
                    "modo",
                    models.CharField(
                        choices=[("MANUAL", "Manual"), ("AUTOMATICO", "Automático")],
                        default="MANUAL",
                        max_length=12,
                        verbose_name="Modo de aplicación",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "monto_minimo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="El subtotal de la cotización debe ser mayor o igual a este monto.",
                        max_digits=10,
                        null=True,
                        verbose_name="Monto mínimo (subtotal)",
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(
                        blank=True, null=True, verbose_name="Vigencia desde"
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateField(
                        blank=True, null=True, verbose_name="Vigencia hasta"
                    ),
                ),
                (
                    "tipos_servicio",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de: EVENTO, PASADIA, ARRENDAMIENTO. Vacío = todos.",
                        verbose_name="Tipos de servicio",
                    ),
                ),
                (
                    "acumulable",
                    models.BooleanField(
                        default=False,
                        help_text="Por default NO. Si es acumulable se suma aparte del ganador no-acumulable.",
                        verbose_name="¿Acumulable?",
                    ),
                ),
                (
                    "prioridad",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Mayor prioridad gana entre no-acumulables en competencia.",
                        verbose_name="Prioridad",
                    ),
                ),
                (
                    "max_usos",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Tope de aplicaciones. Vacío = ilimitado.",
                        null=True,
                        verbose_name="Máximo de usos",
                    ),
                ),
                (
                    "usos",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Usos aplicados"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="descuentos_creados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="descuentos_actualizados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
                (
                    "temporada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="descuentos",
                        to="comercial.temporada",
                        verbose_name="Temporada",
                    ),
                ),
                (
                    "tipos_evento",
                    models.ManyToManyField(
                        blank=True,
                        related_name="descuentos",
                        to="comercial.tipoevento",
                        verbose_name="Tipos de evento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Descuento",
                "verbose_name_plural": "Descuentos",
                "ordering": ["-prioridad", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="DescuentoAplicado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monto_aplicado",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Monto aplicado (MXN)",
                    ),
                ),
                (
                    "porcentaje_equivalente",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Porcentaje que representa el monto sobre el subtotal, para reporting.",
                        max_digits=6,
                        verbose_name="% equivalente",
                    ),
                ),
                (
                    "modo_aplicacion",
                    models.CharField(
                        choices=[("MANUAL", "Manual"), ("AUTOMATICO", "Automático")],
                        max_length=12,
                        verbose_name="Modo de aplicación",
                    ),
                ),
                (
                    "fecha_aplicacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de aplicación"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("notas", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "aplicado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="descuentos_aplicados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aplicado por",
                    ),
                ),
                (
                    "cotizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="descuentos_aplicados",
                        to="comercial.cotizacion",
                        verbose_name="Cotización",
                    ),
                ),
                (
                    "descuento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aplicaciones",
                        to="comercial.descuento",
                        verbose_name="Descuento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Descuento Aplicado",
                "verbose_name_plural": "Descuentos — Aplicados (auditoría)",
                "ordering": ["-fecha_aplicacion"],
            },
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="tipo_evento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cotizaciones",
                to="comercial.tipoevento",
                verbose_name="Tipo de evento",
            ),
        ),
    ]
