# Generated by Django 5.1.15 on 2026-07-04 01:23

from django.db import migrations

# Catálogo base de tipos de evento. Idempotente: get_or_create por nombre.
TIPOS_EVENTO = [
    'Boda',
    'XV Años',
    'Graduación',
    'Cumpleaños',
    'Bautizo',
    'Primera Comunión',
    'Aniversario',
    'Corporativo',
    'Otro',
]


def seed_tipos_evento(apps, schema_editor):
    TipoEvento = apps.get_model('comercial', 'TipoEvento')
    for orden, nombre in enumerate(TIPOS_EVENTO, start=1):
        TipoEvento.objects.get_or_create(
            nombre=nombre,
            defaults={'orden': orden, 'activo': True},
        )


def revertir(apps, schema_editor):
    # No se borran: pueden estar referenciados por cotizaciones/descuentos.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0046_temporada_tipoevento_descuento_descuentoaplicado_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_tipos_evento, revertir),
    ]
