# Generated by Django 5.1.15 on 2026-07-07 19:56

from decimal import Decimal
from django.db import migrations

# Precios reales confirmados por Elian (2026-07-07). Reemplaza los placeholders
# en $0.00 sembrados en la migración 0043. Precio por SET (1 mesa + 10 sillas
# + mantel). "Montaje De Lujo" NO se toca aquí: sigue pendiente de precio.
PRECIOS = {
    'Mobiliario Tiffany': Decimal('600.00'),
    'Mobiliario Crossback': Decimal('950.00'),
    'Mobiliario Vintage': Decimal('1150.00'),
}


def cargar_precios(apps, schema_editor):
    Producto = apps.get_model('comercial', 'Producto')
    for nombre, precio in PRECIOS.items():
        Producto.objects.filter(nombre=nombre).update(
            precio_venta_fijo=precio,
            visible_cotizador=True,  # guardrail: ya no está en $0, se puede mostrar
        )


def revertir(apps, schema_editor):
    Producto = apps.get_model('comercial', 'Producto')
    Producto.objects.filter(nombre__in=PRECIOS.keys()).update(
        precio_venta_fijo=Decimal('0.00'),
        visible_cotizador=False,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0047_seed_tipos_evento"),
    ]

    operations = [
        migrations.RunPython(cargar_precios, revertir),
    ]
