# Generated by Django 5.1.15 on 2026-07-07 19:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0048_cargar_precios_mobiliario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="margen_ganancia",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.30"), max_digits=4
            ),
        ),
    ]
