# Generated by Django 5.1.15 on 2026-07-07 20:03

from django.db import migrations

# Se elimina por instrucción explícita de Elian. El producto se sembró en la
# migración 0043 con precio_venta_fijo=0.00 (pendiente de confirmar) y nunca
# llegó a usarse en ninguna cotización real ni tiene precio definido.


def eliminar(apps, schema_editor):
    Producto = apps.get_model('comercial', 'Producto')
    Producto.objects.filter(nombre='Montaje De Lujo').delete()


def revertir(apps, schema_editor):
    # No se recrea: fue un alta preliminar sin uso real, no auditoría de negocio.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0049_alter_producto_margen_ganancia"),
    ]

    operations = [
        migrations.RunPython(eliminar, revertir),
    ]
