# Generated by Django 5.1.15 on 2026-07-10 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0050_eliminar_montaje_de_lujo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="descuentoaplicado",
            options={
                "ordering": ["-fecha_aplicacion"],
                "verbose_name": "Descuento Aplicado",
                "verbose_name_plural": "Descuentos Aplicados",
            },
        ),
        migrations.AlterModelOptions(
            name="temporada",
            options={
                "ordering": ["-anio", "fecha_inicio"],
                "verbose_name": "Temporada",
                "verbose_name_plural": "Temporadas",
            },
        ),
        migrations.AlterModelOptions(
            name="tipoevento",
            options={
                "ordering": ["orden", "nombre"],
                "verbose_name": "Tipo de Evento",
                "verbose_name_plural": "Tipos de Evento",
            },
        ),
    ]
