# Generated by Django 5.1.15 on 2026-07-10 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0051_alter_descuentoaplicado_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="descuento",
            options={
                "ordering": ["-prioridad", "nombre"],
                "verbose_name": "Descuento",
                "verbose_name_plural": "Reglas de Descuento",
            },
        ),
        migrations.AlterModelOptions(
            name="descuentoaplicado",
            options={
                "ordering": ["-fecha_aplicacion"],
                "verbose_name": "Descuento Aplicado",
                "verbose_name_plural": "Aplicados (auditoría)",
            },
        ),
        migrations.AlterModelOptions(
            name="espaciolanding",
            options={
                "ordering": ["orden"],
                "verbose_name": "Espacio",
                "verbose_name_plural": "Espacios (Página Web)",
            },
        ),
        migrations.AlterModelOptions(
            name="imagenlanding",
            options={
                "ordering": ["seccion", "orden"],
                "verbose_name": "Imagen de la página web",
                "verbose_name_plural": "Imágenes",
            },
        ),
        migrations.AlterModelOptions(
            name="preguntafrecuente",
            options={
                "ordering": ["orden"],
                "verbose_name": "Pregunta frecuente",
                "verbose_name_plural": "Preguntas Frecuentes",
            },
        ),
        migrations.AlterModelOptions(
            name="testimoniolanding",
            options={
                "ordering": ["orden"],
                "verbose_name": "Testimonio de cliente",
                "verbose_name_plural": "Testimonios",
            },
        ),
    ]
