# Generated by Django 5.1.15 on 2026-07-13 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0052_alter_descuento_options_and_more"),
        ("contabilidad", "0009_saldoapertura_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="compra",
            name="cuenta_pago",
            field=models.ForeignKey(
                blank=True,
                help_text="De cuál de las cuentas débito salió este pago. Sin este dato la póliza queda en BORRADOR y no se aplica.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="compras_pagadas",
                to="contabilidad.cuentabancaria",
                verbose_name="Cuenta de pago",
            ),
        ),
        migrations.AlterField(
            model_name="compra",
            name="unidad_negocio",
            field=models.ForeignKey(
                blank=True,
                help_text="¿Este gasto es de Eventos (QUINTA) o de Hospedaje (AIRBNB)? Sin este dato la póliza queda en BORRADOR y no se aplica.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="compras",
                to="contabilidad.unidadnegocio",
                verbose_name="Unidad de negocio",
            ),
        ),
    ]
