# Generated by Django 5.1.15 on 2026-07-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0053_compra_cuenta_pago_alter_compra_unidad_negocio"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagenlanding",
            name="mostrar_en_galeria",
            field=models.BooleanField(
                default=False,
                help_text="Además de su propia sección, muestra esta imagen en la Galería de fotos.",
                verbose_name="Mostrar también en Galería general",
            ),
        ),
    ]
