# Generated by Django 5.1.15 on 2026-07-15 15:46

from django.db import migrations, models


def marcar_existentes_como_visibles_en_galeria(apps, schema_editor):
    """Los registros creados antes de este cambio se quedaron en False
    (default anterior); se ponen en True para igualar el nuevo default."""
    ImagenLanding = apps.get_model('comercial', 'ImagenLanding')
    ImagenLanding.objects.filter(mostrar_en_galeria=False).update(mostrar_en_galeria=True)


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0054_imagenlanding_mostrar_en_galeria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagenlanding",
            name="mostrar_en_galeria",
            field=models.BooleanField(
                default=True,
                help_text="Además de su propia sección, muestra esta imagen en la Galería de fotos.",
                verbose_name="Mostrar también en Galería general",
            ),
        ),
        migrations.RunPython(marcar_existentes_como_visibles_en_galeria, migrations.RunPython.noop),
    ]
