# Generated by Django 5.1.15 on 2026-07-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0055_alter_imagenlanding_mostrar_en_galeria"),
    ]

    operations = [
        migrations.AddField(
            model_name="pago",
            name="concepto",
            field=models.CharField(
                choices=[
                    ("VENTA", "Pago de la venta"),
                    ("EXTRA", "Ingreso adicional (propina, comisión, etc.)"),
                ],
                default="VENTA",
                help_text="'Ingreso adicional' no cuenta para el saldo de la cotización ni bloquea su cierre — úsalo para propinas, comisiones u otros cobros ligados al cliente/evento pero ajenos al precio de la venta.",
                max_length=10,
                verbose_name="Concepto",
            ),
        ),
    ]
