# Generated by Django 5.1.15 on 2026-07-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0056_pago_concepto"),
    ]

    operations = [
        migrations.AddField(
            model_name="compra",
            name="es_deducible",
            field=models.BooleanField(
                default=True,
                help_text="Se desactiva automáticamente si no hay factura/XML cargado (ej. compras en el extranjero, sin CFDI mexicano). Un gasto sin comprobante fiscal no es deducible de impuestos, pero sí se registra en la contabilidad.",
                verbose_name="Deducible (con CFDI)",
            ),
        ),
    ]
