# Generated by Django 6.0.7 on 2026-07-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0059_alter_cliente_regimen_fiscal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cotizacion",
            name="incluye_refrescos",
            field=models.BooleanField(
                default=False, verbose_name="Refrescos y Mezcladores"
            ),
        ),
    ]
