# Generated by Django 6.0.7 on 2026-07-23 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0060_incluye_refrescos_default_false"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenpayTransaccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "openpay_id",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        unique=True,
                        verbose_name="ID de transacción en Openpay",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        help_text="ej. charge.succeeded, charge.failed",
                        max_length=50,
                        verbose_name="Tipo de evento",
                    ),
                ),
                (
                    "estado_openpay",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        verbose_name="Estado reportado por Openpay",
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "payload_crudo",
                    models.JSONField(verbose_name="JSON recibido de Openpay"),
                ),
                ("procesado", models.BooleanField(default=False)),
                ("error_detalle", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cotizacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transacciones_openpay",
                        to="comercial.cotizacion",
                    ),
                ),
                (
                    "pago",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transaccion_openpay",
                        to="comercial.pago",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transacción Openpay",
                "verbose_name_plural": "Transacciones Openpay",
                "ordering": ["-created_at"],
            },
        ),
    ]
