# Generated by Django 6.0.7 on 2026-07-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0061_openpaytransaccion"),
    ]

    operations = [
        migrations.AddField(
            model_name="openpaytransaccion",
            name="metodo",
            field=models.CharField(
                blank=True,
                help_text="card, store o bank_account",
                max_length=20,
                verbose_name="Método",
            ),
        ),
        migrations.AddField(
            model_name="openpaytransaccion",
            name="referencia_pago",
            field=models.CharField(
                blank=True,
                help_text="Solo aplica a efectivo/SPEI",
                max_length=100,
                verbose_name="Referencia/CLABE mostrada al cliente",
            ),
        ),
        migrations.AlterField(
            model_name="openpaytransaccion",
            name="event_type",
            field=models.CharField(
                blank=True,
                help_text="ej. charge.succeeded, charge.failed",
                max_length=50,
                verbose_name="Tipo de evento",
            ),
        ),
    ]
