# Generated by Django 6.0.7 on 2026-07-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0062_openpaytransaccion_metodo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="openpaytransaccion",
            name="autorizacion",
            field=models.CharField(
                blank=True,
                help_text="Número de autorización bancaria reportado por Openpay",
                max_length=30,
                verbose_name="Autorización",
            ),
        ),
    ]
