# Generated by Django 6.0.7 on 2026-07-24 17:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0064_backfill_openpaytransaccion_autorizacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="pago",
            name="comision_tpv",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Comisión que el banco descuenta antes de depositar (IVA incluido). El estado de cuenta nunca la muestra por separado — se captura a mano del recibo de la terminal o del reporte de Netpay.",
                max_digits=10,
                null=True,
                verbose_name="Comisión de terminal (TPV)",
            ),
        ),
    ]
