# Generated by Django 6.0.7 on 2026-08-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0067_itemcotizacion_precio_unitario_sin_iva"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compra",
            name="archivo_pdf",
            field=models.FileField(blank=True, null=True, upload_to="pdf_compras/"),
        ),
        migrations.AlterField(
            model_name="compra",
            name="archivo_xml",
            field=models.FileField(blank=True, null=True, upload_to="xml_compras/"),
        ),
        migrations.AlterField(
            model_name="contratoservicio",
            name="archivo",
            field=models.FileField(
                upload_to="contratos_pdf/", verbose_name="Archivo PDF"
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="archivo_contrato",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="contratos_pdf/",
                verbose_name="Contrato PDF",
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="archivo_pdf",
            field=models.FileField(
                blank=True, null=True, upload_to="cotizaciones_pdf/"
            ),
        ),
        migrations.AlterField(
            model_name="gasto",
            name="archivo_pdf",
            field=models.FileField(blank=True, null=True, upload_to="pdf_gastos/"),
        ),
        migrations.AlterField(
            model_name="gasto",
            name="archivo_xml",
            field=models.FileField(blank=True, null=True, upload_to="xml_gastos/"),
        ),
    ]
