# Generated by Django 6.1 on 2026-08-12 03:19

import core_erp.storages_qkt
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0069_tabla_cache"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contratoservicio",
            name="archivo",
            field=models.FileField(
                storage=core_erp.storages_qkt.storage_privado,
                upload_to="contratos_pdf/",
                verbose_name="Archivo PDF",
            ),
        ),
    ]
