# Generated by Django 6.1 on 2026-08-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0072_producto_rol_cotizador"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="fecha_salida",
            field=models.DateField(
                blank=True,
                help_text="Solo aplica a HOSPEDAJE: fecha de checkout, EXCLUSIVA (la última noche ocupada es fecha_salida - 1 día), mismo criterio que ReservaAirbnb.fecha_fin. Vacía en cualquier otro tipo de servicio.",
                null=True,
                verbose_name="Fecha de salida (checkout)",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="cotizador_hospedaje",
            field=models.BooleanField(
                default=False, verbose_name="Disponible para Hospedaje"
            ),
        ),
        migrations.AlterField(
            model_name="contratoservicio",
            name="tipo_servicio",
            field=models.CharField(
                choices=[
                    ("EVENTO", "Evento"),
                    ("PASADIA", "Pasadía"),
                    ("ARRENDAMIENTO", "Arrendamiento de Mobiliario"),
                    ("HOSPEDAJE", "Hospedaje"),
                ],
                default="EVENTO",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="tipo_servicio",
            field=models.CharField(
                choices=[
                    ("EVENTO", "Evento"),
                    ("PASADIA", "Pasadía"),
                    ("ARRENDAMIENTO", "Arrendamiento de Mobiliario"),
                    ("HOSPEDAJE", "Hospedaje"),
                ],
                default="EVENTO",
                max_length=15,
                verbose_name="Tipo de servicio",
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="rol_cotizador",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BASE_EVENTO", "Base — Evento (se agrega solo)"),
                    ("BASE_PASADIA", "Base — Pasadía (se agrega solo)"),
                    ("HORA_EXTRA", "Hora extra de arrendamiento"),
                    (
                        "HABITACION_HOSPEDAJE",
                        "Habitación de Hospedaje (selección múltiple)",
                    ),
                ],
                db_index=True,
                help_text="Producto que el cotizador agrega SOLO al elegir el servicio (el arrendamiento de la quinta), o que se elige en su propio paso dedicado en vez de la lista de extras (las habitaciones de Hospedaje, selección múltiple, cantidad = noches). No se ofrece como extra: si el cliente pudiera marcarlo ahí también, se cobraría dos veces. Vacío = extra normal.",
                max_length=20,
                verbose_name="Rol en el cotizador",
            ),
        ),
    ]
