# Generated by Django 6.1 on 2026-08-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0073_hospedaje"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuiaTipoServicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_servicio",
                    models.CharField(
                        choices=[
                            ("EVENTO", "Evento"),
                            ("PASADIA", "Pasadía"),
                            ("HOSPEDAJE", "Hospedaje"),
                        ],
                        max_length=15,
                        unique=True,
                        verbose_name="Tipo de servicio",
                    ),
                ),
                (
                    "archivo_pdf",
                    models.FileField(
                        upload_to="guias_servicio/", verbose_name="PDF de la guía"
                    ),
                ),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Guía por tipo de servicio",
                "verbose_name_plural": "Guías por tipo de servicio",
            },
        ),
    ]
