# Generated by Django 6.1 on 2026-08-17 22:44

import core_erp.storages_qkt
import core_erp.validadores_archivos
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0073_hospedaje"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compra",
            name="archivo_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="pdf_compras/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    ),
                    core_erp.validadores_archivos.validar_firma_pdf,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="compra",
            name="archivo_xml",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="xml_compras/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["xml"]
                    ),
                    core_erp.validadores_archivos.validar_firma_xml,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="contratoservicio",
            name="archivo",
            field=models.FileField(
                storage=core_erp.storages_qkt.storage_privado,
                upload_to="contratos_pdf/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    ),
                    core_erp.validadores_archivos.validar_firma_pdf,
                ],
                verbose_name="Archivo PDF",
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="archivo_contrato",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="contratos_pdf/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    ),
                    core_erp.validadores_archivos.validar_firma_pdf,
                ],
                verbose_name="Contrato PDF",
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="archivo_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="cotizaciones_pdf/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    ),
                    core_erp.validadores_archivos.validar_firma_pdf,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="espaciolanding",
            name="imagen",
            field=models.ImageField(
                upload_to="landing/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp"]
                    )
                ],
                verbose_name="Imagen",
            ),
        ),
        migrations.AlterField(
            model_name="gasto",
            name="archivo_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="pdf_gastos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    ),
                    core_erp.validadores_archivos.validar_firma_pdf,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="gasto",
            name="archivo_xml",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="xml_gastos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["xml"]
                    ),
                    core_erp.validadores_archivos.validar_firma_xml,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="imagenlanding",
            name="imagen",
            field=models.ImageField(
                upload_to="landing/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp"]
                    )
                ],
                verbose_name="Imagen",
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="imagen_promocional",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="productos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp"]
                    )
                ],
            ),
        ),
    ]
