# Generated by Django 6.1 on 2026-08-25 21:42

import core_erp.storages_qkt
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0074_guiatiposervicio"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="identificacion_oficial",
            field=models.FileField(
                blank=True,
                help_text="INE u otra identificación oficial de quien contrata. Se pide desde el portal antes de pagar; ver Cotizacion.identificacion_completa().",
                null=True,
                storage=core_erp.storages_qkt.storage_privado,
                upload_to="cotizaciones/identificaciones/",
                verbose_name="Identificación oficial (INE)",
            ),
        ),
    ]
