# Generated by Django 6.1 on 2026-08-25 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0075_cotizacion_identificacion_oficial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="identificacion_revisada",
            field=models.BooleanField(
                default=False,
                help_text="Márcalo tras confirmar visualmente que el archivo subido es una identificación oficial legible.",
                verbose_name="Identificación revisada",
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="identificacion_revisada_en",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Revisada el"
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="identificacion_revisada_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Revisada por",
            ),
        ),
    ]
