# Generated by Django 6.1 on 2026-08-27 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0076_cotizacion_identificacion_revisada_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="capacidad_base_hospedaje",
            field=models.PositiveIntegerField(
                default=4,
                help_text="Huéspedes incluidos en el precio por noche de esta habitación antes de cobrar personas extra. Solo aplica si el rol es 'Habitación de Hospedaje'.",
                verbose_name="Capacidad base (Hospedaje)",
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="rol_cotizador",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BASE_EVENTO", "Base — Evento (se agrega solo)"),
                    ("BASE_PASADIA", "Base — Pasadía (se agrega solo)"),
                    ("HORA_EXTRA", "Hora extra de arrendamiento"),
                    (
                        "HABITACION_HOSPEDAJE",
                        "Habitación de Hospedaje (selección múltiple)",
                    ),
                    (
                        "PERSONA_EXTRA_HOSPEDAJE",
                        "Persona extra en Hospedaje (recargo por noche)",
                    ),
                ],
                db_index=True,
                help_text="Producto que el cotizador agrega SOLO al elegir el servicio (el arrendamiento de la quinta), o que se elige en su propio paso dedicado en vez de la lista de extras (las habitaciones de Hospedaje, selección múltiple, cantidad = noches). No se ofrece como extra: si el cliente pudiera marcarlo ahí también, se cobraría dos veces. Vacío = extra normal.",
                max_length=30,
                verbose_name="Rol en el cotizador",
            ),
        ),
    ]
