# Generated by Django 6.1 on 2026-08-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0077_producto_capacidad_hospedaje"),
    ]

    operations = [
        migrations.AddField(
            model_name="descuento",
            name="es_cortesia",
            field=models.BooleanField(
                default=False,
                help_text="Marca esta regla como cortesía (evento regalado) en vez de promoción comercial. Solo cambia cómo se reporta/filtra el descuento, no su cálculo.",
                verbose_name="¿Es cortesía/regalo?",
            ),
        ),
    ]
