# Generated by Django 6.1 on 2026-09-03 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0079_alter_producto_rol_cotizador"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="rol_cotizador",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BASE_EVENTO", "Base — Evento (se agrega solo)"),
                    ("BASE_PASADIA", "Base — Pasadía (obsoleto, ver Básico/Premium)"),
                    (
                        "BASE_PASADIA_BASICO",
                        "Base — Pasadía Básico (toggle, elegido por default)",
                    ),
                    ("BASE_PASADIA_PREMIUM", "Base — Pasadía Premium (toggle)"),
                    ("HORA_EXTRA", "Hora extra de arrendamiento"),
                    (
                        "HABITACION_HOSPEDAJE",
                        "Habitación de Hospedaje (selección múltiple)",
                    ),
                    (
                        "PERSONA_EXTRA_HOSPEDAJE",
                        "Persona extra en Hospedaje (recargo por noche)",
                    ),
                    (
                        "PERSONA_EXTRA_PASADIA",
                        "Persona extra en Pasadía (aforo ampliado 21-30, incluye mobiliario; NO aplica si el cliente eligió Premium)",
                    ),
                ],
                db_index=True,
                help_text="Producto que el cotizador agrega SOLO al elegir el servicio (el arrendamiento de la quinta), o que se elige en su propio paso dedicado en vez de la lista de extras (las habitaciones de Hospedaje, selección múltiple, cantidad = noches). No se ofrece como extra: si el cliente pudiera marcarlo ahí también, se cobraría dos veces. Vacío = extra normal.",
                max_length=30,
                verbose_name="Rol en el cotizador",
            ),
        ),
    ]
