# Generated by Django 6.1 on 2026-09-09 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0080_alter_producto_rol_cotizador"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ComboTaquiza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.SlugField(
                        help_text="Identificador estable. No lo cambies una vez publicado.",
                        max_length=40,
                        unique=True,
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "descripcion_corta",
                    models.CharField(
                        blank=True,
                        help_text="Texto que ve el cliente bajo el nombre.",
                        max_length=160,
                        verbose_name="Descripción corta",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Desmarcar retira la opción del cotizador sin borrar nada.",
                    ),
                ),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Combo de Taquiza",
                "verbose_name_plural": "Combos de Taquiza",
                "ordering": ["orden", "nombre"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ExtraEvento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.SlugField(
                        help_text="Identificador estable. No lo cambies una vez publicado.",
                        max_length=40,
                        unique=True,
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "descripcion_corta",
                    models.CharField(
                        blank=True,
                        help_text="Texto que ve el cliente bajo el nombre.",
                        max_length=160,
                        verbose_name="Descripción corta",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Desmarcar retira la opción del cotizador sin borrar nada.",
                    ),
                ),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cantidad_por_persona",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Ej: 8 = ocho por invitado · 0.05 = uno cada 20 invitados. Se redondea hacia arriba.",
                        max_digits=8,
                        null=True,
                        verbose_name="Cantidad por persona",
                    ),
                ),
                (
                    "cantidad_fija",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Unidades que no dependen del aforo. Deja vacío si usas 'Cantidad por persona'.",
                        max_digits=8,
                        null=True,
                        verbose_name="Cantidad fija",
                    ),
                ),
                (
                    "capacidad_maxima_simultanea",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Solo informativo para el cliente (ej. brincolín: 5 niños). No afecta el precio.",
                        null=True,
                        verbose_name="Capacidad máxima simultánea",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        help_text="De aquí sale el precio. No se captura ningún importe en esta pantalla.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="comercial.producto",
                        verbose_name="Producto del catálogo",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Extra de Evento",
                "verbose_name_plural": "Extras de Evento",
                "ordering": ["orden", "nombre"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NivelLicor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.SlugField(
                        help_text="Identificador estable. No lo cambies una vez publicado.",
                        max_length=40,
                        unique=True,
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "descripcion_corta",
                    models.CharField(
                        blank=True,
                        help_text="Texto que ve el cliente bajo el nombre.",
                        max_length=160,
                        verbose_name="Descripción corta",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Desmarcar retira la opción del cotizador sin borrar nada.",
                    ),
                ),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nivel de Licor",
                "verbose_name_plural": "Niveles de Licor",
                "ordering": ["orden", "nombre"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PaqueteEvento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.SlugField(
                        help_text="Identificador estable. No lo cambies una vez publicado.",
                        max_length=40,
                        unique=True,
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "descripcion_corta",
                    models.CharField(
                        blank=True,
                        help_text="Texto que ve el cliente bajo el nombre.",
                        max_length=160,
                        verbose_name="Descripción corta",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Desmarcar retira la opción del cotizador sin borrar nada.",
                    ),
                ),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "requiere_mobiliario",
                    models.BooleanField(
                        default=True,
                        help_text="El cliente elige un tier de mobiliario (obligatorio).",
                        verbose_name="Exige elegir mobiliario",
                    ),
                ),
                (
                    "permite_licores_opcional",
                    models.BooleanField(
                        default=False,
                        help_text="Muestra el toggle de licores y, si se activa, el nivel.",
                        verbose_name="Ofrece licores (opcional)",
                    ),
                ),
                (
                    "requiere_taquiza",
                    models.BooleanField(
                        default=False,
                        help_text="El cliente elige un combo cerrado (obligatorio).",
                        verbose_name="Exige elegir taquiza",
                    ),
                ),
                (
                    "permite_extras",
                    models.BooleanField(
                        default=False,
                        help_text="Muestra las casillas de extras (bolis, brincolín).",
                        verbose_name="Ofrece extras",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paquete de Evento",
                "verbose_name_plural": "Paquetes de Evento",
                "ordering": ["orden", "nombre"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TipoMobiliario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.SlugField(
                        help_text="Identificador estable. No lo cambies una vez publicado.",
                        max_length=40,
                        unique=True,
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "descripcion_corta",
                    models.CharField(
                        blank=True,
                        help_text="Texto que ve el cliente bajo el nombre.",
                        max_length=160,
                        verbose_name="Descripción corta",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Desmarcar retira la opción del cotizador sin borrar nada.",
                    ),
                ),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Mobiliario",
                "verbose_name_plural": "Tipos de Mobiliario",
                "ordering": ["orden", "nombre"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ConfiguracionEventoCotizacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modalidad",
                    models.CharField(
                        choices=[
                            ("ARRENDAMIENTO", "Solo arrendamiento del espacio"),
                            ("PAQUETE", "Paquete"),
                        ],
                        max_length=15,
                    ),
                ),
                ("incluir_licores", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "combo_taquiza",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cotizaciones",
                        to="comercial.combotaquiza",
                    ),
                ),
                (
                    "cotizacion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config_evento",
                        to="comercial.cotizacion",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
                (
                    "extras",
                    models.ManyToManyField(
                        blank=True,
                        related_name="cotizaciones",
                        to="comercial.extraevento",
                    ),
                ),
                (
                    "nivel_licor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cotizaciones",
                        to="comercial.nivellicor",
                    ),
                ),
                (
                    "paquete",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cotizaciones",
                        to="comercial.paqueteevento",
                    ),
                ),
                (
                    "tipo_mobiliario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cotizaciones",
                        to="comercial.tipomobiliario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de Evento",
                "verbose_name_plural": "Configuraciones de Evento",
            },
        ),
        migrations.CreateModel(
            name="ComboTaquizaProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad_por_persona",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Ej: 8 = ocho por invitado · 0.05 = uno cada 20 invitados. Se redondea hacia arriba.",
                        max_digits=8,
                        null=True,
                        verbose_name="Cantidad por persona",
                    ),
                ),
                (
                    "cantidad_fija",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Unidades que no dependen del aforo. Deja vacío si usas 'Cantidad por persona'.",
                        max_digits=8,
                        null=True,
                        verbose_name="Cantidad fija",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                (
                    "combo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productos",
                        to="comercial.combotaquiza",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        help_text="De aquí sale el precio. No se captura ningún importe en esta pantalla.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="comercial.producto",
                        verbose_name="Producto del catálogo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proteína del combo",
                "verbose_name_plural": "Proteínas del combo",
                "ordering": ["orden", "id"],
                "abstract": False,
                "unique_together": {("combo", "producto")},
            },
        ),
        migrations.CreateModel(
            name="NivelLicorProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad_por_persona",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Ej: 8 = ocho por invitado · 0.05 = uno cada 20 invitados. Se redondea hacia arriba.",
                        max_digits=8,
                        null=True,
                        verbose_name="Cantidad por persona",
                    ),
                ),
                (
                    "cantidad_fija",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Unidades que no dependen del aforo. Deja vacío si usas 'Cantidad por persona'.",
                        max_digits=8,
                        null=True,
                        verbose_name="Cantidad fija",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                (
                    "nivel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productos",
                        to="comercial.nivellicor",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        help_text="De aquí sale el precio. No se captura ningún importe en esta pantalla.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="comercial.producto",
                        verbose_name="Producto del catálogo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto del nivel de licor",
                "verbose_name_plural": "Productos del nivel de licor",
                "ordering": ["orden", "id"],
                "abstract": False,
                "unique_together": {("nivel", "producto")},
            },
        ),
        migrations.CreateModel(
            name="PaqueteEventoProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad_por_persona",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Ej: 8 = ocho por invitado · 0.05 = uno cada 20 invitados. Se redondea hacia arriba.",
                        max_digits=8,
                        null=True,
                        verbose_name="Cantidad por persona",
                    ),
                ),
                (
                    "cantidad_fija",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Unidades que no dependen del aforo. Deja vacío si usas 'Cantidad por persona'.",
                        max_digits=8,
                        null=True,
                        verbose_name="Cantidad fija",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                (
                    "concepto",
                    models.CharField(
                        help_text="Nombre de la línea tal como la ve el cliente. Genérico y reutilizable entre paquetes: 'Refrescos', 'Servicio de mesa'.",
                        max_length=150,
                        verbose_name="Concepto",
                    ),
                ),
                (
                    "paquete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productos_incluidos",
                        to="comercial.paqueteevento",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        help_text="De aquí sale el precio. No se captura ningún importe en esta pantalla.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="comercial.producto",
                        verbose_name="Producto del catálogo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto incluido en el paquete",
                "verbose_name_plural": "Productos incluidos en el paquete",
                "ordering": ["orden", "id"],
                "abstract": False,
                "unique_together": {("paquete", "producto")},
            },
        ),
        migrations.CreateModel(
            name="TipoMobiliarioProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad_por_persona",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Ej: 8 = ocho por invitado · 0.05 = uno cada 20 invitados. Se redondea hacia arriba.",
                        max_digits=8,
                        null=True,
                        verbose_name="Cantidad por persona",
                    ),
                ),
                (
                    "cantidad_fija",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Unidades que no dependen del aforo. Deja vacío si usas 'Cantidad por persona'.",
                        max_digits=8,
                        null=True,
                        verbose_name="Cantidad fija",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                (
                    "producto",
                    models.ForeignKey(
                        help_text="De aquí sale el precio. No se captura ningún importe en esta pantalla.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="comercial.producto",
                        verbose_name="Producto del catálogo",
                    ),
                ),
                (
                    "tipo_mobiliario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productos",
                        to="comercial.tipomobiliario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto del tipo de mobiliario",
                "verbose_name_plural": "Productos del tipo de mobiliario",
                "ordering": ["orden", "id"],
                "abstract": False,
                "unique_together": {("tipo_mobiliario", "producto")},
            },
        ),
    ]
