# Generated by Django 6.1 on 2026-09-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "comercial",
            "0081_combotaquiza_extraevento_nivellicor_paqueteevento_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagenlanding",
            name="seccion",
            field=models.CharField(
                choices=[
                    ("HERO", "Banner principal"),
                    ("NOSOTROS", "Quiénes Somos"),
                    ("EVENTO", "Servicio — Eventos"),
                    ("PASADIA", "Servicio — Pasadía"),
                    ("HOSPEDAJE", "Servicio — Hospedaje"),
                    ("GALERIA", "Galería de fotos"),
                    ("ZONAS_RESTRINGIDAS", "Mapa de zonas restringidas (cotizador)"),
                ],
                max_length=20,
                verbose_name="Sección",
            ),
        ),
    ]
