# Generated by Django 6.1 on 2026-09-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0082_alter_imagenlanding_seccion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cotizacion",
            name="estado",
            field=models.CharField(
                choices=[
                    ("BORRADOR", "Borrador"),
                    ("COTIZADA", "Cotización Enviada"),
                    ("CONFIRMADA", "Venta Confirmada"),
                    ("EJECUTADA", "Evento Ejecutado"),
                    ("CERRADA", "Cerrada / Completada"),
                    ("EXPIRADA", "Expirada sin pago"),
                    ("CANCELADA", "Cancelada"),
                ],
                default="BORRADOR",
                max_length=20,
            ),
        ),
    ]
