# Generated by Django 6.1 on 2026-09-09 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


# El propietario confirmó que el catálogo del cotizador de Eventos estaba vacío
# cuando se planeó esta migración (nunca llegó a capturarlo en producción), y
# por eso las cinco tablas viejas se eliminan en vez de migrarse fila por fila.
# Si esa premisa resultara falsa el día del deploy, borrar en silencio sería lo
# peor posible: esta comprobación rompe la migración ANTES de tocar nada, para
# que el deploy falle en vez de perder datos.
TABLAS_QUE_DEBEN_ESTAR_VACIAS = (
    'comercial_paqueteevento',
    'comercial_paqueteeventoproducto',
    'comercial_tipomobiliario',
    'comercial_tipomobiliarioproducto',
    'comercial_nivellicor',
    'comercial_nivellicorproducto',
    'comercial_combotaquiza',
    'comercial_combotaquizaproducto',
    'comercial_extraevento',
)


def verificar_catalogo_vacio(apps, schema_editor):
    con_datos = []
    with schema_editor.connection.cursor() as cursor:
        existentes = set(schema_editor.connection.introspection.table_names(cursor))
        for tabla in TABLAS_QUE_DEBEN_ESTAR_VACIAS:
            if tabla not in existentes:
                continue
            cursor.execute(f'SELECT COUNT(*) FROM "{tabla}"')  # noqa: S608 -- nombre de tabla fijo, no entrada externa
            cuantos = cursor.fetchone()[0]
            if cuantos:
                con_datos.append(f'{tabla} ({cuantos})')
    if con_datos:
        raise RuntimeError(
            'El catálogo del cotizador de Eventos NO está vacío: '
            + ', '.join(con_datos)
            + '. Esta migración lo daría por perdido. Detén el deploy y pide una '
              'migración de datos que traslade estas filas a CatalogoEvento.'
        )


def sin_reversa(apps, schema_editor):
    """Nada que deshacer: la comprobación no escribe."""


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0083_alter_cotizacion_estado"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(verificar_catalogo_vacio, sin_reversa),
        migrations.AlterUniqueTogether(
            name="nivellicorproducto",
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name="paqueteeventoproducto",
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name="tipomobiliarioproducto",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="combotaquiza",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="combotaquiza",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="extraevento",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="extraevento",
            name="producto",
        ),
        migrations.RemoveField(
            model_name="extraevento",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="configuracioneventocotizacion",
            name="extras",
        ),
        migrations.RemoveField(
            model_name="nivellicor",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="nivellicor",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="nivellicorproducto",
            name="nivel",
        ),
        migrations.RemoveField(
            model_name="nivellicorproducto",
            name="producto",
        ),
        migrations.RemoveField(
            model_name="paqueteevento",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="paqueteevento",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="paqueteeventoproducto",
            name="paquete",
        ),
        migrations.RemoveField(
            model_name="paqueteeventoproducto",
            name="producto",
        ),
        migrations.RemoveField(
            model_name="tipomobiliario",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="tipomobiliario",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="tipomobiliarioproducto",
            name="tipo_mobiliario",
        ),
        migrations.RemoveField(
            model_name="tipomobiliarioproducto",
            name="producto",
        ),
        migrations.CreateModel(
            name="CatalogoEvento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.SlugField(
                        help_text="Identificador estable. No lo cambies una vez publicado.",
                        max_length=40,
                        unique=True,
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "descripcion_corta",
                    models.CharField(
                        blank=True,
                        help_text="Texto que ve el cliente bajo el nombre.",
                        max_length=160,
                        verbose_name="Descripción corta",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Desmarcar retira la opción del cotizador sin borrar nada.",
                    ),
                ),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("PAQUETE", "Paquete (Esencial / QKT)"),
                            ("MOBILIARIO", "Tipo de mobiliario"),
                            ("LICOR", "Nivel de licor"),
                            ("TAQUIZA", "Combo de taquiza"),
                            ("EXTRA", "Extra (bolis, brincolín)"),
                        ],
                        db_index=True,
                        help_text="Dónde aparece esta opción en el cotizador.",
                        max_length=15,
                    ),
                ),
                (
                    "requiere_mobiliario",
                    models.BooleanField(
                        default=False,
                        help_text="Solo paquetes. El cliente elige un tipo de mobiliario (obligatorio).",
                        verbose_name="Exige elegir mobiliario",
                    ),
                ),
                (
                    "permite_licores_opcional",
                    models.BooleanField(
                        default=False,
                        help_text="Solo paquetes. Muestra el toggle de licores y, si se activa, el nivel.",
                        verbose_name="Ofrece licores (opcional)",
                    ),
                ),
                (
                    "requiere_taquiza",
                    models.BooleanField(
                        default=False,
                        help_text="Solo paquetes. El cliente elige un combo cerrado (obligatorio).",
                        verbose_name="Exige elegir taquiza",
                    ),
                ),
                (
                    "permite_extras",
                    models.BooleanField(
                        default=False,
                        help_text="Solo paquetes. Muestra las casillas de extras (bolis, brincolín).",
                        verbose_name="Ofrece extras",
                    ),
                ),
                (
                    "capacidad_maxima_simultanea",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Solo extras. Informativo para el cliente (ej. brincolín: 5 niños). No afecta el precio.",
                        null=True,
                        verbose_name="Capacidad máxima simultánea",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opción del cotizador de Eventos",
                "verbose_name_plural": "Cotizador de Eventos — opciones",
                "ordering": ["tipo", "orden", "nombre"],
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="configuracioneventocotizacion",
            name="combo_taquiza",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cotizaciones_como_taquiza",
                to="comercial.catalogoevento",
            ),
        ),
        migrations.AlterField(
            model_name="configuracioneventocotizacion",
            name="nivel_licor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cotizaciones_como_licor",
                to="comercial.catalogoevento",
            ),
        ),
        migrations.AlterField(
            model_name="configuracioneventocotizacion",
            name="paquete",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cotizaciones_como_paquete",
                to="comercial.catalogoevento",
            ),
        ),
        migrations.AlterField(
            model_name="configuracioneventocotizacion",
            name="tipo_mobiliario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cotizaciones_como_mobiliario",
                to="comercial.catalogoevento",
            ),
        ),
        migrations.CreateModel(
            name="CatalogoEventoProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad_por_persona",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Ej: 8 = ocho por invitado · 0.05 = uno cada 20 invitados. Se redondea hacia arriba.",
                        max_digits=8,
                        null=True,
                        verbose_name="Cantidad por persona",
                    ),
                ),
                (
                    "cantidad_fija",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Unidades que no dependen del aforo. Deja vacío si usas 'Cantidad por persona'.",
                        max_digits=8,
                        null=True,
                        verbose_name="Cantidad fija",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                (
                    "concepto",
                    models.CharField(
                        blank=True,
                        help_text="Solo para lo que un paquete incluye sin que el cliente lo elija (refrescos, servicio de mesa): nombre de la línea tal como la ve. Vacío en el resto: el concepto lo pone el tipo de opción.",
                        max_length=150,
                        verbose_name="Concepto",
                    ),
                ),
                (
                    "opcion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productos",
                        to="comercial.catalogoevento",
                        verbose_name="Opción del cotizador",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        help_text="De aquí sale el precio. No se captura ningún importe en esta pantalla.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="comercial.producto",
                        verbose_name="Producto del catálogo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto de la opción",
                "verbose_name_plural": "Productos de la opción",
                "ordering": ["orden", "id"],
                "abstract": False,
                "unique_together": {("opcion", "producto")},
            },
        ),
        migrations.DeleteModel(
            name="ComboTaquizaProducto",
        ),
        migrations.DeleteModel(
            name="ExtraEvento",
        ),
        migrations.AddField(
            model_name="configuracioneventocotizacion",
            name="extras",
            field=models.ManyToManyField(
                blank=True,
                related_name="cotizaciones_como_extra",
                to="comercial.catalogoevento",
            ),
        ),
        migrations.DeleteModel(
            name="NivelLicorProducto",
        ),
        migrations.DeleteModel(
            name="PaqueteEventoProducto",
        ),
        migrations.DeleteModel(
            name="TipoMobiliarioProducto",
        ),
        migrations.DeleteModel(
            name="ComboTaquiza",
        ),
        migrations.DeleteModel(
            name="NivelLicor",
        ),
        migrations.DeleteModel(
            name="PaqueteEvento",
        ),
        migrations.DeleteModel(
            name="TipoMobiliario",
        ),
    ]
