# Generated by Django 6.1 on 2026-09-14 01:52
"""
Quita `es_upgrade`/`hereda_inventario_de` de Producto: mecanismo de
"herencia de inventario" (evitar duplicar subproductos entre un producto
base y su upgrade al calcular inventario) cuyo único consumidor,
`Cotizacion.calcular_inventario_inteligente()`, no lo llamaba ningún
signal/vista/reporte/comando del proyecto — confirmado con grep exhaustivo
antes de borrar. El propietario confirmó que ya no se usa. `requiere_licor`
(campo separado, mismo modelo) no se toca: sigue vivo en
`Cotizacion.clean()` y en el cotizador público.
"""

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0085_limpia_tablas_huerfanas_catalogo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producto",
            name="es_upgrade",
        ),
        migrations.RemoveField(
            model_name="producto",
            name="hereda_inventario_de",
        ),
    ]
