# Generated by Django 6.1 on 2026-09-14 23:44
"""
`nivel_licor` (FK, opción única) -> `niveles_licor` (M2M): el rediseño del
cotizador de Eventos (Issue #286) pide que Cerveza/Nacional/Premium se
puedan combinar libremente en "Servicios Incluidos", no elegir una sola.
No se migran datos: una `ConfiguracionEventoCotizacion` existente con
`nivel_licor` capturado perdería esa selección puntual (queda sin niveles
de licor, el resto de la configuración/`ItemCotizacion` ya cobrados no se
tocan) — riesgo aceptado porque este es un catálogo cerrado de reciente
adopción, no el flujo principal de Evento.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0086_remove_producto_es_upgrade_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="configuracioneventocotizacion",
            name="nivel_licor",
        ),
        migrations.AddField(
            model_name="configuracioneventocotizacion",
            name="niveles_licor",
            field=models.ManyToManyField(
                blank=True,
                related_name="cotizaciones_como_licor",
                to="comercial.catalogoevento",
            ),
        ),
    ]
