# Generated by Django 6.1 on 2026-09-17 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0087_remove_configuracioneventocotizacion_nivel_licor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogoevento",
            name="aforo_maximo",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Solo paquetes. Vacío = usa el máximo general del cotizador de Eventos (150).",
                null=True,
                verbose_name="Aforo máximo",
            ),
        ),
        migrations.AddField(
            model_name="catalogoevento",
            name="aforo_minimo",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Solo paquetes. Vacío = sin mínimo propio (usa el mínimo general del cotizador de Eventos).",
                null=True,
                verbose_name="Aforo mínimo",
            ),
        ),
        migrations.AddField(
            model_name="catalogoevento",
            name="aforo_paso",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Solo paquetes. Vacío = tramo general (10, el cliente elige 50, 60, 70...). Pon 1 para que no haya tramos: cualquier número de personas dentro del rango es válido.",
                null=True,
                verbose_name="Tramo de aforo",
            ),
        ),
    ]
