# Generated by Django 6.1 on 2026-09-17 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0088_catalogoevento_aforo_maximo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductoEventos",
            fields=[],
            options={
                "verbose_name": "Producto de Eventos",
                "verbose_name_plural": "Eventos — Productos",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("comercial.producto",),
        ),
        migrations.CreateModel(
            name="ProductoHospedaje",
            fields=[],
            options={
                "verbose_name": "Producto de Hospedaje",
                "verbose_name_plural": "Hospedaje — Productos",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("comercial.producto",),
        ),
        migrations.CreateModel(
            name="ProductoPasadia",
            fields=[],
            options={
                "verbose_name": "Producto de Pasadía",
                "verbose_name_plural": "Pasadía — Productos",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("comercial.producto",),
        ),
    ]
