# Generated by Django 6.1 on 2026-09-17 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0089_productoeventos_productohospedaje_productopasadia"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productoeventos",
            options={
                "verbose_name": "Productos — Eventos",
                "verbose_name_plural": "Productos — Eventos",
            },
        ),
        migrations.AlterModelOptions(
            name="productohospedaje",
            options={
                "verbose_name": "Productos — Hospedaje",
                "verbose_name_plural": "Productos — Hospedaje",
            },
        ),
        migrations.AlterModelOptions(
            name="productopasadia",
            options={
                "verbose_name": "Productos — Pasadía",
                "verbose_name_plural": "Productos — Pasadía",
            },
        ),
    ]
