# Generated by Django 6.1 on 2026-09-17 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0090_alter_productoeventos_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productoeventos",
            options={"verbose_name": "Eventos", "verbose_name_plural": "Eventos"},
        ),
        migrations.AlterModelOptions(
            name="productohospedaje",
            options={"verbose_name": "Hospedaje", "verbose_name_plural": "Hospedaje"},
        ),
        migrations.AlterModelOptions(
            name="productopasadia",
            options={"verbose_name": "Pasadía", "verbose_name_plural": "Pasadía"},
        ),
    ]
