# Generated by Django 6.1 on 2026-09-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0091_alter_productoeventos_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="precio_venta_fijo",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Si se define (>0), sobreescribe el cálculo costo×margen. Para rentas de precio fijo (mobiliario). Se guarda con 4 decimales (aunque el admin captura el precio con IVA a centavos) para que el round-trip con_iva(precio_venta_fijo) reproduzca exacto el importe capturado — ver core_erp/impuestos.py::sin_iva_preciso.",
                max_digits=10,
                null=True,
                verbose_name="Precio de venta fijo",
            ),
        ),
    ]
