# Generated by Django 6.1 on 2026-09-17 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0092_alter_producto_precio_venta_fijo"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="impuesto_hospedaje",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Impuesto estatal al hospedaje. Solo se calcula en cotizaciones de HOSPEDAJE y solo si hay una tasa configurada (TASA_ISH). El hospedaje de Airbnb no lleva: ese ISH lo retiene y entera la propia plataforma.",
                max_digits=10,
                verbose_name="Impuesto al hospedaje (ISH)",
            ),
        ),
    ]
