# Generated by Django 6.1 on 2026-09-17 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0092_alter_producto_precio_venta_fijo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="grupo_cotizador",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PAQUETE", "Paquetes"),
                    ("MOBILIARIO", "Mobiliario"),
                    ("ALIMENTOS", "Alimentos"),
                    ("BEBIDAS", "Bebidas"),
                    ("SERVICIOS", "Servicios"),
                    ("EXTRAS", "Extras"),
                    ("OTRO", "Otros"),
                    ("ENTRETENIMIENTO", "Entretenimiento (obsoleto, recategorizar)"),
                    (
                        "COMIDA",
                        "Alimentos y Bebidas (obsoleto, recategorizar en Alimentos/Bebidas)",
                    ),
                    ("DECORACION", "Decoración (obsoleto, recategorizar en Extras)"),
                    ("INFANTIL", "Infantil (obsoleto, recategorizar en Extras)"),
                ],
                max_length=20,
                verbose_name="Grupo en cotizador",
            ),
        ),
    ]
