# Generated by Django 6.1 on 2026-09-17 23:05
#
# Retira el catálogo cerrado de Eventos (Issue #287): CatalogoEvento,
# CatalogoEventoProducto y ConfiguracionEventoCotizacion. Si en producción ya
# existe alguna `ConfiguracionEventoCotizacion` ligada a una cotización real
# (confirmada/pagada), esta migración la borra sin dejar rastro — revisar
# `SELECT COUNT(*) FROM comercial_configuracioneventocotizacion` antes de
# aplicar en Railway; si hay filas, exportarlas a un JSON de auditoría antes
# de mergear, no perderlas en silencio.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0093_grupo_cotizador_categorias"),
    ]

    operations = [
        # `AlterUniqueTogether` va primero: la constraint de
        # CatalogoEventoProducto incluye `opcion`/`producto`, así que
        # quitarla antes evita que el remake de tabla de SQLite intente
        # reconstruir la unique_together con un campo ya eliminado.
        migrations.AlterUniqueTogether(
            name="catalogoeventoproducto",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="catalogoeventoproducto",
            name="opcion",
        ),
        migrations.RemoveField(
            model_name="catalogoeventoproducto",
            name="producto",
        ),
        migrations.RemoveField(
            model_name="configuracioneventocotizacion",
            name="combo_taquiza",
        ),
        migrations.RemoveField(
            model_name="configuracioneventocotizacion",
            name="paquete",
        ),
        migrations.RemoveField(
            model_name="configuracioneventocotizacion",
            name="tipo_mobiliario",
        ),
        migrations.RemoveField(
            model_name="configuracioneventocotizacion",
            name="extras",
        ),
        migrations.RemoveField(
            model_name="configuracioneventocotizacion",
            name="niveles_licor",
        ),
        migrations.RemoveField(
            model_name="configuracioneventocotizacion",
            name="cotizacion",
        ),
        migrations.RemoveField(
            model_name="configuracioneventocotizacion",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="configuracioneventocotizacion",
            name="updated_by",
        ),
        migrations.DeleteModel(
            name="CatalogoEvento",
        ),
        migrations.DeleteModel(
            name="CatalogoEventoProducto",
        ),
        migrations.DeleteModel(
            name="ConfiguracionEventoCotizacion",
        ),
    ]
