# Generated by Django 6.1 on 2026-09-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0093_impuesto_hospedaje_cotizacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="tasa_ish_aplicada",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="Tasa de ISH con la que se cotizó, congelada al crear la cotización (o mientras siga en BORRADOR). No se relee de la configuración al reguardar: si se releyera, encender la tasa subiría el precio de cotizaciones ya aceptadas —y reabriría saldo en las ya pagadas— con solo editarlas. Las cotizaciones anteriores al ISH quedan en 0 y ahí se quedan.",
                max_digits=6,
                verbose_name="Tasa de ISH aplicada",
            ),
        ),
    ]
