# Generated by Django 6.1 on 2026-09-18 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0094_retirar_catalogo_evento"),
        ("comercial", "0094_tasa_ish_congelada"),
    ]

    operations = []
