# Generated by Django 6.1 on 2026-09-22 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0095_merge_20260918_1134"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contracargo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "openpay_id",
                    models.CharField(
                        db_index=True,
                        help_text="Identificador del contracargo tal como lo manda el webhook.",
                        max_length=100,
                        verbose_name="ID reportado por Openpay",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Último evento recibido"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("EN_DISPUTA", "En disputa"),
                            ("GANADO", "Ganado (a favor del comercio)"),
                            ("PERDIDO", "Perdido (a favor del cliente)"),
                        ],
                        default="EN_DISPUTA",
                        max_length=15,
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "motivo",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Motivo reportado por Openpay",
                    ),
                ),
                ("fecha_recibido", models.DateTimeField(auto_now_add=True)),
                (
                    "fecha_limite_evidencia",
                    models.DateField(
                        blank=True,
                        help_text="3 días hábiles desde la notificación (chargeback.created). Pasada esta fecha, Openpay ya no puede disputar el contracargo.",
                        null=True,
                        verbose_name="Límite para enviar evidencia",
                    ),
                ),
                ("fecha_resolucion", models.DateTimeField(blank=True, null=True)),
                (
                    "evidencia_enviada",
                    models.BooleanField(
                        default=False,
                        help_text="Marcar manualmente al enviar la evidencia a soporte@openpay.mx.",
                    ),
                ),
                ("notas", models.TextField(blank=True)),
                (
                    "requiere_vinculacion_manual",
                    models.BooleanField(
                        default=False,
                        help_text="No se pudo resolver automáticamente la cotización/transacción original — revisar el payload crudo.",
                        verbose_name="Requiere vinculación manual",
                    ),
                ),
                (
                    "payload_crudo",
                    models.JSONField(verbose_name="Último JSON recibido de Openpay"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cotizacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contracargos",
                        to="comercial.cotizacion",
                    ),
                ),
                (
                    "pago_reactivacion",
                    models.OneToOneField(
                        blank=True,
                        help_text="Pago tipo INGRESO generado automáticamente si se gana la disputa.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contracargo_reactivacion",
                        to="comercial.pago",
                    ),
                ),
                (
                    "pago_reversion",
                    models.OneToOneField(
                        blank=True,
                        help_text="Pago tipo REEMBOLSO generado automáticamente al recibirse el contracargo.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contracargo_reversion",
                        to="comercial.pago",
                    ),
                ),
                (
                    "transaccion_openpay",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contracargos",
                        to="comercial.openpaytransaccion",
                        verbose_name="Transacción original",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contracargo",
                "verbose_name_plural": "Contracargos",
                "ordering": ["-fecha_recibido"],
                "indexes": [
                    models.Index(
                        fields=["openpay_id"], name="comercial_c_openpay_5189ca_idx"
                    ),
                    models.Index(
                        fields=["estado", "fecha_recibido"],
                        name="comercial_c_estado_cfe25e_idx",
                    ),
                ],
            },
        ),
    ]
