# Generated by Django 6.1 on 2026-09-22 22:18

import core_erp.storages_qkt
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0096_contracargo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contracargo",
            name="evidencia_enviada_por",
            field=models.ForeignKey(
                blank=True,
                help_text="Vacío si el envío fue automático (cron de última instancia, sin intervención manual).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Evidencia enviada por",
            ),
        ),
        migrations.AddField(
            model_name="contracargo",
            name="evidencia_pdf",
            field=models.FileField(
                blank=True,
                help_text="Generado automáticamente al entrar en disputa: datos de la transacción, la cotización, los pagos y la bitácora de comunicación con el cliente.",
                null=True,
                storage=core_erp.storages_qkt.storage_privado,
                upload_to="contracargos/evidencia/",
                verbose_name="PDF de evidencia armado",
            ),
        ),
        migrations.AddField(
            model_name="contracargo",
            name="fecha_evidencia_enviada",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contracargo",
            name="evidencia_enviada",
            field=models.BooleanField(
                default=False,
                help_text="Se marca sola al enviar la evidencia a soporte@openpay.mx — con un clic desde el admin o, si nadie lo hizo a tiempo, por el envío automático de última instancia antes del plazo (ver comercial.services_evidencia_contracargo).",
            ),
        ),
    ]
