# Generated by Django 6.1 on 2026-09-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0097_contracargo_evidencia"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="fecha_reactivacion",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="Reactivada el"
            ),
        ),
    ]
