# Generated by Django 6.1 on 2026-09-23 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0098_cotizacion_fecha_reactivacion"),
        ("contabilidad", "0019_retiro_airbnb_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compra",
            name="unidad_negocio",
            field=models.ForeignKey(
                blank=True,
                help_text="Unidad de negocio a la que se carga el gasto. Sin este dato la póliza queda en BORRADOR y no se aplica.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="compras",
                to="contabilidad.unidadnegocio",
                verbose_name="Unidad de negocio",
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="fecha_salida",
            field=models.DateField(
                blank=True,
                help_text="Solo aplica a HOSPEDAJE: fecha de checkout, EXCLUSIVA (la última noche ocupada es fecha_salida - 1 día). Vacía en cualquier otro tipo de servicio.",
                null=True,
                verbose_name="Fecha de salida (checkout)",
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="impuesto_hospedaje",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Impuesto estatal al hospedaje. Solo se calcula en cotizaciones de HOSPEDAJE y solo si hay una tasa configurada (TASA_ISH).",
                max_digits=10,
                verbose_name="Impuesto al hospedaje (ISH)",
            ),
        ),
    ]
