# Generated by Django 6.1 on 2026-09-24 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0099_retiro_airbnb_textos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="descuento",
            name="usos",
        ),
        migrations.AddField(
            model_name="descuento",
            name="productos",
            field=models.ManyToManyField(
                blank=True,
                help_text="Vacío = toda la cotización. Si eliges productos o paquetes, el descuento se calcula solo sobre esos conceptos y solo aplica si la cotización incluye al menos uno.",
                related_name="descuentos_especificos",
                to="comercial.producto",
                verbose_name="Productos / paquetes",
            ),
        ),
        migrations.AlterField(
            model_name="descuento",
            name="max_usos",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Tope de ventas confirmadas con este descuento. Vacío = ilimitado. Una cotización que nunca se confirma no gasta usos.",
                null=True,
                verbose_name="Máximo de usos",
            ),
        ),
        migrations.AlterField(
            model_name="descuento",
            name="tipos_servicio",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Lista de: EVENTO, PASADIA, HOSPEDAJE, ARRENDAMIENTO. Vacío = todos.",
                verbose_name="Tipos de servicio",
            ),
        ),
    ]
