# Generated by Django 6.1 on 2026-09-25 17:09

import core_erp.storages_qkt
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0100_descuentos_por_producto_y_usos_confirmados"),
    ]

    operations = [
        migrations.CreateModel(
            name="FirmaContrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hash_documento",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        verbose_name="SHA-256 del contrato mostrado",
                    ),
                ),
                ("codigo_hash", models.CharField(blank=True, max_length=128)),
                ("codigo_enviado_en", models.DateTimeField(blank=True, null=True)),
                (
                    "codigo_canal",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Canal del código"
                    ),
                ),
                (
                    "codigo_destino",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Destino del código"
                    ),
                ),
                ("intentos", models.PositiveSmallIntegerField(default=0)),
                ("nombre_firmante", models.CharField(blank=True, max_length=200)),
                (
                    "imagen_firma",
                    models.FileField(
                        blank=True,
                        storage=core_erp.storages_qkt.storage_privado,
                        upload_to="firmas_contrato/",
                    ),
                ),
                ("firmado_en", models.DateTimeField(blank=True, null=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=300)),
                ("acepta_publicidad", models.BooleanField(default=False)),
                ("acepta_transmision", models.BooleanField(default=False)),
                (
                    "archivo_firmado",
                    models.FileField(
                        blank=True,
                        storage=core_erp.storages_qkt.storage_privado,
                        upload_to="contratos_firmados/",
                        verbose_name="PDF firmado",
                    ),
                ),
                (
                    "hash_firmado",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        verbose_name="SHA-256 del PDF firmado",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contrato",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="firma",
                        to="comercial.contratoservicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Firma de contrato",
                "verbose_name_plural": "Firmas de contrato",
                "ordering": ["-created_at"],
            },
        ),
    ]
