# Generated by Django 6.1 on 2026-09-25 17:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0101_firma_contrato"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="openpaytransaccion",
            name="destino",
            field=models.CharField(
                choices=[
                    ("SERVICIO", "Pago del servicio"),
                    ("DEPOSITO", "Depósito en garantía"),
                ],
                default="SERVICIO",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="DepositoGarantia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Monto del depósito",
                    ),
                ),
                ("notas", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cotizacion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deposito_garantia",
                        to="comercial.cotizacion",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Depósito en garantía",
                "verbose_name_plural": "Depósitos en garantía",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MovimientoDeposito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("RECEPCION", "Recepción"),
                            ("DEVOLUCION", "Devolución"),
                            ("RETENCION_DANOS", "Retención por daños"),
                            (
                                "RETENCION_SERVICIO",
                                "Retención por servicio (tiempo extra, limpieza)",
                            ),
                        ],
                        max_length=20,
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha", models.DateField(default=django.utils.timezone.now)),
                (
                    "metodo",
                    models.CharField(
                        choices=[
                            ("PLATAFORMA", "Openpay"),
                            ("TRANSFERENCIA", "Transferencia"),
                            ("EFECTIVO", "Efectivo"),
                            ("TARJETA", "Terminal / tarjeta"),
                            ("NO_APLICA", "No aplica (retención)"),
                        ],
                        max_length=15,
                    ),
                ),
                ("referencia", models.CharField(blank=True, max_length=100)),
                (
                    "desglose",
                    models.TextField(blank=True, verbose_name="Desglose / motivo"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deposito",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos",
                        to="comercial.depositogarantia",
                    ),
                ),
                (
                    "transaccion_openpay",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimiento_deposito",
                        to="comercial.openpaytransaccion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de depósito",
                "verbose_name_plural": "Movimientos de depósito",
                "ordering": ["fecha", "pk"],
            },
        ),
    ]
