# Generated by Django 6.1 on 2026-09-26 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0102_deposito_garantia"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subproducto",
            options={
                "verbose_name": "Subproducto",
                "verbose_name_plural": "Subproductos",
            },
        ),
        migrations.AlterField(
            model_name="asignacionespacio",
            name="cotizacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="espacios_asignados",
                to="comercial.cotizacion",
                verbose_name="Cotización",
            ),
        ),
        migrations.AlterField(
            model_name="asignacionespacio",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
        ),
        migrations.AlterField(
            model_name="asignacionpersonal",
            name="cotizacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personal_asignado",
                to="comercial.cotizacion",
                verbose_name="Cotización",
            ),
        ),
        migrations.AlterField(
            model_name="asignacionpersonal",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="codigo_postal_fiscal",
            field=models.CharField(
                blank=True, max_length=5, null=True, verbose_name="Código postal fiscal"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="razon_social",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Razón social"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="regimen_fiscal",
            field=models.CharField(
                blank=True,
                choices=[
                    ("601", "601 - General de Ley Personas Morales"),
                    ("603", "603 - Personas Morales con Fines no Lucrativos"),
                    (
                        "605",
                        "605 - Sueldos y Salarios e Ingresos Asimilados a Salarios",
                    ),
                    ("606", "606 - Arrendamiento"),
                    ("607", "607 - Régimen de Enajenación o Adquisición de Bienes"),
                    ("608", "608 - Demás ingresos"),
                    ("609", "609 - Consolidación"),
                    (
                        "610",
                        "610 - Residentes en el Extranjero sin Establecimiento Permanente en México",
                    ),
                    ("611", "611 - Ingresos por Dividendos (socios y accionistas)"),
                    (
                        "612",
                        "612 - Personas Físicas con Actividades Empresariales y Profesionales",
                    ),
                    ("614", "614 - Ingresos por intereses"),
                    ("615", "615 - Régimen de los ingresos por obtención de premios"),
                    ("616", "616 - Sin obligaciones fiscales"),
                    (
                        "620",
                        "620 - Sociedades Cooperativas de Producción que optan por diferir sus ingresos",
                    ),
                    ("621", "621 - Incorporación Fiscal"),
                    (
                        "622",
                        "622 - Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras",
                    ),
                    ("623", "623 - Opcional para Grupos de Sociedades"),
                    ("624", "624 - Coordinados"),
                    (
                        "625",
                        "625 - Régimen de las Actividades Empresariales con ingresos a través de Plataformas Tecnológicas",
                    ),
                    ("626", "626 - Régimen Simplificado de Confianza"),
                    ("628", "628 - Hidrocarburos"),
                    (
                        "629",
                        "629 - De los Regímenes Fiscales Preferentes y de las Empresas Multinacionales",
                    ),
                    ("630", "630 - Enajenación de acciones en bolsa de valores"),
                ],
                default="616",
                max_length=3,
                null=True,
                verbose_name="Régimen fiscal",
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="telefono",
            field=models.CharField(blank=True, max_length=20, verbose_name="Teléfono"),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="uso_cfdi",
            field=models.CharField(
                blank=True,
                choices=[
                    ("G01", "G01 - Adquisición de mercancías"),
                    ("G02", "G02 - Devoluciones, descuentos o bonificaciones"),
                    ("G03", "G03 - Gastos en general"),
                    ("I01", "I01 - Construcciones"),
                    ("I02", "I02 - Mobiliario y equipo de oficina"),
                    ("I03", "I03 - Equipo de transporte"),
                    ("I04", "I04 - Equipo de computo y accesorios"),
                    (
                        "D01",
                        "D01 - Honorarios médicos, dentales y gastos hospitalarios",
                    ),
                    ("D02", "D02 - Gastos médicos por incapacidad"),
                    ("D03", "D03 - Gastos funerales"),
                    ("D04", "D04 - Donativos"),
                    ("D05", "D05 - Intereses reales hipotecarios"),
                    ("D06", "D06 - Aportaciones voluntarias al SAR"),
                    ("D07", "D07 - Primas por seguros de gastos médicos"),
                    ("D08", "D08 - Gastos de transportación escolar obligatoria"),
                    ("D09", "D09 - Depósitos en cuentas para el ahorro"),
                    ("D10", "D10 - Pagos por servicios educativos (Colegiaturas)"),
                    ("S01", "S01 - Sin efectos fiscales"),
                    ("CP01", "CP01 - Pagos"),
                    ("CN01", "CN01 - Nómina"),
                ],
                default="G03",
                max_length=4,
                null=True,
                verbose_name="Uso de CFDI",
            ),
        ),
        migrations.AlterField(
            model_name="compra",
            name="archivo_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="pdf_compras/",
                verbose_name="Archivo PDF",
            ),
        ),
        migrations.AlterField(
            model_name="compra",
            name="archivo_xml",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="xml_compras/",
                verbose_name="Archivo XML",
            ),
        ),
        migrations.AlterField(
            model_name="compra",
            name="fecha_emision",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de emisión"
            ),
        ),
        migrations.AlterField(
            model_name="compra",
            name="iva",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=12, verbose_name="IVA"
            ),
        ),
        migrations.AlterField(
            model_name="compra",
            name="ret_isr",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=12,
                verbose_name="Retención ISR",
            ),
        ),
        migrations.AlterField(
            model_name="compra",
            name="ret_iva",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=12,
                verbose_name="Retención IVA",
            ),
        ),
        migrations.AlterField(
            model_name="compra",
            name="rfc_emisor",
            field=models.CharField(
                blank=True, max_length=13, verbose_name="RFC emisor"
            ),
        ),
        migrations.AlterField(
            model_name="compra",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Subido el"),
        ),
        migrations.AlterField(
            model_name="compra",
            name="uuid",
            field=models.CharField(
                blank=True, max_length=36, null=True, unique=True, verbose_name="UUID"
            ),
        ),
        migrations.AlterField(
            model_name="constantesistema",
            name="descripcion",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Descripción"
            ),
        ),
        migrations.AlterField(
            model_name="contracargo",
            name="cotizacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contracargos",
                to="comercial.cotizacion",
                verbose_name="Cotización",
            ),
        ),
        migrations.AlterField(
            model_name="contracargo",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
        ),
        migrations.AlterField(
            model_name="contracargo",
            name="fecha_resolucion",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de resolución"
            ),
        ),
        migrations.AlterField(
            model_name="contracargo",
            name="pago_reactivacion",
            field=models.OneToOneField(
                blank=True,
                help_text="Pago tipo INGRESO generado automáticamente si se gana la disputa.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contracargo_reactivacion",
                to="comercial.pago",
                verbose_name="Pago de reactivación",
            ),
        ),
        migrations.AlterField(
            model_name="contracargo",
            name="pago_reversion",
            field=models.OneToOneField(
                blank=True,
                help_text="Pago tipo REEMBOLSO generado automáticamente al recibirse el contracargo.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contracargo_reversion",
                to="comercial.pago",
                verbose_name="Pago de reversión",
            ),
        ),
        migrations.AlterField(
            model_name="contracargo",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
        ),
        migrations.AlterField(
            model_name="contratoservicio",
            name="cotizacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contratos",
                to="comercial.cotizacion",
                verbose_name="Cotización",
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="archivo_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="cotizaciones_pdf/",
                verbose_name="Archivo PDF",
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="fecha_cancelacion",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de cancelación"
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="iva",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="IVA"
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="retencion_isr",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Retención ISR",
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="retencion_iva",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Retención IVA",
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
        ),
        migrations.AlterField(
            model_name="depositogarantia",
            name="cotizacion",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deposito_garantia",
                to="comercial.cotizacion",
                verbose_name="Cotización",
            ),
        ),
        migrations.AlterField(
            model_name="depositogarantia",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
        ),
        migrations.AlterField(
            model_name="depositogarantia",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AlterField(
            model_name="depositogarantia",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
        ),
        migrations.AlterField(
            model_name="depositogarantia",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actualizado por",
            ),
        ),
        migrations.AlterField(
            model_name="descuento",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
        ),
        migrations.AlterField(
            model_name="descuento",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
        ),
        migrations.AlterField(
            model_name="espacio",
            name="descripcion",
            field=models.TextField(blank=True, verbose_name="Descripción"),
        ),
        migrations.AlterField(
            model_name="firmacontrato",
            name="acepta_transmision",
            field=models.BooleanField(default=False, verbose_name="Acepta transmisión"),
        ),
        migrations.AlterField(
            model_name="firmacontrato",
            name="codigo_enviado_en",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Código enviado el"
            ),
        ),
        migrations.AlterField(
            model_name="firmacontrato",
            name="codigo_hash",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Hash del código"
            ),
        ),
        migrations.AlterField(
            model_name="firmacontrato",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
        ),
        migrations.AlterField(
            model_name="firmacontrato",
            name="ip",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="IP"
            ),
        ),
        migrations.AlterField(
            model_name="firmacontrato",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
        ),
        migrations.AlterField(
            model_name="firmacontrato",
            name="user_agent",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Navegador (user agent)"
            ),
        ),
        migrations.AlterField(
            model_name="gasto",
            name="archivo_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="pdf_gastos/",
                verbose_name="Archivo PDF",
            ),
        ),
        migrations.AlterField(
            model_name="gasto",
            name="archivo_xml",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="xml_gastos/",
                verbose_name="Archivo XML",
            ),
        ),
        migrations.AlterField(
            model_name="gasto",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("SIN_CLASIFICAR", "Sin Clasificar"),
                    ("SERVICIO_EXTERNO", "Servicio Externo"),
                    ("BEBIDAS_SIN_ALCOHOL", "Bebidas Sin Alcohol"),
                    ("BEBIDAS_CON_ALCOHOL", "Bebidas Con Alcohol"),
                    ("LIMPIEZA", "Limpieza Y Desechables"),
                    ("MOBILIARIO_EQ", "Mobiliario Y Equipo"),
                    ("MANTENIMIENTO", "Mantenimiento Y Reparaciones"),
                    ("NOMINA_EXT", "Servicios Staff Externo"),
                    ("IMPUESTOS", "Pago De Impuestos"),
                    ("PUBLICIDAD", "Publicidad Y Marketing"),
                    ("SERVICIOS_ADMON", "Servicios Administrativos Y Bancarios"),
                    ("OTRO", "Otros Gastos"),
                ],
                default="SIN_CLASIFICAR",
                max_length=20,
                verbose_name="Categoría",
            ),
        ),
        migrations.AlterField(
            model_name="gasto",
            name="clave_sat",
            field=models.CharField(blank=True, max_length=20, verbose_name="Clave SAT"),
        ),
        migrations.AlterField(
            model_name="gasto",
            name="descripcion",
            field=models.CharField(max_length=255, verbose_name="Descripción"),
        ),
        migrations.AlterField(
            model_name="insumo",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("CONSUMIBLE", "Consumible (Hielo, Comida, Desechables)"),
                    ("MOBILIARIO", "Mobiliario (Se renta: Sillas, Mesas)"),
                    ("SERVICIO", "Personal (Bartender, Staff, Seguridad)"),
                ],
                default="CONSUMIBLE",
                max_length=20,
                verbose_name="Categoría",
            ),
        ),
        migrations.AlterField(
            model_name="itemcotizacion",
            name="cotizacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="comercial.cotizacion",
                verbose_name="Cotización",
            ),
        ),
        migrations.AlterField(
            model_name="itemcotizacion",
            name="descripcion",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Descripción"
            ),
        ),
        migrations.AlterField(
            model_name="movimientodeposito",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
        ),
        migrations.AlterField(
            model_name="movimientodeposito",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AlterField(
            model_name="movimientodeposito",
            name="deposito",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movimientos",
                to="comercial.depositogarantia",
                verbose_name="Depósito",
            ),
        ),
        migrations.AlterField(
            model_name="movimientodeposito",
            name="metodo",
            field=models.CharField(
                choices=[
                    ("PLATAFORMA", "Openpay"),
                    ("TRANSFERENCIA", "Transferencia"),
                    ("EFECTIVO", "Efectivo"),
                    ("TARJETA", "Terminal / tarjeta"),
                    ("NO_APLICA", "No aplica (retención)"),
                ],
                max_length=15,
                verbose_name="Método",
            ),
        ),
        migrations.AlterField(
            model_name="movimientodeposito",
            name="transaccion_openpay",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movimiento_deposito",
                to="comercial.openpaytransaccion",
                verbose_name="Transacción Openpay",
            ),
        ),
        migrations.AlterField(
            model_name="movimientoinventario",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
        ),
        migrations.AlterField(
            model_name="openpaytransaccion",
            name="cotizacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transacciones_openpay",
                to="comercial.cotizacion",
                verbose_name="Cotización",
            ),
        ),
        migrations.AlterField(
            model_name="openpaytransaccion",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
        ),
        migrations.AlterField(
            model_name="pago",
            name="cotizacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pagos",
                to="comercial.cotizacion",
                verbose_name="Cotización",
            ),
        ),
        migrations.AlterField(
            model_name="pago",
            name="metodo",
            field=models.CharField(
                choices=[
                    ("EFECTIVO", "Efectivo"),
                    ("TRANSFERENCIA", "Transferencia Electrónica"),
                    ("TARJETA_CREDITO", "Tarjeta de Crédito"),
                    ("TARJETA_DEBITO", "Tarjeta de Débito"),
                    ("CHEQUE", "Cheque Nominativo"),
                    ("DEPOSITO", "Depósito Bancario"),
                    ("PLATAFORMA", "Plataforma"),
                    ("CONDONACION", "Condonación / Cortesía"),
                    ("OTRO", "Otro Método"),
                ],
                max_length=20,
                verbose_name="Método",
            ),
        ),
        migrations.AlterField(
            model_name="pago",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
        ),
        migrations.AlterField(
            model_name="planpago",
            name="fecha_generacion",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de generación"
            ),
        ),
        migrations.AlterField(
            model_name="portalcliente",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
        ),
        migrations.AlterField(
            model_name="portalcliente",
            name="ultima_visita",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Última visita"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="descripcion",
            field=models.TextField(blank=True, verbose_name="Descripción"),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="telefono",
            field=models.CharField(blank=True, max_length=20, verbose_name="Teléfono"),
        ),
        migrations.AlterField(
            model_name="recordatoriopago",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
        ),
        migrations.AlterField(
            model_name="recordatoriopago",
            name="fecha_envio",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de envío"
            ),
        ),
        migrations.AlterField(
            model_name="subproducto",
            name="descripcion",
            field=models.TextField(blank=True, verbose_name="Descripción"),
        ),
    ]
