# Generated by Django 6.1 on 2026-09-26 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0103_alter_subproducto_options_and_more"),
        ("contabilidad", "0028_cuentas_insumos_impuestos"),
    ]

    operations = [
        migrations.AddField(
            model_name="compra",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("SIN_CLASIFICAR", "Sin Clasificar"),
                    ("INSUMOS", "Insumos para eventos"),
                    ("SERVICIO_EXTERNO", "Servicio Externo"),
                    ("BEBIDAS_SIN_ALCOHOL", "Bebidas Sin Alcohol"),
                    ("BEBIDAS_CON_ALCOHOL", "Bebidas Con Alcohol"),
                    ("LIMPIEZA", "Limpieza Y Desechables"),
                    ("MOBILIARIO_EQ", "Mobiliario Y Equipo"),
                    ("MANTENIMIENTO", "Mantenimiento Y Reparaciones"),
                    ("NOMINA_EXT", "Servicios Staff Externo"),
                    ("IMPUESTOS", "Pago De Impuestos"),
                    ("PUBLICIDAD", "Publicidad Y Marketing"),
                    ("SERVICIOS_ADMON", "Servicios Administrativos Y Bancarios"),
                    ("OTRO", "Otros Gastos"),
                ],
                db_index=True,
                default="SIN_CLASIFICAR",
                help_text="Define la cuenta contable del gasto. Al cambiarla se reclasifica la póliza y el proveedor la recuerda para sus próximas facturas.",
                max_length=20,
                verbose_name="Categoría de gasto",
            ),
        ),
        migrations.AddField(
            model_name="proveedor",
            name="categoria_gasto",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SIN_CLASIFICAR", "Sin Clasificar"),
                    ("INSUMOS", "Insumos para eventos"),
                    ("SERVICIO_EXTERNO", "Servicio Externo"),
                    ("BEBIDAS_SIN_ALCOHOL", "Bebidas Sin Alcohol"),
                    ("BEBIDAS_CON_ALCOHOL", "Bebidas Con Alcohol"),
                    ("LIMPIEZA", "Limpieza Y Desechables"),
                    ("MOBILIARIO_EQ", "Mobiliario Y Equipo"),
                    ("MANTENIMIENTO", "Mantenimiento Y Reparaciones"),
                    ("NOMINA_EXT", "Servicios Staff Externo"),
                    ("IMPUESTOS", "Pago De Impuestos"),
                    ("PUBLICIDAD", "Publicidad Y Marketing"),
                    ("SERVICIOS_ADMON", "Servicios Administrativos Y Bancarios"),
                    ("OTRO", "Otros Gastos"),
                ],
                help_text="Las facturas nuevas de este proveedor entran con esta categoría. Se llena sola la primera vez que clasificas una de sus compras.",
                max_length=20,
                verbose_name="Categoría de gasto",
            ),
        ),
        migrations.AddField(
            model_name="proveedor",
            name="cuenta_gasto",
            field=models.ForeignKey(
                blank=True,
                help_text="Opcional. Cuenta exacta para sus compras (ej. CFE → Energía eléctrica). Sin ella, la cuenta sale de la categoría.",
                limit_choices_to={
                    "activa": True,
                    "permite_movimientos": True,
                    "tipo__in": ("GASTO", "COSTO"),
                },
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="proveedores",
                to="contabilidad.cuentacontable",
                verbose_name="Cuenta contable de gasto",
            ),
        ),
        migrations.AlterField(
            model_name="gasto",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("SIN_CLASIFICAR", "Sin Clasificar"),
                    ("INSUMOS", "Insumos para eventos"),
                    ("SERVICIO_EXTERNO", "Servicio Externo"),
                    ("BEBIDAS_SIN_ALCOHOL", "Bebidas Sin Alcohol"),
                    ("BEBIDAS_CON_ALCOHOL", "Bebidas Con Alcohol"),
                    ("LIMPIEZA", "Limpieza Y Desechables"),
                    ("MOBILIARIO_EQ", "Mobiliario Y Equipo"),
                    ("MANTENIMIENTO", "Mantenimiento Y Reparaciones"),
                    ("NOMINA_EXT", "Servicios Staff Externo"),
                    ("IMPUESTOS", "Pago De Impuestos"),
                    ("PUBLICIDAD", "Publicidad Y Marketing"),
                    ("SERVICIOS_ADMON", "Servicios Administrativos Y Bancarios"),
                    ("OTRO", "Otros Gastos"),
                ],
                default="SIN_CLASIFICAR",
                max_length=20,
                verbose_name="Categoría",
            ),
        ),
    ]
