# Generated by Django 6.1 on 2026-09-28 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0104_clasificacion_compras_por_proveedor"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="depositogarantia",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Depósito en garantía",
                "verbose_name_plural": "Depósitos",
            },
        ),
        migrations.AlterModelOptions(
            name="firmacontrato",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Firma de contrato",
                "verbose_name_plural": "Firmas",
            },
        ),
        migrations.AlterModelOptions(
            name="guiatiposervicio",
            options={
                "verbose_name": "Guía por tipo de servicio",
                "verbose_name_plural": "Guías",
            },
        ),
    ]
