# Generated by Django 6.1 on 2026-09-28 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0105_nombres_cortos_menu"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="asignacionespacio",
            options={
                "verbose_name": "Asignación de espacio",
                "verbose_name_plural": "Ocupación",
            },
        ),
        migrations.AlterModelOptions(
            name="asignacionpersonal",
            options={
                "verbose_name": "Asignación de personal",
                "verbose_name_plural": "Personal",
            },
        ),
        migrations.AlterModelOptions(
            name="constantesistema",
            options={
                "verbose_name": "Constante del Sistema",
                "verbose_name_plural": "Constantes",
            },
        ),
        migrations.AlterModelOptions(
            name="descuento",
            options={
                "ordering": ["-prioridad", "nombre"],
                "verbose_name": "Descuento",
                "verbose_name_plural": "Reglas",
            },
        ),
        migrations.AlterModelOptions(
            name="descuentoaplicado",
            options={
                "ordering": ["-fecha_aplicacion"],
                "verbose_name": "Descuento Aplicado",
                "verbose_name_plural": "Aplicados",
            },
        ),
        migrations.AlterModelOptions(
            name="espaciolanding",
            options={
                "ordering": ["orden"],
                "verbose_name": "Espacio",
                "verbose_name_plural": "Instalaciones",
            },
        ),
        migrations.AlterModelOptions(
            name="openpaytransaccion",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Transacción Openpay",
                "verbose_name_plural": "Transacciones",
            },
        ),
        migrations.AlterModelOptions(
            name="pago",
            options={"verbose_name": "Pago Aprobado", "verbose_name_plural": "Pagos"},
        ),
        migrations.AlterModelOptions(
            name="planpago",
            options={"verbose_name": "Plan de Pago", "verbose_name_plural": "Planes"},
        ),
        migrations.AlterModelOptions(
            name="plantillabarra",
            options={
                "ordering": ["grupo", "orden", "categoria"],
                "verbose_name": "Plantilla de Barra",
                "verbose_name_plural": "Barra",
            },
        ),
        migrations.AlterModelOptions(
            name="portalcliente",
            options={
                "verbose_name": "Portal del Cliente",
                "verbose_name_plural": "Portales",
            },
        ),
        migrations.AlterModelOptions(
            name="preguntafrecuente",
            options={
                "ordering": ["orden"],
                "verbose_name": "Pregunta frecuente",
                "verbose_name_plural": "Preguntas",
            },
        ),
        migrations.AlterModelOptions(
            name="recordatoriopago",
            options={
                "ordering": ["-fecha_envio"],
                "verbose_name": "Recordatorio de Pago",
                "verbose_name_plural": "Recordatorios",
            },
        ),
        migrations.AlterModelOptions(
            name="tipoevento",
            options={
                "ordering": ["orden", "nombre"],
                "verbose_name": "Tipo de Evento",
                "verbose_name_plural": "Tipos",
            },
        ),
    ]
