# Generated by Django 6.1 on 2026-10-01 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0106_nombres_cortos_menu_2"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BloqueoFecha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateField(verbose_name="Desde")),
                (
                    "fecha_fin",
                    models.DateField(
                        help_text="Último día bloqueado (incluido). Para un solo día, la misma fecha que «Desde».",
                        verbose_name="Hasta",
                    ),
                ),
                (
                    "motivo",
                    models.CharField(
                        choices=[
                            ("MANTENIMIENTO", "Mantenimiento"),
                            ("REPARACION", "Reparación"),
                            ("USO_PROPIO", "Uso propio"),
                            ("OTRO", "Otro"),
                        ],
                        default="MANTENIMIENTO",
                        max_length=15,
                        verbose_name="Motivo",
                    ),
                ),
                (
                    "notas",
                    models.TextField(
                        blank=True,
                        help_text="Solo las ve el equipo; nunca se muestran al cliente.",
                        verbose_name="Notas internas",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Desmárcalo para liberar las fechas (el registro se conserva).",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bloqueos_creados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bloqueos_actualizados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bloqueo de fecha",
                "verbose_name_plural": "Bloqueos",
                "ordering": ["-fecha_inicio"],
            },
        ),
    ]
