# Generated by Django 6.1 on 2026-10-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0108_sembrar_preguntas_frecuentes"),
    ]

    operations = [
        migrations.AddField(
            model_name="productocomponente",
            name="fijo_por_evento",
            field=models.BooleanField(
                default=False,
                help_text="Se cobra una sola vez por evento, a su propio precio y aparte del precio del paquete (ej. renta de la Quinta). Sin marcar, va dentro del precio de cada bloque de personas.",
                verbose_name="Una vez por evento",
            ),
        ),
    ]
