# Generated by Django 6.1 on 2026-10-06 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0110_habitacion_dia_pasadia"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="como_nos_encontro",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="Cómo nos encontró"
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="notas_cliente",
            field=models.TextField(blank=True, verbose_name="Notas del cliente"),
        ),
    ]
