# Generated by Django 6.0.1 on 2026-03-07 18:55

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comercial', '0018_proveedor_insumo_proveedor_legacy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnuncioAirbnb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Casa Jardín, Habitación Orquídea', max_length=200, verbose_name='Nombre del Anuncio')),
                ('tipo', models.CharField(choices=[('CASA', 'Casa Completa'), ('HABITACION', 'Habitación en Quinta')], default='HABITACION', max_length=20)),
                ('url_ical', models.URLField(help_text='Obtener en Airbnb > Calendario > Exportar calendario', max_length=500, verbose_name='URL de iCal')),
                ('airbnb_listing_id', models.CharField(blank=True, help_text='Se extrae automáticamente de la URL de iCal', max_length=50, verbose_name='ID de Airbnb')),
                ('afecta_eventos_quinta', models.BooleanField(default=True, help_text='Si está activo, las reservas de este anuncio pueden generar conflictos con eventos', verbose_name='¿Afecta eventos de la Quinta?')),
                ('activo', models.BooleanField(default=True)),
                ('ultima_sincronizacion', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Anuncio Airbnb',
                'verbose_name_plural': 'Anuncios Airbnb',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ReservaAirbnb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid_ical', models.CharField(help_text='Identificador único del evento en el calendario', max_length=255, unique=True, verbose_name='UID de iCal')),
                ('titulo', models.CharField(blank=True, max_length=200, verbose_name='Título/Huésped')),
                ('fecha_inicio', models.DateField(verbose_name='Check-in')),
                ('fecha_fin', models.DateField(verbose_name='Check-out')),
                ('estado', models.CharField(choices=[('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('BLOQUEADA', 'Bloqueado por Host')], default='CONFIRMADA', max_length=20)),
                ('origen', models.CharField(choices=[('AIRBNB', 'Airbnb'), ('MANUAL', 'Registro Manual'), ('EVENTO', 'Bloqueo por Evento QKT')], default='AIRBNB', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='airbnb.anuncioairbnb')),
            ],
            options={
                'verbose_name': 'Reserva Airbnb',
                'verbose_name_plural': 'Reservas Airbnb',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PagoAirbnb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_confirmacion', models.CharField(blank=True, help_text='Código de reserva de Airbnb (ej: HMXXXXXXXX)', max_length=20, verbose_name='Código de Confirmación')),
                ('huesped', models.CharField(max_length=200, verbose_name='Nombre del Huésped')),
                ('fecha_checkin', models.DateField(verbose_name='Check-in')),
                ('fecha_checkout', models.DateField(verbose_name='Check-out')),
                ('monto_bruto', models.DecimalField(decimal_places=2, help_text='Total cobrado al huésped (antes de comisiones)', max_digits=12, verbose_name='Monto Bruto')),
                ('comision_airbnb', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Comisión cobrada por Airbnb (normalmente 3%)', max_digits=12, verbose_name='Comisión Airbnb')),
                ('retencion_isr', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='ISR retenido por plataforma tecnológica', max_digits=12, verbose_name='Retención ISR (4%)')),
                ('retencion_iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='IVA retenido por plataforma tecnológica', max_digits=12, verbose_name='Retención IVA (8%)')),
                ('monto_neto', models.DecimalField(decimal_places=2, help_text='Lo que realmente deposita Airbnb', max_digits=12, verbose_name='Monto Neto Recibido')),
                ('fecha_pago', models.DateField(blank=True, help_text='Fecha en que Airbnb depositó el pago', null=True, verbose_name='Fecha de Pago')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Pago'), ('PAGADO', 'Pagado por Airbnb'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('archivo_csv_origen', models.CharField(blank=True, help_text='Nombre del archivo CSV de donde se importó', max_length=255, verbose_name='Archivo CSV Origen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anuncio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='airbnb.anuncioairbnb')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_airbnb_creados', to=settings.AUTH_USER_MODEL)),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='airbnb.reservaairbnb')),
            ],
            options={
                'verbose_name': 'Pago Airbnb',
                'verbose_name_plural': 'Pagos Airbnb',
                'ordering': ['-fecha_checkin'],
            },
        ),
        migrations.CreateModel(
            name='ConflictoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_conflicto', models.DateField(verbose_name='Fecha del Conflicto')),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Resolver'), ('RESUELTO', 'Resuelto'), ('IGNORADO', 'Ignorado')], default='PENDIENTE', max_length=20)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('notas_resolucion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflictos_airbnb', to='comercial.cotizacion')),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reserva_airbnb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflictos', to='airbnb.reservaairbnb')),
            ],
            options={
                'verbose_name': 'Conflicto de Calendario',
                'verbose_name_plural': 'Conflictos de Calendario',
                'ordering': ['-fecha_conflicto'],
            },
        ),
        migrations.AddIndex(
            model_name='reservaairbnb',
            index=models.Index(fields=['fecha_inicio', 'fecha_fin'], name='airbnb_rese_fecha_i_1c34e6_idx'),
        ),
        migrations.AddIndex(
            model_name='reservaairbnb',
            index=models.Index(fields=['anuncio', 'fecha_inicio'], name='airbnb_rese_anuncio_295ba7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conflictocalendario',
            unique_together={('reserva_airbnb', 'cotizacion', 'fecha_conflicto')},
        ),
    ]
