# Generated by Django 6.0.1 on 2026-03-08 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaairbnb',
            name='estado',
            field=models.CharField(choices=[('CONFIRMADA', 'Confirmada'), ('PENDIENTE', 'Pendiente de Aceptar'), ('CANCELADA', 'Cancelada'), ('BLOQUEADA', 'Bloqueado por Host')], default='CONFIRMADA', max_length=20),
        ),
    ]
