# Generated by Django 5.1.15 on 2026-07-10 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airbnb", "0002_alter_reservaairbnb_estado"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="anuncioairbnb",
            options={
                "ordering": ["nombre"],
                "verbose_name": "Anuncio",
                "verbose_name_plural": "Anuncios",
            },
        ),
        migrations.AlterModelOptions(
            name="pagoairbnb",
            options={
                "ordering": ["-fecha_checkin"],
                "verbose_name": "Pago",
                "verbose_name_plural": "Pagos",
            },
        ),
        migrations.AlterModelOptions(
            name="reservaairbnb",
            options={
                "ordering": ["-fecha_inicio"],
                "verbose_name": "Reserva",
                "verbose_name_plural": "Reservas",
            },
        ),
    ]
