# Generated by Django 6.0.7 on 2026-08-04 22:33

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def _normalizar_antes_del_unique(apps, schema_editor):
    """
    `codigo_confirmacion` pasa a ser único y nullable. Dos cosas del histórico
    lo impedirían y tumbarían el deploy a mitad de la migración:

    1. Varias filas con cadena vacía. En SQL '' no es NULL, así que todas
       chocarían entre sí contra el índice único. Se pasan a NULL, que sí
       admite repetición.
    2. Códigos repetidos de verdad, por reimportaciones del mismo CSV antes de
       que existiera el candado. Se conserva el registro más reciente y a los
       anteriores se les vacía el código, dejando constancia en `notas` para
       que se puedan revisar a mano.
    """
    Pago = apps.get_model('airbnb', 'PagoAirbnb')

    Pago.objects.filter(codigo_confirmacion='').update(codigo_confirmacion=None)

    vistos = {}
    for pago in Pago.objects.exclude(codigo_confirmacion=None).order_by('-id'):
        codigo = pago.codigo_confirmacion
        if codigo in vistos:
            pago.notas = (
                f"{pago.notas}\n[migración 0004] Código duplicado {codigo}; "
                f"se conservó en el pago #{vistos[codigo]}."
            ).strip()
            pago.codigo_confirmacion = None
            pago.save(update_fields=['codigo_confirmacion', 'notas'])
        else:
            vistos[codigo] = pago.id


def _rescatar_impuesto_hospedaje(apps, schema_editor):
    """
    El ISH se guardaba como texto dentro de `notas`
    ("Impuesto hospedaje: $123.45") porque no había campo. Se recupera al
    campo nuevo para no perder el histórico; la nota se deja intacta como
    respaldo de la conversión.
    """
    import re as _re
    from decimal import Decimal as _D, InvalidOperation

    Pago = apps.get_model('airbnb', 'PagoAirbnb')
    patron = _re.compile(r'Impuesto hospedaje:\s*\$?\s*([\d,]+\.?\d*)')

    for pago in Pago.objects.filter(notas__contains='Impuesto hospedaje'):
        encontrado = patron.search(pago.notas or '')
        if not encontrado:
            continue
        try:
            pago.impuesto_hospedaje = _D(encontrado.group(1).replace(',', ''))
        except (InvalidOperation, ValueError):
            continue
        pago.save(update_fields=['impuesto_hospedaje'])


def _sin_vuelta_atras(apps, schema_editor):
    """Revertir no restaura nada: los datos rescatados siguen en `notas`."""


class Migration(migrations.Migration):

    dependencies = [
        (
            "airbnb",
            "0003_alter_anuncioairbnb_options_alter_pagoairbnb_options_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(_normalizar_antes_del_unique, _sin_vuelta_atras),
        migrations.AddField(
            model_name="pagoairbnb",
            name="impuesto_hospedaje",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Impuesto estatal liquidado por la plataforma, tal como viene en el CSV.",
                max_digits=12,
                verbose_name="Impuesto al hospedaje (ISH)",
            ),
        ),
        migrations.AddField(
            model_name="pagoairbnb",
            name="origen",
            field=models.CharField(
                choices=[
                    ("CSV", "Importado del CSV de Airbnb"),
                    ("MANUAL", "Capturado a mano"),
                ],
                default="CSV",
                help_text="Un pago capturado a mano no se sobrescribe al reimportar el CSV.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="pagoairbnb",
            name="payout_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Agrupa los pagos que Airbnb depositó juntos, para conciliar contra el banco.",
                max_length=100,
                verbose_name="Depósito de Airbnb",
            ),
        ),
        migrations.AlterField(
            model_name="pagoairbnb",
            name="codigo_confirmacion",
            field=models.CharField(
                blank=True,
                help_text="Código de reserva de Airbnb (ej: HMXXXXXXXX)",
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Código de Confirmación",
            ),
        ),
        migrations.AlterField(
            model_name="pagoairbnb",
            name="estado",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente de Pago"),
                    ("PAGADO", "Pagado por Airbnb"),
                    ("CANCELADO", "Cancelado"),
                    ("REEMBOLSADO", "Reembolsado al huésped"),
                ],
                default="PENDIENTE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pagoairbnb",
            name="retencion_isr",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="ISR retenido por la plataforma, tal como viene en el CSV. La tasa depende de si Airbnb tiene el RFC del anfitrión (art. 113-A LISR).",
                max_digits=12,
                verbose_name="Retención ISR",
            ),
        ),
        migrations.AlterField(
            model_name="pagoairbnb",
            name="retencion_iva",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="IVA retenido por la plataforma, tal como viene en el CSV (art. 18-J LIVA).",
                max_digits=12,
                verbose_name="Retención IVA",
            ),
        ),
        migrations.AddIndex(
            model_name="pagoairbnb",
            index=models.Index(
                fields=["fecha_pago"], name="airbnb_pago_fecha_p_6af271_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pagoairbnb",
            index=models.Index(
                fields=["estado", "-fecha_pago"], name="airbnb_pago_estado_e6af3a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pagoairbnb",
            index=models.Index(
                fields=["anuncio", "-fecha_checkin"],
                name="airbnb_pago_anuncio_771af4_idx",
            ),
        ),
        migrations.RunPython(_rescatar_impuesto_hospedaje, _sin_vuelta_atras),
    ]
