# Generated by Django 6.0.7 on 2026-08-05 03:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airbnb", "0004_pagoairbnb_impuesto_hospedaje_pagoairbnb_origen_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagoairbnb",
            name="iva_trasladado",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="IVA que Airbnb cobró al huésped y te transfiere. Lo enteras tú, no la plataforma.",
                max_digits=12,
                verbose_name="IVA trasladado",
            ),
        ),
        migrations.AlterField(
            model_name="pagoairbnb",
            name="impuesto_hospedaje",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Impuesto estatal que Airbnb retiene y entera por su cuenta. Informativo: no pasa por tus manos.",
                max_digits=12,
                verbose_name="Impuesto al hospedaje (ISH)",
            ),
        ),
    ]
