# Generated by Django 6.1 on 2026-08-07 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airbnb", "0005_pagoairbnb_iva_trasladado_and_more"),
        ("contabilidad", "0015_movimientoestadocuenta_periodo_devengo_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DepositoConciliado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payout_id",
                    models.CharField(
                        help_text="El payout tal como lo trae el CSV.",
                        max_length=100,
                        unique=True,
                        verbose_name="Depósito de Airbnb",
                    ),
                ),
                ("confirmado_at", models.DateTimeField(auto_now_add=True)),
                ("notas", models.TextField(blank=True)),
                (
                    "confirmado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "movimiento",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deposito_airbnb",
                        to="contabilidad.movimientoestadocuenta",
                        verbose_name="Abono del estado de cuenta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Depósito de Airbnb conciliado",
                "verbose_name_plural": "Depósitos de Airbnb conciliados",
                "ordering": ["-confirmado_at"],
            },
        ),
    ]
