# Generated by Django 6.1 on 2026-08-31 19:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airbnb", "0006_depositoconciliado"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagoairbnb",
            name="codigo_confirmacion",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Código de reserva de Airbnb (ej: HMXXXXXXXX). Ya NO es único: una extensión de estancia genera un segundo payout con el mismo código (mismo huésped, cobro nuevo), y cada uno necesita su propio registro para cuadrar con el estado de cuenta y con las facturas del contador.",
                max_length=20,
                null=True,
                verbose_name="Código de Confirmación",
            ),
        ),
        migrations.AddConstraint(
            model_name="pagoairbnb",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("codigo_confirmacion__isnull", False),
                    ("fecha_pago__isnull", False),
                ),
                fields=("codigo_confirmacion", "fecha_pago"),
                name="airbnb_pago_codigo_fecha_unico",
            ),
        ),
    ]
