# Generated by Django 6.0.1 on 2026-01-21 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación')),
                ('origen', models.CharField(choices=[('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('Google', 'Google'), ('Recomendacion', 'Recomendación'), ('Otro', 'Otro')], default='Otro', max_length=50)),
                ('es_cliente_fiscal', models.BooleanField(default=False, verbose_name='¿Datos Fiscales Completos?')),
                ('tipo_persona', models.CharField(choices=[('FISICA', 'Persona Física (Juan Pérez)'), ('MORAL', 'Persona Moral (Empresa S.A. de C.V.)')], default='FISICA', help_text='Define si lleva Retenciones', max_length=10)),
                ('rfc', models.CharField(blank=True, max_length=13, null=True, verbose_name='RFC')),
                ('razon_social', models.CharField(blank=True, max_length=200, null=True, verbose_name='Razón Social')),
                ('codigo_postal_fiscal', models.CharField(blank=True, max_length=5, null=True, verbose_name='C.P. Fiscal')),
                ('regimen_fiscal', models.CharField(blank=True, choices=[('601', '601 - General de Ley Personas Morales'), ('612', '612 - Personas Físicas con Actividades Empresariales'), ('626', '626 - Régimen Simplificado de Confianza (RESICO)'), ('605', '605 - Sueldos y Salarios'), ('603', '603 - Personas Morales con Fines no Lucrativos')], max_length=100, null=True)),
                ('uso_cfdi', models.CharField(blank=True, choices=[('G03', 'G03 - Gastos en general'), ('P01', 'P01 - Por definir'), ('G01', 'G01 - Adquisición de mercancías'), ('D04', 'D04 - Donativos')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('unidad_medida', models.CharField(max_length=50)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_stock', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('categoria', models.CharField(choices=[('CONSUMIBLE', 'Consumible (Se gasta: Hielo, Comida, Desechables)'), ('MOBILIARIO', 'Mobiliario (Se renta: Sillas, Mesas, Manteles)'), ('SERVICIO', 'Personal (RH: Meseros, Seguridad, Staff)')], default='CONSUMIBLE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('margen_ganancia', models.DecimalField(decimal_places=2, default=0.3, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evento', models.DateField()),
                ('requiere_factura', models.BooleanField(default=False, help_text='Si se marca, calcula IVA y Retenciones')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, help_text='Precio del servicio ANTES de impuestos', max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('retencion_isr', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('retencion_iva', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('precio_final', models.DecimalField(decimal_places=2, editable=False, help_text='Total a Pagar (Neto)', max_digits=10)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONFIRMADA', 'Venta Confirmada'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='cotizaciones_pdf/')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comercial.producto')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_gasto', models.DateField(blank=True, help_text='Si subes XML, se llena sola', null=True)),
                ('descripcion', models.CharField(blank=True, help_text='Se llena sola con el XML', max_length=255, null=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, help_text='Se llena sola con el XML', max_digits=10, null=True)),
                ('categoria', models.CharField(choices=[('PROVEEDOR', 'Pago a Proveedor (Hielo, Comida)'), ('NOMINA', 'Pago de Nómina (Meseros, Staff)'), ('SERVICIOS', 'Servicios (Luz, Agua, Gas)'), ('MANTENIMIENTO', 'Mantenimiento Quinta'), ('IMPUESTOS', 'Pago de Impuestos'), ('OTRO', 'Otros Gastos')], default='PROVEEDOR', max_length=20)),
                ('proveedor', models.CharField(blank=True, help_text='Nombre del Emisor (del XML)', max_length=200)),
                ('archivo_xml', models.FileField(blank=True, null=True, upload_to='xml_gastos/')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='pdf_gastos/')),
                ('uuid', models.CharField(blank=True, max_length=36, null=True, unique=True)),
                ('evento_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comercial.cotizacion')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia')], max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='comercial.cotizacion')),
            ],
        ),
        migrations.CreateModel(
            name='ComponenteProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comercial.insumo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='comercial.producto')),
            ],
        ),
    ]
