# Generated by Django 5.2.12 on 2026-04-07 19:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "comercial",
            "0031_espacio_cotizacion_tipo_servicio_asignacionpersonal_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ComunicacionCliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "canal",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email"),
                            ("WHATSAPP", "WhatsApp"),
                            ("SMS", "SMS"),
                            ("PORTAL", "Notificación en portal"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("COTIZACION", "Cotización enviada"),
                            ("CONFIRMACION_PAGO", "Confirmación de pago"),
                            ("REEMBOLSO", "Notificación de reembolso"),
                            ("RECORDATORIO_PAGO", "Recordatorio de pago"),
                            ("CONTRATO", "Contrato"),
                            ("EVENTO_PROXIMO", "Evento próximo"),
                            ("CANCELACION", "Cancelación"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("ENVIADO", "Enviado"),
                            ("ENTREGADO", "Entregado"),
                            ("ABIERTO", "Abierto / leído"),
                            ("FALLIDO", "Fallido"),
                        ],
                        default="PENDIENTE",
                        max_length=15,
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual"),
                            ("SIGNAL", "Signal automático"),
                            ("CRON", "Tarea programada"),
                        ],
                        default="MANUAL",
                        max_length=10,
                    ),
                ),
                (
                    "destinatario",
                    models.CharField(help_text="Email, teléfono o URL", max_length=200),
                ),
                ("asunto", models.CharField(blank=True, max_length=255)),
                ("cuerpo", models.TextField(blank=True)),
                ("error", models.TextField(blank=True)),
                (
                    "fecha_envio",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("fecha_entrega", models.DateTimeField(blank=True, null=True)),
                ("fecha_apertura", models.DateTimeField(blank=True, null=True)),
                (
                    "proveedor_id",
                    models.CharField(
                        blank=True,
                        help_text="ID externo (Brevo, WhatsApp, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "cotizacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comunicaciones",
                        to="comercial.cotizacion",
                    ),
                ),
                (
                    "pago",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comunicaciones",
                        to="comercial.pago",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comunicación con cliente",
                "verbose_name_plural": "Comunicaciones con clientes",
                "ordering": ["-fecha_envio"],
                "indexes": [
                    models.Index(
                        fields=["cotizacion", "-fecha_envio"],
                        name="comunicacio_cotizac_95c175_idx",
                    ),
                    models.Index(
                        fields=["estado", "canal"], name="comunicacio_estado_c0720c_idx"
                    ),
                ],
            },
        ),
    ]
