# Generated by Django 6.1 on 2026-08-10 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comunicacion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comunicacioncliente",
            name="clave_idempotencia",
            field=models.CharField(
                blank=True,
                help_text="Evita envíos duplicados del mismo evento por el mismo canal.",
                max_length=191,
                null=True,
                unique=True,
                verbose_name="Clave de idempotencia",
            ),
        ),
    ]
