# Generated by Django 6.1 on 2026-09-25 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comunicacion", "0002_comunicacioncliente_clave_idempotencia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comunicacioncliente",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("COTIZACION", "Cotización enviada"),
                    ("CONFIRMACION_PAGO", "Confirmación de pago"),
                    ("REEMBOLSO", "Notificación de reembolso"),
                    ("RECORDATORIO_PAGO", "Recordatorio de pago"),
                    ("CONTRATO", "Contrato"),
                    ("EVENTO_PROXIMO", "Evento próximo"),
                    ("CANCELACION", "Cancelación"),
                    ("FACTURA", "Factura emitida"),
                    ("OTRO", "Otro"),
                ],
                max_length=25,
            ),
        ),
    ]
