# Generated by Django 6.1 on 2026-09-26 00:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0103_alter_subproducto_options_and_more"),
        ("comunicacion", "0003_tipo_factura"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comunicacioncliente",
            name="cotizacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comunicaciones",
                to="comercial.cotizacion",
                verbose_name="Cotización",
            ),
        ),
        migrations.AlterField(
            model_name="comunicacioncliente",
            name="fecha_envio",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Fecha de envío"
            ),
        ),
        migrations.AlterField(
            model_name="comunicacioncliente",
            name="proveedor_id",
            field=models.CharField(
                blank=True,
                help_text="ID externo (Brevo, WhatsApp, etc.)",
                max_length=100,
                verbose_name="ID del proveedor",
            ),
        ),
        migrations.AlterField(
            model_name="comunicacioncliente",
            name="trigger",
            field=models.CharField(
                choices=[
                    ("MANUAL", "Manual"),
                    ("SIGNAL", "Signal automático"),
                    ("CRON", "Tarea programada"),
                ],
                default="MANUAL",
                max_length=10,
                verbose_name="Disparador",
            ),
        ),
    ]
