# Generated by Django 6.1 on 2026-09-28 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comunicacion", "0004_alter_comunicacioncliente_cotizacion_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comunicacioncliente",
            options={
                "ordering": ["-fecha_envio"],
                "verbose_name": "Comunicación con cliente",
                "verbose_name_plural": "Bitácora",
            },
        ),
    ]
