# Generated by Django 6.1 on 2026-09-29 23:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0106_nombres_cortos_menu_2"),
        ("comunicacion", "0005_nombres_cortos_menu_2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comunicacioncliente",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("COTIZACION", "Cotización enviada"),
                    ("CONFIRMACION_PAGO", "Confirmación de pago"),
                    ("REEMBOLSO", "Notificación de reembolso"),
                    ("RECORDATORIO_PAGO", "Recordatorio de pago"),
                    ("CONTRATO", "Contrato"),
                    ("EVENTO_PROXIMO", "Evento próximo"),
                    ("CANCELACION", "Cancelación"),
                    ("FACTURA", "Factura emitida"),
                    ("AGENTE_IA", "Respuesta del agente de WhatsApp"),
                    ("OTRO", "Otro"),
                ],
                max_length=25,
            ),
        ),
        migrations.CreateModel(
            name="ConversacionWhatsApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Teléfono"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nombre en WhatsApp"
                    ),
                ),
                (
                    "historial",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Historial para la IA"
                    ),
                ),
                (
                    "requiere_humano",
                    models.BooleanField(
                        default=False,
                        help_text="El agente pidió ayuda y dejó de contestar. Desmárcalo para reactivarlo.",
                        verbose_name="Requiere humano",
                    ),
                ),
                (
                    "motivo_humano",
                    models.CharField(blank=True, max_length=300, verbose_name="Motivo"),
                ),
                (
                    "pausado_hasta",
                    models.DateTimeField(
                        blank=True,
                        help_text="Se llena solo cuando alguien contesta desde la app de WhatsApp.",
                        null=True,
                        verbose_name="Agente en pausa hasta",
                    ),
                ),
                (
                    "ultimo_mensaje",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Último mensaje"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversaciones_whatsapp",
                        to="comercial.cliente",
                        verbose_name="Cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversación de WhatsApp",
                "verbose_name_plural": "Conversaciones",
                "ordering": ["-ultimo_mensaje"],
            },
        ),
        migrations.CreateModel(
            name="MensajeWhatsApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direccion",
                    models.CharField(
                        choices=[
                            ("ENTRADA", "Cliente"),
                            ("AGENTE", "Agente IA"),
                            ("HUMANO", "Persona (app)"),
                        ],
                        max_length=10,
                        verbose_name="Quién",
                    ),
                ),
                ("texto", models.TextField(blank=True, verbose_name="Texto")),
                (
                    "wamid",
                    models.CharField(
                        blank=True,
                        max_length=191,
                        null=True,
                        unique=True,
                        verbose_name="ID de Meta",
                    ),
                ),
                (
                    "procesado",
                    models.BooleanField(default=False, verbose_name="Procesado"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Fecha"
                    ),
                ),
                (
                    "conversacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensajes",
                        to="comunicacion.conversacionwhatsapp",
                        verbose_name="Conversación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensaje de WhatsApp",
                "verbose_name_plural": "Mensajes",
                "ordering": ["created_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["conversacion", "procesado"],
                        name="comunicacio_convers_3bdfab_idx",
                    )
                ],
            },
        ),
    ]
