# Generated by Django 6.1 on 2026-10-07 00:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comunicacion", "0006_agente_whatsapp"),
    ]

    operations = [
        migrations.AddField(
            model_name="mensajewhatsapp",
            name="automatico",
            field=models.BooleanField(default=False, verbose_name="Automático"),
        ),
        migrations.AddField(
            model_name="mensajewhatsapp",
            name="modelo",
            field=models.CharField(
                blank=True, max_length=60, verbose_name="Modelo de IA"
            ),
        ),
        migrations.AddField(
            model_name="mensajewhatsapp",
            name="tokens_cache_escritura",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Tokens escritos en caché"
            ),
        ),
        migrations.AddField(
            model_name="mensajewhatsapp",
            name="tokens_cache_lectura",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Tokens leídos de caché"
            ),
        ),
        migrations.AddField(
            model_name="mensajewhatsapp",
            name="tokens_entrada",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Tokens de entrada"
            ),
        ),
        migrations.AddField(
            model_name="mensajewhatsapp",
            name="tokens_salida",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Tokens de salida"
            ),
        ),
        migrations.AlterField(
            model_name="comunicacioncliente",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("COTIZACION", "Cotización enviada"),
                    ("CONFIRMACION_PAGO", "Confirmación de pago"),
                    ("REEMBOLSO", "Notificación de reembolso"),
                    ("RECORDATORIO_PAGO", "Recordatorio de pago"),
                    ("CONTRATO", "Contrato"),
                    ("EVENTO_PROXIMO", "Evento próximo"),
                    ("CANCELACION", "Cancelación"),
                    ("FACTURA", "Factura emitida"),
                    ("AGENTE_IA", "Respuesta del agente de WhatsApp"),
                    ("SEGUIMIENTO", "Seguimiento de cotización sin pago"),
                    ("OTRO", "Otro"),
                ],
                max_length=25,
            ),
        ),
        migrations.CreateModel(
            name="PaseAHumano",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "motivo",
                    models.CharField(blank=True, max_length=300, verbose_name="Motivo"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Fecha"
                    ),
                ),
                (
                    "conversacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pases_a_humano",
                        to="comunicacion.conversacionwhatsapp",
                        verbose_name="Conversación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pase a humano",
                "verbose_name_plural": "Pases",
                "ordering": ["-created_at"],
            },
        ),
    ]
