# Generated by Django 6.1 on 2026-10-07 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comunicacion", "0007_agente_tablero_seguimiento"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversacionwhatsapp",
            name="consentimiento_en",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Aceptó el aviso el"
            ),
        ),
        migrations.AddField(
            model_name="conversacionwhatsapp",
            name="consentimiento_marketing",
            field=models.BooleanField(default=False, verbose_name="Aceptó promociones"),
        ),
        migrations.AddField(
            model_name="conversacionwhatsapp",
            name="consentimiento_wamid",
            field=models.CharField(
                blank=True, max_length=191, verbose_name="Mensaje con que aceptó"
            ),
        ),
    ]
