# Generated by Django 6.1 on 2026-10-07 18:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comunicacion", "0008_consentimiento_chat"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreguntaSinRespuesta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pregunta", models.CharField(max_length=300, verbose_name="Pregunta")),
                (
                    "resumida_en",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Resumida el"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Fecha"
                    ),
                ),
                (
                    "conversacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preguntas_sin_respuesta",
                        to="comunicacion.conversacionwhatsapp",
                        verbose_name="Conversación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pregunta sin respuesta",
                "verbose_name_plural": "Pendientes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RespuestaBloqueada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.TextField(verbose_name="Respuesta detenida")),
                (
                    "capa",
                    models.CharField(
                        choices=[
                            ("FILTRO", "Filtro automático"),
                            ("JUEZ", "Juez de IA"),
                        ],
                        max_length=10,
                        verbose_name="Quién la detuvo",
                    ),
                ),
                (
                    "motivo",
                    models.CharField(blank=True, max_length=300, verbose_name="Motivo"),
                ),
                (
                    "avisada_al_modelo",
                    models.BooleanField(
                        default=False, verbose_name="Avisada al modelo"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Fecha"
                    ),
                ),
                (
                    "conversacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respuestas_bloqueadas",
                        to="comunicacion.conversacionwhatsapp",
                        verbose_name="Conversación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Respuesta bloqueada",
                "verbose_name_plural": "Bloqueadas",
                "ordering": ["-created_at"],
            },
        ),
    ]
