# Generated by Django 6.1 on 2026-10-07 22:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comunicacion", "0009_guardia_agente"),
    ]

    operations = [
        migrations.CreateModel(
            name="BajaWhatsApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="Teléfono"
                    ),
                ),
                (
                    "origen",
                    models.CharField(
                        choices=[
                            ("PALABRA", "Escribió BAJA"),
                            ("AGENTE", "Se lo pidió a Kooxi"),
                        ],
                        max_length=10,
                        verbose_name="Cómo la pidió",
                    ),
                ),
                (
                    "texto",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Mensaje del cliente"
                    ),
                ),
                (
                    "wamid",
                    models.CharField(
                        blank=True,
                        max_length=191,
                        verbose_name="ID del mensaje en WhatsApp",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Fecha",
                    ),
                ),
            ],
            options={
                "verbose_name": "Baja de mensajes",
                "verbose_name_plural": "Bajas",
                "ordering": ["-created_at"],
            },
        ),
    ]
